.TH "androidx.browser.customtabs.CustomTabsClient_CustomTabsCallbackImpl" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
androidx.browser.customtabs.CustomTabsClient_CustomTabsCallbackImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.browser\&.customtabs\&.CustomTabsCallback, mono\&.android\&.IGCUserPeer, androidx\&.browser\&.customtabs\&.CustomTabsCallback, mono\&.android\&.IGCUserPeer, androidx\&.browser\&.customtabs\&.CustomTabsCallback, mono\&.android\&.IGCUserPeer, androidx\&.browser\&.customtabs\&.CustomTabsCallback, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomTabsClient_CustomTabsCallbackImpl\fP ()"
.br
.ti -1c
.RI "void \fBonNavigationEvent\fP (int p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBextraCallback\fP (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCustomTabsClient_CustomTabsCallbackImpl\fP ()"
.br
.ti -1c
.RI "void \fBonNavigationEvent\fP (int p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBextraCallback\fP (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCustomTabsClient_CustomTabsCallbackImpl\fP ()"
.br
.ti -1c
.RI "void \fBonNavigationEvent\fP (int p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBextraCallback\fP (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCustomTabsClient_CustomTabsCallbackImpl\fP ()"
.br
.ti -1c
.RI "void \fBonNavigationEvent\fP (int p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBextraCallback\fP (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.CustomTabsClient_CustomTabsCallbackImpl ()"

.PP
Definition at line 20 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.CustomTabsClient_CustomTabsCallbackImpl ()"

.PP
Definition at line 20 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.CustomTabsClient_CustomTabsCallbackImpl ()"

.PP
Definition at line 20 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.CustomTabsClient_CustomTabsCallbackImpl ()"

.PP
Definition at line 20 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.extraCallback (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 36 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.extraCallback (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 36 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.extraCallback (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 36 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.extraCallback (java\&.lang\&.String p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 36 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 44 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 44 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 44 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 44 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidClearReferences ()"

.PP
Definition at line 51 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidClearReferences ()"

.PP
Definition at line 51 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidClearReferences ()"

.PP
Definition at line 51 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.monodroidClearReferences ()"

.PP
Definition at line 51 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.onNavigationEvent (int p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 28 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.onNavigationEvent (int p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 28 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.onNavigationEvent (int p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 28 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SS "void androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.onNavigationEvent (int p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 28 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String androidx\&.browser\&.customtabs\&.CustomTabsClient_CustomTabsCallbackImpl\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file CustomTabsClient_CustomTabsCallbackImpl\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
