.TH "Application_Green_Quake.Models.EnergyPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.EnergyPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBhangDryCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBfullDryerCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBinsulateWaterCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBefficientThermostatCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBisolateHomeCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBledLightBulbCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBfullMachineCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBmicrowaveCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBoffSocketCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBreBatteriesCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBfridgeCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBdraftSealCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBductSealCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBsolarPanelCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file EnergyPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.draftSealCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.ductSealCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.efficientThermostatCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.fridgeCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.fullDryerCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.fullMachineCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.hangDryCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.insulateWaterCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.isolateHomeCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.ledLightBulbCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.microwaveCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.offSocketCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.reBatteriesCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file EnergyPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.EnergyPoints\&.solarPanelCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file EnergyPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.EnergyPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file EnergyPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
