.TH "Application_Green_Quake.Views.ProfilePage.BadgePopUp" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.ProfilePage.BadgePopUp
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.RgPlugins\&.Popup\&.Pages\&.PopupPage, and global\&.RgPlugins\&.Popup\&.Pages\&.PopupPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadgePopUp\fP (int number, int stage)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file BadgePopUp\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.ProfilePage\&.BadgePopUp\&.BadgePopUp (int number, int stage)"
\fBThe\fP \fBBadgePopUp\fP Constructor 
.PP
\fBParameters\fP
.RS 4
\fInumber\fP is used to specify which badge it is 
.br
\fIstage\fP is used to specify what stage the badge is in 
.RE
.PP

.PP
Definition at line 23 of file BadgePopUp\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Application_Green_Quake\&.Views\&.ProfilePage\&.BadgePopUp\&.OnAppearing ()\fC [protected]\fP"
This function is called before the page is displayed\&. It displays the correct information and badge based on what was passed into the constructor 
.PP
Definition at line 33 of file BadgePopUp\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
