.TH "Application_Green_Quake.Views.EcoActions.Shopping" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.Shopping
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClothNapkins\fP"
.br
.ti -1c
.RI "class \fBClothTowels\fP"
.br
.ti -1c
.RI "class \fBEcoFreidnlyApplicance\fP"
.br
.ti -1c
.RI "class \fBEcoFriendlyProduct\fP"
.br
.ti -1c
.RI "class \fBEcoFriendlyToothbrush\fP"
.br
.ti -1c
.RI "class \fBEthicalClothes\fP"
.br
.ti -1c
.RI "class \fBFoodInBulk\fP"
.br
.ti -1c
.RI "class \fBLocalProduct\fP"
.br
.ti -1c
.RI "class \fBLooseLeafTea\fP"
.br
.ti -1c
.RI "class \fBOrganicFood\fP"
.br
.ti -1c
.RI "class \fBPurchaseReusableWater\fP"
.br
.ti -1c
.RI "class \fBReBatteries\fP"
.br
.ti -1c
.RI "class \fBReusableBag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
