.TH "Application_Green_Quake.App" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.App
.SH SYNOPSIS
.br
.PP
.PP
Inherits Application, global\&.XamarinForms\&.Application, and global\&.XamarinForms\&.Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApp\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStart\fP ()"
.br
.ti -1c
.RI "override void \fBOnSleep\fP ()"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file App\&.xaml\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.App\&.App ()"

.PP
Definition at line 21 of file App\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Application_Green_Quake\&.App\&.OnResume ()\fC [protected]\fP"

.PP
Definition at line 56 of file App\&.xaml\&.cs\&.
.SS "override void Application_Green_Quake\&.App\&.OnSleep ()\fC [protected]\fP"

.PP
Definition at line 52 of file App\&.xaml\&.cs\&.
.SS "override void Application_Green_Quake\&.App\&.OnStart ()\fC [protected]\fP"

.PP
Definition at line 42 of file App\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
