.TH "Application Green Quake/obj/Release/netstandard2.0/Application Green Quake.AssemblyInfo.cs" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Release/netstandard2.0/Application Green Quake.AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
