.TH "Application_Green_Quake" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDroid\fP"
.br
.ti -1c
.RI "namespace \fBiOS\fP"
.br
.ti -1c
.RI "namespace \fBModels\fP"
.br
.ti -1c
.RI "namespace \fBViewModels\fP"
.br
.ti -1c
.RI "namespace \fBViews\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.ti -1c
.RI "interface \fBIAuth\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
