.TH "Application_Green_Quake.Views.ProfilePage.UploadImagePopUp" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.ProfilePage.UploadImagePopUp
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.RgPlugins\&.Popup\&.Pages\&.PopupPage, and global\&.RgPlugins\&.Popup\&.Pages\&.PopupPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUploadImagePopUp\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MediaFile \fBFile\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file UploadImagePopUp\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.ProfilePage\&.UploadImagePopUp\&.UploadImagePopUp ()"

.PP
Definition at line 29 of file UploadImagePopUp\&.xaml\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "MediaFile Application_Green_Quake\&.Views\&.ProfilePage\&.UploadImagePopUp\&.File\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file UploadImagePopUp\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
