.TH "Application_Green_Quake.Droid.Resource.Plurals" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Plurals
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBmtrl_badge_content_description\fP = 2131558400"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22950 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Plurals\&.mtrl_badge_content_description = 2131558400\fC [static]\fP"

.PP
Definition at line 22954 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
