.TH "Application_Green_Quake.ViewModels.WaterPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.WaterPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBCisternPoints\fP ()"
.br
.ti -1c
.RI "async void \fBBarrelPoints\fP ()"
.br
.ti -1c
.RI "async void \fBReWaterPoints\fP ()"
.br
.ti -1c
.RI "async void \fBShowerBucketPoints\fP ()"
.br
.ti -1c
.RI "async void \fBWSSowerHeadPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file WaterPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.WaterPointsUpdate\&.BarrelPoints ()"
This function updates the points in the Water category by ten points\&. It also increments the number of logs logged in the Water category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 134 of file WaterPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WaterPointsUpdate\&.CisternPoints ()"
This function updates the points in the Water category by ten points\&. It also increments the number of logs logged in the Water category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 34 of file WaterPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WaterPointsUpdate\&.ReWaterPoints ()"
This function updates the points in the Water category by eight points\&. It also increments the number of logs logged in the Water category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 234 of file WaterPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WaterPointsUpdate\&.ShowerBucketPoints ()"
This function updates the points in the Water category by eight points\&. It also increments the number of logs logged in the Water category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 334 of file WaterPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WaterPointsUpdate\&.WSSowerHeadPoints ()"
This function updates the points in the Water category by ten points\&. It also increments the number of logs logged in the Water category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 434 of file WaterPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
