.TH "Application_Green_Quake.iOS.AuthiOS" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.iOS.AuthiOS
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApplication_Green_Quake\&.IAuth\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsSignIn\fP ()"
.br
.ti -1c
.RI "async Task< string > \fBLoginWithEmailAndPassword\fP (string email, string password)"
.br
.ti -1c
.RI "bool \fBSignOut\fP ()"
.br
.ti -1c
.RI "async Task< string > \fBSignUpWithEmailAndPassword\fP (string email, string password)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file AuthiOS\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Application_Green_Quake\&.iOS\&.AuthiOS\&.IsSignIn ()"

.PP
Implements \fBApplication_Green_Quake\&.IAuth\fP\&.
.PP
Definition at line 13 of file AuthiOS\&.cs\&.
.SS "async Task<string> Application_Green_Quake\&.iOS\&.AuthiOS\&.LoginWithEmailAndPassword (string email, string password)"

.PP
Implements \fBApplication_Green_Quake\&.IAuth\fP\&.
.PP
Definition at line 19 of file AuthiOS\&.cs\&.
.SS "bool Application_Green_Quake\&.iOS\&.AuthiOS\&.SignOut ()"

.PP
Implements \fBApplication_Green_Quake\&.IAuth\fP\&.
.PP
Definition at line 32 of file AuthiOS\&.cs\&.
.SS "async Task<string> Application_Green_Quake\&.iOS\&.AuthiOS\&.SignUpWithEmailAndPassword (string email, string password)"

.PP
Implements \fBApplication_Green_Quake\&.IAuth\fP\&.
.PP
Definition at line 45 of file AuthiOS\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
