.TH "Application_Green_Quake.Views.ProfilePage.TopTabProfile" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.ProfilePage.TopTabProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.ContentPage, global\&.XamarinForms\&.ContentPage, and ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTopTabProfile\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file TopTabProfile\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.ProfilePage\&.TopTabProfile\&.TopTabProfile ()"

.PP
Definition at line 29 of file TopTabProfile\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async void Application_Green_Quake\&.Views\&.ProfilePage\&.TopTabProfile\&.OnAppearing ()\fC [protected]\fP"
This function is called before the page is displayed\&. It displays the images as the criteria are met and also the bio and username\&. It also calulates the players level and progress and displays the progress to the next level on a progress bar\&. 
.PP
Definition at line 38 of file TopTabProfile\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
