.TH "Application_Green_Quake.ViewModels.ShoppingPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.ShoppingPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBClothNapkinsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBClothTowelsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBAppliancePoints\fP ()"
.br
.ti -1c
.RI "async void \fBProductPoints\fP ()"
.br
.ti -1c
.RI "async void \fBEcoToothbrushPoints\fP ()"
.br
.ti -1c
.RI "async void \fBClothesPoints\fP ()"
.br
.ti -1c
.RI "async void \fBFoodInBulkPoints\fP ()"
.br
.ti -1c
.RI "async void \fBLocalProductPoints\fP ()"
.br
.ti -1c
.RI "async void \fBTeaPoints\fP ()"
.br
.ti -1c
.RI "async void \fBOrganicPoints\fP ()"
.br
.ti -1c
.RI "async void \fBReWaterPoints\fP ()"
.br
.ti -1c
.RI "async void \fBReBattereisPoints\fP ()"
.br
.ti -1c
.RI "async void \fBReBagPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file ShoppingPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.AppliancePoints ()"
This function updates the points in the Shopping category by two points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 338 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ClothesPoints ()"
This function updates the points in the Shopping category by ten points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 782 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ClothNapkinsPoints ()"
This function updates the points in the Shopping category by two points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 42 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ClothTowelsPoints ()"
This function updates the points in the Shopping category by two points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 190 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.EcoToothbrushPoints ()"
This function updates the points in the Shopping category by six points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 634 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.FoodInBulkPoints ()"
This function updates the points in the Shopping category by six points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 930 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.LocalProductPoints ()"
This function updates the points in the Shopping category by eight points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1078 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.OrganicPoints ()"
This function updates the points in the Shopping category by eight points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1374 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ProductPoints ()"
This function updates the points in the Shopping category by four points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 486 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ReBagPoints ()"
This function updates the points in the Shopping category by eight points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1818 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ReBattereisPoints ()"
This function updates the points in the Shopping category by six points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1670 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.ReWaterPoints ()"
This function updates the points in the Shopping category by eight points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1522 of file ShoppingPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.ShoppingPointsUpdate\&.TeaPoints ()"
This function updates the points in the Shopping category by four points\&. It also increments the number of logs logged in the Shopping category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1226 of file ShoppingPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
