.TH "Application_Green_Quake.Models.Users" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.Users
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbio\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBnation\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Users\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Application_Green_Quake\&.Models\&.Users\&.bio\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file Users\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.Users\&.nation\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file Users\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.Users\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file Users\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
