.TH "Application_Green_Quake.Views.EcoActions.FoodAndDrink.SaveLeftOvers" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.FoodAndDrink.SaveLeftOvers
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.ContentPage, global\&.XamarinForms\&.ContentPage, and ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSaveLeftOvers\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file SaveLeftOvers\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.EcoActions\&.FoodAndDrink\&.SaveLeftOvers\&.SaveLeftOvers ()"

.PP
Definition at line 21 of file SaveLeftOvers\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Application_Green_Quake\&.Views\&.EcoActions\&.FoodAndDrink\&.SaveLeftOvers\&.OnAppearing ()\fC [protected]\fP"
This function is called before the page is displayed and it created an object ans uses it's SetLvl method to set the players level in the app and display it in the navigation bar\&. 
.PP
Definition at line 61 of file SaveLeftOvers\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
