.TH "Application_Green_Quake.ViewModels.OutdoorsPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.OutdoorsPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBCampingPoints\fP ()"
.br
.ti -1c
.RI "async void \fBPicnicPoints\fP ()"
.br
.ti -1c
.RI "async void \fBPlantBushPoints\fP ()"
.br
.ti -1c
.RI "async void \fBPlantTreePoints\fP ()"
.br
.ti -1c
.RI "async void \fBPlantFlowerPoints\fP ()"
.br
.ti -1c
.RI "async void \fBScoopPoints\fP ()"
.br
.ti -1c
.RI "async void \fBFruitGardenPoints\fP ()"
.br
.ti -1c
.RI "async void \fBHerbGardenPoints\fP ()"
.br
.ti -1c
.RI "async void \fBVegetableGardenPoints\fP ()"
.br
.ti -1c
.RI "async void \fBBirdFeederPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file OutdoorsPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.BirdFeederPoints ()"
This function updates the points in the Outdoors category by ten points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1218 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.CampingPoints ()"
This function updates the points in the Outdoors category by ten points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 39 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.FruitGardenPoints ()"
This function updates the points in the Outdoors category by ten points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 825 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.HerbGardenPoints ()"
This function updates the points in the Outdoors category by ten points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 956 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.PicnicPoints ()"
This function updates the points in the Outdoors category by six points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 170 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.PlantBushPoints ()"
This function updates the points in the Outdoors category by eight points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 301 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.PlantFlowerPoints ()"
This function updates the points in the Outdoors category by eight points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 563 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.PlantTreePoints ()"
This function updates the points in the Outdoors category by ten points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 432 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.ScoopPoints ()"
This function updates the points in the Outdoors category by four points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 694 of file OutdoorsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.OutdoorsPointsUpdate\&.VegetableGardenPoints ()"
This function updates the points in the Outdoors category by ten points\&. It also increments the number of logs logged in the Outdoors category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1087 of file OutdoorsPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
