.TH "Application_Green_Quake.Droid.Resource.Animation" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Animation
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_fade_in\fP = 2130771968"
.br
.ti -1c
.RI "const int \fBabc_fade_out\fP = 2130771969"
.br
.ti -1c
.RI "const int \fBabc_grow_fade_in_from_bottom\fP = 2130771970"
.br
.ti -1c
.RI "const int \fBabc_popup_enter\fP = 2130771971"
.br
.ti -1c
.RI "const int \fBabc_popup_exit\fP = 2130771972"
.br
.ti -1c
.RI "const int \fBabc_shrink_fade_out_from_bottom\fP = 2130771973"
.br
.ti -1c
.RI "const int \fBabc_slide_in_bottom\fP = 2130771974"
.br
.ti -1c
.RI "const int \fBabc_slide_in_top\fP = 2130771975"
.br
.ti -1c
.RI "const int \fBabc_slide_out_bottom\fP = 2130771976"
.br
.ti -1c
.RI "const int \fBabc_slide_out_top\fP = 2130771977"
.br
.ti -1c
.RI "const int \fBabc_tooltip_enter\fP = 2130771978"
.br
.ti -1c
.RI "const int \fBabc_tooltip_exit\fP = 2130771979"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_to_checked_box_inner_merged_animation\fP = 2130771980"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_to_checked_box_outer_merged_animation\fP = 2130771981"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_to_checked_icon_null_animation\fP = 2130771982"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_to_unchecked_box_inner_merged_animation\fP = 2130771983"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_to_unchecked_check_path_merged_animation\fP = 2130771984"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_to_unchecked_icon_null_animation\fP = 2130771985"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_off_mtrl_dot_group_animation\fP = 2130771986"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_off_mtrl_ring_outer_animation\fP = 2130771987"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_off_mtrl_ring_outer_path_animation\fP = 2130771988"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_on_mtrl_dot_group_animation\fP = 2130771989"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_on_mtrl_ring_outer_animation\fP = 2130771990"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_on_mtrl_ring_outer_path_animation\fP = 2130771991"
.br
.ti -1c
.RI "const int \fBdesign_bottom_sheet_slide_in\fP = 2130771992"
.br
.ti -1c
.RI "const int \fBdesign_bottom_sheet_slide_out\fP = 2130771993"
.br
.ti -1c
.RI "const int \fBdesign_snackbar_in\fP = 2130771994"
.br
.ti -1c
.RI "const int \fBdesign_snackbar_out\fP = 2130771995"
.br
.ti -1c
.RI "const int \fBEnterFromLeft\fP = 2130771996"
.br
.ti -1c
.RI "const int \fBEnterFromRight\fP = 2130771997"
.br
.ti -1c
.RI "const int \fBExitToLeft\fP = 2130771998"
.br
.ti -1c
.RI "const int \fBExitToRight\fP = 2130771999"
.br
.ti -1c
.RI "const int \fBfragment_fast_out_extra_slow_in\fP = 2130772000"
.br
.ti -1c
.RI "const int \fBmtrl_bottom_sheet_slide_in\fP = 2130772001"
.br
.ti -1c
.RI "const int \fBmtrl_bottom_sheet_slide_out\fP = 2130772002"
.br
.ti -1c
.RI "const int \fBmtrl_card_lowers_interpolator\fP = 2130772003"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15591 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_fade_in = 2130771968\fC [static]\fP"

.PP
Definition at line 15595 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_fade_out = 2130771969\fC [static]\fP"

.PP
Definition at line 15598 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_grow_fade_in_from_bottom = 2130771970\fC [static]\fP"

.PP
Definition at line 15601 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_popup_enter = 2130771971\fC [static]\fP"

.PP
Definition at line 15604 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_popup_exit = 2130771972\fC [static]\fP"

.PP
Definition at line 15607 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_shrink_fade_out_from_bottom = 2130771973\fC [static]\fP"

.PP
Definition at line 15610 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_slide_in_bottom = 2130771974\fC [static]\fP"

.PP
Definition at line 15613 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_slide_in_top = 2130771975\fC [static]\fP"

.PP
Definition at line 15616 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_slide_out_bottom = 2130771976\fC [static]\fP"

.PP
Definition at line 15619 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_slide_out_top = 2130771977\fC [static]\fP"

.PP
Definition at line 15622 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_tooltip_enter = 2130771978\fC [static]\fP"

.PP
Definition at line 15625 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.abc_tooltip_exit = 2130771979\fC [static]\fP"

.PP
Definition at line 15628 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_checkbox_to_checked_box_inner_merged_animation = 2130771980\fC [static]\fP"

.PP
Definition at line 15631 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_checkbox_to_checked_box_outer_merged_animation = 2130771981\fC [static]\fP"

.PP
Definition at line 15634 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_checkbox_to_checked_icon_null_animation = 2130771982\fC [static]\fP"

.PP
Definition at line 15637 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_checkbox_to_unchecked_box_inner_merged_animation = 2130771983\fC [static]\fP"

.PP
Definition at line 15640 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_checkbox_to_unchecked_check_path_merged_animation = 2130771984\fC [static]\fP"

.PP
Definition at line 15643 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_checkbox_to_unchecked_icon_null_animation = 2130771985\fC [static]\fP"

.PP
Definition at line 15646 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_radio_to_off_mtrl_dot_group_animation = 2130771986\fC [static]\fP"

.PP
Definition at line 15649 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_radio_to_off_mtrl_ring_outer_animation = 2130771987\fC [static]\fP"

.PP
Definition at line 15652 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_radio_to_off_mtrl_ring_outer_path_animation = 2130771988\fC [static]\fP"

.PP
Definition at line 15655 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_radio_to_on_mtrl_dot_group_animation = 2130771989\fC [static]\fP"

.PP
Definition at line 15658 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_radio_to_on_mtrl_ring_outer_animation = 2130771990\fC [static]\fP"

.PP
Definition at line 15661 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.btn_radio_to_on_mtrl_ring_outer_path_animation = 2130771991\fC [static]\fP"

.PP
Definition at line 15664 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.design_bottom_sheet_slide_in = 2130771992\fC [static]\fP"

.PP
Definition at line 15667 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.design_bottom_sheet_slide_out = 2130771993\fC [static]\fP"

.PP
Definition at line 15670 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.design_snackbar_in = 2130771994\fC [static]\fP"

.PP
Definition at line 15673 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.design_snackbar_out = 2130771995\fC [static]\fP"

.PP
Definition at line 15676 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.EnterFromLeft = 2130771996\fC [static]\fP"

.PP
Definition at line 15679 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.EnterFromRight = 2130771997\fC [static]\fP"

.PP
Definition at line 15682 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.ExitToLeft = 2130771998\fC [static]\fP"

.PP
Definition at line 15685 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.ExitToRight = 2130771999\fC [static]\fP"

.PP
Definition at line 15688 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.fragment_fast_out_extra_slow_in = 2130772000\fC [static]\fP"

.PP
Definition at line 15691 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.mtrl_bottom_sheet_slide_in = 2130772001\fC [static]\fP"

.PP
Definition at line 15694 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.mtrl_bottom_sheet_slide_out = 2130772002\fC [static]\fP"

.PP
Definition at line 15697 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animation\&.mtrl_card_lowers_interpolator = 2130772003\fC [static]\fP"

.PP
Definition at line 15700 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
