.TH "Application_Green_Quake.ViewModels.WorkPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.WorkPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBPaperPoints\fP ()"
.br
.ti -1c
.RI "async void \fBElectonicsOffPoints\fP ()"
.br
.ti -1c
.RI "async void \fBRemoteWorkPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file WorkPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.WorkPointsUpdate\&.ElectonicsOffPoints ()"
This function updates the points in the Work category by six points\&. It also increments the number of logs logged in the Work category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 120 of file WorkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WorkPointsUpdate\&.PaperPoints ()"
This function updates the points in the Work category by four points\&. It also increments the number of logs logged in the Work category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 32 of file WorkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WorkPointsUpdate\&.RemoteWorkPoints ()"
This function updates the points in the Work category by ten points\&. It also increments the number of logs logged in the Work category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 208 of file WorkPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
