.TH "Application_Green_Quake.ViewModels.WastePointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.WastePointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBBillsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBCompostPoints\fP ()"
.br
.ti -1c
.RI "async void \fBSetUpRecyclingBinPoints\fP ()"
.br
.ti -1c
.RI "async void \fBBioBinBagPoints\fP ()"
.br
.ti -1c
.RI "async void \fBRecyclingBinPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file WastePointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.WastePointsUpdate\&.BillsPoints ()"
This function updates the points in the Waste category by four points\&. It also increments the number of logs logged in the Waste category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 35 of file WastePointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WastePointsUpdate\&.BioBinBagPoints ()"
This function updates the points in the Waste category by four points\&. It also increments the number of logs logged in the Waste category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 335 of file WastePointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WastePointsUpdate\&.CompostPoints ()"
This function updates the points in the Waste category by six points\&. It also increments the number of logs logged in the Waste category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 135 of file WastePointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WastePointsUpdate\&.RecyclingBinPoints ()"
This function updates the points in the Waste category by six points\&. It also increments the number of logs logged in the Waste category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 435 of file WastePointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.WastePointsUpdate\&.SetUpRecyclingBinPoints ()"
This function updates the points in the Waste category by ten points\&. It also increments the number of logs logged in the Waste category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 235 of file WastePointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
