.TH "Application_Green_Quake.ViewModels.EnergyPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.EnergyPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBHangDryPoints\fP ()"
.br
.ti -1c
.RI "async void \fBDryerFullPoints\fP ()"
.br
.ti -1c
.RI "async void \fBEfficientThermostatPoints\fP ()"
.br
.ti -1c
.RI "async void \fBInsulateWaterPoints\fP ()"
.br
.ti -1c
.RI "async void \fBIsolateHomePoints\fP ()"
.br
.ti -1c
.RI "async void \fBLedLightsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBMachineFullPoints\fP ()"
.br
.ti -1c
.RI "async void \fBMicrowavePoints\fP ()"
.br
.ti -1c
.RI "async void \fBSocketPoints\fP ()"
.br
.ti -1c
.RI "async void \fBReBatteriesPoints\fP ()"
.br
.ti -1c
.RI "async void \fBFridgePoints\fP ()"
.br
.ti -1c
.RI "async void \fBSealDraftsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBSealDuctsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBSolarPanelPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file EnergyPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.DryerFullPoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 198 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.EfficientThermostatPoints ()"
This function updates the points in the Energy category by eight points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 352 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.FridgePoints ()"
This function updates the points in the Energy category by eight points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1582 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.HangDryPoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 44 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.InsulateWaterPoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 506 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.IsolateHomePoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 660 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.LedLightsPoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 814 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.MachineFullPoints ()"
This function updates the points in the Energy category by eight points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 968 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.MicrowavePoints ()"

.PP
Definition at line 1120 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.ReBatteriesPoints ()"
This function updates the points in the Energy category by six points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1428 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.SealDraftsPoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1736 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.SealDuctsPoints ()"
This function updates the points in the Energy category by eight points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1890 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.SocketPoints ()"
This function updates the points in the Energy category by four points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1274 of file EnergyPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.EnergyPointsUpdate\&.SolarPanelPoints ()"
This function updates the points in the Energy category by ten points\&. It also increments the number of logs logged in the Energy category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 2044 of file EnergyPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
