.TH "Application_Green_Quake.Views.EcoActions.Habits" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.Habits
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrushingTeeth\fP"
.br
.ti -1c
.RI "class \fBDishwasherFull\fP"
.br
.ti -1c
.RI "class \fBShowerInstead\fP"
.br
.ti -1c
.RI "class \fBTimedShower\fP"
.br
.ti -1c
.RI "class \fBTurnOffLights\fP"
.br
.ti -1c
.RI "class \fBUseMatches\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
