.TH "Application_Green_Quake.Droid.Resource.Xml" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Xml
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBfile_paths\fP = 2131820544"
.br
.ti -1c
.RI "const int \fBimage_share_filepaths\fP = 2131820545"
.br
.ti -1c
.RI "const int \fBstandalone_badge\fP = 2131820546"
.br
.ti -1c
.RI "const int \fBstandalone_badge_gravity_bottom_end\fP = 2131820547"
.br
.ti -1c
.RI "const int \fBstandalone_badge_gravity_bottom_start\fP = 2131820548"
.br
.ti -1c
.RI "const int \fBstandalone_badge_gravity_top_start\fP = 2131820549"
.br
.ti -1c
.RI "const int \fBstandalone_badge_offset\fP = 2131820550"
.br
.ti -1c
.RI "const int \fBxamarin_essentials_fileprovider_file_paths\fP = 2131820551"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32047 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.file_paths = 2131820544\fC [static]\fP"

.PP
Definition at line 32051 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.image_share_filepaths = 2131820545\fC [static]\fP"

.PP
Definition at line 32054 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.standalone_badge = 2131820546\fC [static]\fP"

.PP
Definition at line 32057 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.standalone_badge_gravity_bottom_end = 2131820547\fC [static]\fP"

.PP
Definition at line 32060 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.standalone_badge_gravity_bottom_start = 2131820548\fC [static]\fP"

.PP
Definition at line 32063 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.standalone_badge_gravity_top_start = 2131820549\fC [static]\fP"

.PP
Definition at line 32066 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.standalone_badge_offset = 2131820550\fC [static]\fP"

.PP
Definition at line 32069 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Xml\&.xamarin_essentials_fileprovider_file_paths = 2131820551\fC [static]\fP"

.PP
Definition at line 32072 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
