.TH "Application_Green_Quake.Droid.MainActivity" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.MainActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.Platform\&.Android\&.FormsAppCompatActivity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnBackPressed\fP ()"
.br
.ti -1c
.RI "override void \fBOnRequestPermissionsResult\fP (int requestCode, string[] permissions, [GeneratedEnum] Android\&.Content\&.PM\&.Permission[] grantResults)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file MainActivity\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Application_Green_Quake\&.Droid\&.MainActivity\&.OnBackPressed ()"
This function makes it that when outside of a pop up is touched the popup closes\&. 
.PP
Definition at line 24 of file MainActivity\&.cs\&.
.SS "override void Application_Green_Quake\&.Droid\&.MainActivity\&.OnCreate (Bundle savedInstanceState)\fC [protected]\fP"

.PP
Definition at line 28 of file MainActivity\&.cs\&.
.SS "override void Application_Green_Quake\&.Droid\&.MainActivity\&.OnRequestPermissionsResult (int requestCode, string[] permissions, [GeneratedEnum] Android\&.Content\&.PM\&.Permission[] grantResults)"

.PP
Definition at line 45 of file MainActivity\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
