.TH "Application_Green_Quake.Views.EcoActions.Energy" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.Energy
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDryerFull\fP"
.br
.ti -1c
.RI "class \fBEfficientThermostat\fP"
.br
.ti -1c
.RI "class \fBHangDry\fP"
.br
.ti -1c
.RI "class \fBInsulateWater\fP"
.br
.ti -1c
.RI "class \fBIsolateHome\fP"
.br
.ti -1c
.RI "class \fBLedLightBulb\fP"
.br
.ti -1c
.RI "class \fBMachineFull\fP"
.br
.ti -1c
.RI "class \fBMicrowaveNotOven\fP"
.br
.ti -1c
.RI "class \fBOffSocketSwitch\fP"
.br
.ti -1c
.RI "class \fBReBatteries\fP"
.br
.ti -1c
.RI "class \fBRefrigiratorDown\fP"
.br
.ti -1c
.RI "class \fBSealDrafts\fP"
.br
.ti -1c
.RI "class \fBSealDucts\fP"
.br
.ti -1c
.RI "class \fBSolarPanel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
