.TH "Application_Green_Quake.Views.MainPage" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.MainPage
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.ContentPage, global\&.XamarinForms\&.ContentPage, and ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainPage\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBtoken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file MainPage\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.MainPage\&.MainPage ()"

.PP
Definition at line 21 of file MainPage\&.xaml\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Application_Green_Quake\&.Views\&.MainPage\&.token\fC [static]\fP"

.PP
Definition at line 20 of file MainPage\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
