.TH "Application_Green_Quake.Droid.Resource" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimation\fP"
.br
.ti -1c
.RI "class \fBAnimator\fP"
.br
.ti -1c
.RI "class \fBAttribute\fP"
.br
.ti -1c
.RI "class \fBBoolean\fP"
.br
.ti -1c
.RI "class \fBColor\fP"
.br
.ti -1c
.RI "class \fBDimension\fP"
.br
.ti -1c
.RI "class \fBDrawable\fP"
.br
.ti -1c
.RI "class \fBId\fP"
.br
.ti -1c
.RI "class \fBInteger\fP"
.br
.ti -1c
.RI "class \fBInterpolator\fP"
.br
.ti -1c
.RI "class \fBLayout\fP"
.br
.ti -1c
.RI "class \fBMipmap\fP"
.br
.ti -1c
.RI "class \fBPlurals\fP"
.br
.ti -1c
.RI "class \fBString\fP"
.br
.ti -1c
.RI "class \fBStyle\fP"
.br
.ti -1c
.RI "class \fBStyleable\fP"
.br
.ti -1c
.RI "class \fBXml\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBUpdateIdValues\fP ()"
.br
.ti -1c
.RI "static void \fBUpdateIdValues\fP ()"
.br
.ti -1c
.RI "static void \fBUpdateIdValues\fP ()"
.br
.ti -1c
.RI "static void \fBUpdateIdValues\fP ()"
.br
.ti -1c
.RI "static void \fBUpdateIdValues\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Resource\&.designer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Application_Green_Quake\&.Droid\&.Resource\&.UpdateIdValues ()\fC [static]\fP"

.PP
Definition at line 26 of file Resource\&.designer\&.cs\&.
.SS "static void Application_Green_Quake\&.Droid\&.Resource\&.UpdateIdValues ()\fC [static]\fP"

.PP
Definition at line 26 of file Resource\&.designer\&.cs\&.
.SS "static void Application_Green_Quake\&.Droid\&.Resource\&.UpdateIdValues ()\fC [static]\fP"

.PP
Definition at line 26 of file Resource\&.designer\&.cs\&.
.SS "static void Application_Green_Quake\&.Droid\&.Resource\&.UpdateIdValues ()\fC [static]\fP"

.PP
Definition at line 26 of file Resource\&.designer\&.cs\&.
.SS "static void Application_Green_Quake\&.Droid\&.Resource\&.UpdateIdValues ()\fC [static]\fP"

.PP
Definition at line 26 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
