.TH "Application_Green_Quake.ViewModels" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdvancedPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBCommunityPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBEnergyPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBFoodAndDrinkPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBGetAchievementsData\fP"
.br
.ti -1c
.RI "class \fBGetBadgeData\fP"
.br
.ti -1c
.RI "class \fBGetData\fP"
.br
.ti -1c
.RI "class \fBHabitsPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBHomePointsUpdate\fP"
.br
.ti -1c
.RI "class \fBOutdoorsPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBSecurityMethods\fP"
.br
.ti -1c
.RI "class \fBShoppingPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBTravelPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBWastePointsUpdate\fP"
.br
.ti -1c
.RI "class \fBWaterPointsUpdate\fP"
.br
.ti -1c
.RI "class \fBWorkPointsUpdate\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
