.TH "Application_Green_Quake.Models.CommunityPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.CommunityPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcreateGroupCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcommunityCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBdonateCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBgroupCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBshareCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBawarenessCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file CommunityPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.awarenessCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.communityCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.createGroupCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.donateCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.groupCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file CommunityPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.CommunityPoints\&.shareCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file CommunityPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.CommunityPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file CommunityPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
