.TH "Application_Green_Quake.ViewModels.FoodAndDrinkPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.FoodAndDrinkPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBOrganicPoints\fP ()"
.br
.ti -1c
.RI "async void \fBEatAllPoints\fP ()"
.br
.ti -1c
.RI "async void \fBFoodDelivredPoints\fP ()"
.br
.ti -1c
.RI "async void \fBNoMeatPoints\fP ()"
.br
.ti -1c
.RI "async void \fBOwnCoffeePoints\fP ()"
.br
.ti -1c
.RI "async void \fBReCoffeeMugPoints\fP ()"
.br
.ti -1c
.RI "async void \fBSaveLeftOversPoints\fP ()"
.br
.ti -1c
.RI "async void \fBSteelStrawPoints\fP ()"
.br
.ti -1c
.RI "async void \fBWaterOverFizzyPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.EatAllPoints ()"
This function updates the points in the FoodAndDrink category by four points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 162 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.FoodDelivredPoints ()"
This function updates the points in the FoodAndDrink category by six points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 286 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.NoMeatPoints ()"
This function updates the points in the FoodAndDrink category by ten points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 410 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.OrganicPoints ()"
This function updates the points in the FoodAndDrink category by eight points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 38 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.OwnCoffeePoints ()"
This function updates the points in the FoodAndDrink category by two points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 534 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.ReCoffeeMugPoints ()"
This function updates the points in the FoodAndDrink category by four points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 658 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.SaveLeftOversPoints ()"
This function updates the points in the FoodAndDrink category by six points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 782 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.SteelStrawPoints ()"
This function updates the points in the FoodAndDrink category by four points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 906 of file FoodAndDrinkPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.FoodAndDrinkPointsUpdate\&.WaterOverFizzyPoints ()"
This function updates the points in the FoodAndDrink category by six points\&. It also increments the number of logs logged in the FoodAndDrink category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 1030 of file FoodAndDrinkPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
