.TH "Application_Green_Quake.Droid.Resource.Drawable" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Drawable
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_ab_share_pack_mtrl_alpha\fP = 2131165190"
.br
.ti -1c
.RI "const int \fBabc_action_bar_item_background_material\fP = 2131165191"
.br
.ti -1c
.RI "const int \fBabc_btn_borderless_material\fP = 2131165192"
.br
.ti -1c
.RI "const int \fBabc_btn_check_material\fP = 2131165193"
.br
.ti -1c
.RI "const int \fBabc_btn_check_material_anim\fP = 2131165194"
.br
.ti -1c
.RI "const int \fBabc_btn_check_to_on_mtrl_000\fP = 2131165195"
.br
.ti -1c
.RI "const int \fBabc_btn_check_to_on_mtrl_015\fP = 2131165196"
.br
.ti -1c
.RI "const int \fBabc_btn_colored_material\fP = 2131165197"
.br
.ti -1c
.RI "const int \fBabc_btn_default_mtrl_shape\fP = 2131165198"
.br
.ti -1c
.RI "const int \fBabc_btn_radio_material\fP = 2131165199"
.br
.ti -1c
.RI "const int \fBabc_btn_radio_material_anim\fP = 2131165200"
.br
.ti -1c
.RI "const int \fBabc_btn_radio_to_on_mtrl_000\fP = 2131165201"
.br
.ti -1c
.RI "const int \fBabc_btn_radio_to_on_mtrl_015\fP = 2131165202"
.br
.ti -1c
.RI "const int \fBabc_btn_switch_to_on_mtrl_00001\fP = 2131165203"
.br
.ti -1c
.RI "const int \fBabc_btn_switch_to_on_mtrl_00012\fP = 2131165204"
.br
.ti -1c
.RI "const int \fBabc_cab_background_internal_bg\fP = 2131165205"
.br
.ti -1c
.RI "const int \fBabc_cab_background_top_material\fP = 2131165206"
.br
.ti -1c
.RI "const int \fBabc_cab_background_top_mtrl_alpha\fP = 2131165207"
.br
.ti -1c
.RI "const int \fBabc_control_background_material\fP = 2131165208"
.br
.ti -1c
.RI "const int \fBabc_dialog_material_background\fP = 2131165209"
.br
.ti -1c
.RI "const int \fBabc_edit_text_material\fP = 2131165210"
.br
.ti -1c
.RI "const int \fBabc_ic_ab_back_material\fP = 2131165211"
.br
.ti -1c
.RI "const int \fBabc_ic_arrow_drop_right_black_24dp\fP = 2131165212"
.br
.ti -1c
.RI "const int \fBabc_ic_clear_material\fP = 2131165213"
.br
.ti -1c
.RI "const int \fBabc_ic_commit_search_api_mtrl_alpha\fP = 2131165214"
.br
.ti -1c
.RI "const int \fBabc_ic_go_search_api_material\fP = 2131165215"
.br
.ti -1c
.RI "const int \fBabc_ic_menu_copy_mtrl_am_alpha\fP = 2131165216"
.br
.ti -1c
.RI "const int \fBabc_ic_menu_cut_mtrl_alpha\fP = 2131165217"
.br
.ti -1c
.RI "const int \fBabc_ic_menu_overflow_material\fP = 2131165218"
.br
.ti -1c
.RI "const int \fBabc_ic_menu_paste_mtrl_am_alpha\fP = 2131165219"
.br
.ti -1c
.RI "const int \fBabc_ic_menu_selectall_mtrl_alpha\fP = 2131165220"
.br
.ti -1c
.RI "const int \fBabc_ic_menu_share_mtrl_alpha\fP = 2131165221"
.br
.ti -1c
.RI "const int \fBabc_ic_search_api_material\fP = 2131165222"
.br
.ti -1c
.RI "const int \fBabc_ic_star_black_16dp\fP = 2131165223"
.br
.ti -1c
.RI "const int \fBabc_ic_star_black_36dp\fP = 2131165224"
.br
.ti -1c
.RI "const int \fBabc_ic_star_black_48dp\fP = 2131165225"
.br
.ti -1c
.RI "const int \fBabc_ic_star_half_black_16dp\fP = 2131165226"
.br
.ti -1c
.RI "const int \fBabc_ic_star_half_black_36dp\fP = 2131165227"
.br
.ti -1c
.RI "const int \fBabc_ic_star_half_black_48dp\fP = 2131165228"
.br
.ti -1c
.RI "const int \fBabc_ic_voice_search_api_material\fP = 2131165229"
.br
.ti -1c
.RI "const int \fBabc_item_background_holo_dark\fP = 2131165230"
.br
.ti -1c
.RI "const int \fBabc_item_background_holo_light\fP = 2131165231"
.br
.ti -1c
.RI "const int \fBabc_list_divider_material\fP = 2131165232"
.br
.ti -1c
.RI "const int \fBabc_list_divider_mtrl_alpha\fP = 2131165233"
.br
.ti -1c
.RI "const int \fBabc_list_focused_holo\fP = 2131165234"
.br
.ti -1c
.RI "const int \fBabc_list_longpressed_holo\fP = 2131165235"
.br
.ti -1c
.RI "const int \fBabc_list_pressed_holo_dark\fP = 2131165236"
.br
.ti -1c
.RI "const int \fBabc_list_pressed_holo_light\fP = 2131165237"
.br
.ti -1c
.RI "const int \fBabc_list_selector_background_transition_holo_dark\fP = 2131165238"
.br
.ti -1c
.RI "const int \fBabc_list_selector_background_transition_holo_light\fP = 2131165239"
.br
.ti -1c
.RI "const int \fBabc_list_selector_disabled_holo_dark\fP = 2131165240"
.br
.ti -1c
.RI "const int \fBabc_list_selector_disabled_holo_light\fP = 2131165241"
.br
.ti -1c
.RI "const int \fBabc_list_selector_holo_dark\fP = 2131165242"
.br
.ti -1c
.RI "const int \fBabc_list_selector_holo_light\fP = 2131165243"
.br
.ti -1c
.RI "const int \fBabc_menu_hardkey_panel_mtrl_mult\fP = 2131165244"
.br
.ti -1c
.RI "const int \fBabc_popup_background_mtrl_mult\fP = 2131165245"
.br
.ti -1c
.RI "const int \fBabc_ratingbar_indicator_material\fP = 2131165246"
.br
.ti -1c
.RI "const int \fBabc_ratingbar_material\fP = 2131165247"
.br
.ti -1c
.RI "const int \fBabc_ratingbar_small_material\fP = 2131165248"
.br
.ti -1c
.RI "const int \fBabc_scrubber_control_off_mtrl_alpha\fP = 2131165249"
.br
.ti -1c
.RI "const int \fBabc_scrubber_control_to_pressed_mtrl_000\fP = 2131165250"
.br
.ti -1c
.RI "const int \fBabc_scrubber_control_to_pressed_mtrl_005\fP = 2131165251"
.br
.ti -1c
.RI "const int \fBabc_scrubber_primary_mtrl_alpha\fP = 2131165252"
.br
.ti -1c
.RI "const int \fBabc_scrubber_track_mtrl_alpha\fP = 2131165253"
.br
.ti -1c
.RI "const int \fBabc_seekbar_thumb_material\fP = 2131165254"
.br
.ti -1c
.RI "const int \fBabc_seekbar_tick_mark_material\fP = 2131165255"
.br
.ti -1c
.RI "const int \fBabc_seekbar_track_material\fP = 2131165256"
.br
.ti -1c
.RI "const int \fBabc_spinner_mtrl_am_alpha\fP = 2131165257"
.br
.ti -1c
.RI "const int \fBabc_spinner_textfield_background_material\fP = 2131165258"
.br
.ti -1c
.RI "const int \fBabc_switch_thumb_material\fP = 2131165259"
.br
.ti -1c
.RI "const int \fBabc_switch_track_mtrl_alpha\fP = 2131165260"
.br
.ti -1c
.RI "const int \fBabc_tab_indicator_material\fP = 2131165261"
.br
.ti -1c
.RI "const int \fBabc_tab_indicator_mtrl_alpha\fP = 2131165262"
.br
.ti -1c
.RI "const int \fBabc_textfield_activated_mtrl_alpha\fP = 2131165270"
.br
.ti -1c
.RI "const int \fBabc_textfield_default_mtrl_alpha\fP = 2131165271"
.br
.ti -1c
.RI "const int \fBabc_textfield_search_activated_mtrl_alpha\fP = 2131165272"
.br
.ti -1c
.RI "const int \fBabc_textfield_search_default_mtrl_alpha\fP = 2131165273"
.br
.ti -1c
.RI "const int \fBabc_textfield_search_material\fP = 2131165274"
.br
.ti -1c
.RI "const int \fBabc_text_cursor_material\fP = 2131165263"
.br
.ti -1c
.RI "const int \fBabc_text_select_handle_left_mtrl_dark\fP = 2131165264"
.br
.ti -1c
.RI "const int \fBabc_text_select_handle_left_mtrl_light\fP = 2131165265"
.br
.ti -1c
.RI "const int \fBabc_text_select_handle_middle_mtrl_dark\fP = 2131165266"
.br
.ti -1c
.RI "const int \fBabc_text_select_handle_middle_mtrl_light\fP = 2131165267"
.br
.ti -1c
.RI "const int \fBabc_text_select_handle_right_mtrl_dark\fP = 2131165268"
.br
.ti -1c
.RI "const int \fBabc_text_select_handle_right_mtrl_light\fP = 2131165269"
.br
.ti -1c
.RI "const int \fBabc_vector_test\fP = 2131165275"
.br
.ti -1c
.RI "const int \fBAppLogo\fP = 2131165276"
.br
.ti -1c
.RI "const int \fBavd_hide_password\fP = 2131165277"
.br
.ti -1c
.RI "const int \fBavd_show_password\fP = 2131165278"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_checked_mtrl\fP = 2131165279"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_checked_to_unchecked_mtrl_animation\fP = 2131165280"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_unchecked_mtrl\fP = 2131165281"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_unchecked_to_checked_mtrl_animation\fP = 2131165282"
.br
.ti -1c
.RI "const int \fBbtn_radio_off_mtrl\fP = 2131165283"
.br
.ti -1c
.RI "const int \fBbtn_radio_off_to_on_mtrl_animation\fP = 2131165284"
.br
.ti -1c
.RI "const int \fBbtn_radio_on_mtrl\fP = 2131165285"
.br
.ti -1c
.RI "const int \fBbtn_radio_on_to_off_mtrl_animation\fP = 2131165286"
.br
.ti -1c
.RI "const int \fBcommon_full_open_on_phone\fP = 2131165287"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_dark\fP = 2131165288"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_dark_focused\fP = 2131165289"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_dark_normal\fP = 2131165290"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_dark_normal_background\fP = 2131165291"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_disabled\fP = 2131165292"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_light\fP = 2131165293"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_light_focused\fP = 2131165294"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_light_normal\fP = 2131165295"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_icon_light_normal_background\fP = 2131165296"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark\fP = 2131165297"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_focused\fP = 2131165298"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_normal\fP = 2131165299"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_normal_background\fP = 2131165300"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_disabled\fP = 2131165301"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light\fP = 2131165302"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_focused\fP = 2131165303"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_normal\fP = 2131165304"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_normal_background\fP = 2131165305"
.br
.ti -1c
.RI "const int \fBdesign_bottom_navigation_item_background\fP = 2131165306"
.br
.ti -1c
.RI "const int \fBdesign_fab_background\fP = 2131165307"
.br
.ti -1c
.RI "const int \fBdesign_ic_visibility\fP = 2131165308"
.br
.ti -1c
.RI "const int \fBdesign_ic_visibility_off\fP = 2131165309"
.br
.ti -1c
.RI "const int \fBdesign_password_eye\fP = 2131165310"
.br
.ti -1c
.RI "const int \fBdesign_snackbar_background\fP = 2131165311"
.br
.ti -1c
.RI "const int \fBgoogleg_disabled_color_18\fP = 2131165312"
.br
.ti -1c
.RI "const int \fBgoogleg_standard_color_18\fP = 2131165313"
.br
.ti -1c
.RI "const int \fBic_clock_black_24dp\fP = 2131165314"
.br
.ti -1c
.RI "const int \fBic_errorstatus\fP = 2131165315"
.br
.ti -1c
.RI "const int \fBic_keyboard_black_24dp\fP = 2131165316"
.br
.ti -1c
.RI "const int \fBic_mtrl_checked_circle\fP = 2131165317"
.br
.ti -1c
.RI "const int \fBic_mtrl_chip_checked_black\fP = 2131165318"
.br
.ti -1c
.RI "const int \fBic_mtrl_chip_checked_circle\fP = 2131165319"
.br
.ti -1c
.RI "const int \fBic_mtrl_chip_close_circle\fP = 2131165320"
.br
.ti -1c
.RI "const int \fBic_successstatus\fP = 2131165321"
.br
.ti -1c
.RI "const int \fBmaterial_cursor_drawable\fP = 2131165322"
.br
.ti -1c
.RI "const int \fBmaterial_ic_calendar_black_24dp\fP = 2131165323"
.br
.ti -1c
.RI "const int \fBmaterial_ic_clear_black_24dp\fP = 2131165324"
.br
.ti -1c
.RI "const int \fBmaterial_ic_edit_black_24dp\fP = 2131165325"
.br
.ti -1c
.RI "const int \fBmaterial_ic_keyboard_arrow_left_black_24dp\fP = 2131165326"
.br
.ti -1c
.RI "const int \fBmaterial_ic_keyboard_arrow_next_black_24dp\fP = 2131165327"
.br
.ti -1c
.RI "const int \fBmaterial_ic_keyboard_arrow_previous_black_24dp\fP = 2131165328"
.br
.ti -1c
.RI "const int \fBmaterial_ic_keyboard_arrow_right_black_24dp\fP = 2131165329"
.br
.ti -1c
.RI "const int \fBmaterial_ic_menu_arrow_down_black_24dp\fP = 2131165330"
.br
.ti -1c
.RI "const int \fBmaterial_ic_menu_arrow_up_black_24dp\fP = 2131165331"
.br
.ti -1c
.RI "const int \fBmtrl_dialog_background\fP = 2131165332"
.br
.ti -1c
.RI "const int \fBmtrl_dropdown_arrow\fP = 2131165333"
.br
.ti -1c
.RI "const int \fBmtrl_ic_arrow_drop_down\fP = 2131165334"
.br
.ti -1c
.RI "const int \fBmtrl_ic_arrow_drop_up\fP = 2131165335"
.br
.ti -1c
.RI "const int \fBmtrl_ic_cancel\fP = 2131165336"
.br
.ti -1c
.RI "const int \fBmtrl_ic_error\fP = 2131165337"
.br
.ti -1c
.RI "const int \fBmtrl_popupmenu_background\fP = 2131165338"
.br
.ti -1c
.RI "const int \fBmtrl_popupmenu_background_dark\fP = 2131165339"
.br
.ti -1c
.RI "const int \fBmtrl_tabs_default_indicator\fP = 2131165340"
.br
.ti -1c
.RI "const int \fBnavigation_empty_icon\fP = 2131165341"
.br
.ti -1c
.RI "const int \fBnotification_action_background\fP = 2131165342"
.br
.ti -1c
.RI "const int \fBnotification_bg\fP = 2131165343"
.br
.ti -1c
.RI "const int \fBnotification_bg_low\fP = 2131165344"
.br
.ti -1c
.RI "const int \fBnotification_bg_low_normal\fP = 2131165345"
.br
.ti -1c
.RI "const int \fBnotification_bg_low_pressed\fP = 2131165346"
.br
.ti -1c
.RI "const int \fBnotification_bg_normal\fP = 2131165347"
.br
.ti -1c
.RI "const int \fBnotification_bg_normal_pressed\fP = 2131165348"
.br
.ti -1c
.RI "const int \fBnotification_icon_background\fP = 2131165349"
.br
.ti -1c
.RI "const int \fBnotification_template_icon_bg\fP = 2131165350"
.br
.ti -1c
.RI "const int \fBnotification_template_icon_low_bg\fP = 2131165351"
.br
.ti -1c
.RI "const int \fBnotification_tile_bg\fP = 2131165352"
.br
.ti -1c
.RI "const int \fBnotify_panel_notification_icon_bg\fP = 2131165353"
.br
.ti -1c
.RI "const int \fBroundedbg\fP = 2131165354"
.br
.ti -1c
.RI "const int \fBroundedbgdark\fP = 2131165355"
.br
.ti -1c
.RI "const int \fBtest_custom_background\fP = 2131165356"
.br
.ti -1c
.RI "const int \fBtooltip_frame_dark\fP = 2131165357"
.br
.ti -1c
.RI "const int \fBtooltip_frame_light\fP = 2131165358"
.br
.ti -1c
.RI "const int \fBAvatar1\fP = 2131165277"
.br
.ti -1c
.RI "const int \fBAvatar10\fP = 2131165278"
.br
.ti -1c
.RI "const int \fBAvatar11\fP = 2131165279"
.br
.ti -1c
.RI "const int \fBAvatar12\fP = 2131165280"
.br
.ti -1c
.RI "const int \fBAvatar13\fP = 2131165281"
.br
.ti -1c
.RI "const int \fBAvatar14\fP = 2131165282"
.br
.ti -1c
.RI "const int \fBAvatar15\fP = 2131165283"
.br
.ti -1c
.RI "const int \fBAvatar16\fP = 2131165284"
.br
.ti -1c
.RI "const int \fBAvatar17\fP = 2131165285"
.br
.ti -1c
.RI "const int \fBAvatar18\fP = 2131165286"
.br
.ti -1c
.RI "const int \fBAvatar19\fP = 2131165287"
.br
.ti -1c
.RI "const int \fBAvatar2\fP = 2131165288"
.br
.ti -1c
.RI "const int \fBAvatar20\fP = 2131165289"
.br
.ti -1c
.RI "const int \fBAvatar21\fP = 2131165290"
.br
.ti -1c
.RI "const int \fBAvatar22\fP = 2131165291"
.br
.ti -1c
.RI "const int \fBAvatar23\fP = 2131165292"
.br
.ti -1c
.RI "const int \fBAvatar24\fP = 2131165293"
.br
.ti -1c
.RI "const int \fBAvatar25\fP = 2131165294"
.br
.ti -1c
.RI "const int \fBAvatar26\fP = 2131165295"
.br
.ti -1c
.RI "const int \fBAvatar27\fP = 2131165296"
.br
.ti -1c
.RI "const int \fBAvatar28\fP = 2131165297"
.br
.ti -1c
.RI "const int \fBAvatar29\fP = 2131165298"
.br
.ti -1c
.RI "const int \fBAvatar3\fP = 2131165299"
.br
.ti -1c
.RI "const int \fBAvatar30\fP = 2131165300"
.br
.ti -1c
.RI "const int \fBAvatar4\fP = 2131165301"
.br
.ti -1c
.RI "const int \fBAvatar5\fP = 2131165302"
.br
.ti -1c
.RI "const int \fBAvatar6\fP = 2131165303"
.br
.ti -1c
.RI "const int \fBAvatar7\fP = 2131165304"
.br
.ti -1c
.RI "const int \fBAvatar8\fP = 2131165305"
.br
.ti -1c
.RI "const int \fBAvatar9\fP = 2131165306"
.br
.ti -1c
.RI "const int \fBclear_button_icon\fP = 2131165317"
.br
.ti -1c
.RI "const int \fBinputlayout_togglecollapseicon\fP = 2131165354"
.br
.ti -1c
.RI "const int \fBinputlayout_togglevisibleicon\fP = 2131165355"
.br
.ti -1c
.RI "const int \fBinput_layout_drop_down_icon\fP = 2131165353"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20508 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ab_share_pack_mtrl_alpha = 2131165190\fC [static]\fP"

.PP
Definition at line 20512 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_action_bar_item_background_material = 2131165191\fC [static]\fP"

.PP
Definition at line 20515 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_borderless_material = 2131165192\fC [static]\fP"

.PP
Definition at line 20518 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_check_material = 2131165193\fC [static]\fP"

.PP
Definition at line 20521 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_check_material_anim = 2131165194\fC [static]\fP"

.PP
Definition at line 20524 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_check_to_on_mtrl_000 = 2131165195\fC [static]\fP"

.PP
Definition at line 20527 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_check_to_on_mtrl_015 = 2131165196\fC [static]\fP"

.PP
Definition at line 20530 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_colored_material = 2131165197\fC [static]\fP"

.PP
Definition at line 20533 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_default_mtrl_shape = 2131165198\fC [static]\fP"

.PP
Definition at line 20536 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_radio_material = 2131165199\fC [static]\fP"

.PP
Definition at line 20539 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_radio_material_anim = 2131165200\fC [static]\fP"

.PP
Definition at line 20542 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_radio_to_on_mtrl_000 = 2131165201\fC [static]\fP"

.PP
Definition at line 20545 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_radio_to_on_mtrl_015 = 2131165202\fC [static]\fP"

.PP
Definition at line 20548 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_switch_to_on_mtrl_00001 = 2131165203\fC [static]\fP"

.PP
Definition at line 20551 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_btn_switch_to_on_mtrl_00012 = 2131165204\fC [static]\fP"

.PP
Definition at line 20554 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_cab_background_internal_bg = 2131165205\fC [static]\fP"

.PP
Definition at line 20557 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_cab_background_top_material = 2131165206\fC [static]\fP"

.PP
Definition at line 20560 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_cab_background_top_mtrl_alpha = 2131165207\fC [static]\fP"

.PP
Definition at line 20563 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_control_background_material = 2131165208\fC [static]\fP"

.PP
Definition at line 20566 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_dialog_material_background = 2131165209\fC [static]\fP"

.PP
Definition at line 20569 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_edit_text_material = 2131165210\fC [static]\fP"

.PP
Definition at line 20572 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_ab_back_material = 2131165211\fC [static]\fP"

.PP
Definition at line 20575 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_arrow_drop_right_black_24dp = 2131165212\fC [static]\fP"

.PP
Definition at line 20578 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_clear_material = 2131165213\fC [static]\fP"

.PP
Definition at line 20581 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_commit_search_api_mtrl_alpha = 2131165214\fC [static]\fP"

.PP
Definition at line 20584 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_go_search_api_material = 2131165215\fC [static]\fP"

.PP
Definition at line 20587 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_menu_copy_mtrl_am_alpha = 2131165216\fC [static]\fP"

.PP
Definition at line 20590 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_menu_cut_mtrl_alpha = 2131165217\fC [static]\fP"

.PP
Definition at line 20593 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_menu_overflow_material = 2131165218\fC [static]\fP"

.PP
Definition at line 20596 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_menu_paste_mtrl_am_alpha = 2131165219\fC [static]\fP"

.PP
Definition at line 20599 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_menu_selectall_mtrl_alpha = 2131165220\fC [static]\fP"

.PP
Definition at line 20602 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_menu_share_mtrl_alpha = 2131165221\fC [static]\fP"

.PP
Definition at line 20605 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_search_api_material = 2131165222\fC [static]\fP"

.PP
Definition at line 20608 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_star_black_16dp = 2131165223\fC [static]\fP"

.PP
Definition at line 20611 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_star_black_36dp = 2131165224\fC [static]\fP"

.PP
Definition at line 20614 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_star_black_48dp = 2131165225\fC [static]\fP"

.PP
Definition at line 20617 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_star_half_black_16dp = 2131165226\fC [static]\fP"

.PP
Definition at line 20620 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_star_half_black_36dp = 2131165227\fC [static]\fP"

.PP
Definition at line 20623 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_star_half_black_48dp = 2131165228\fC [static]\fP"

.PP
Definition at line 20626 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ic_voice_search_api_material = 2131165229\fC [static]\fP"

.PP
Definition at line 20629 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_item_background_holo_dark = 2131165230\fC [static]\fP"

.PP
Definition at line 20632 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_item_background_holo_light = 2131165231\fC [static]\fP"

.PP
Definition at line 20635 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_divider_material = 2131165232\fC [static]\fP"

.PP
Definition at line 20638 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_divider_mtrl_alpha = 2131165233\fC [static]\fP"

.PP
Definition at line 20641 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_focused_holo = 2131165234\fC [static]\fP"

.PP
Definition at line 20644 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_longpressed_holo = 2131165235\fC [static]\fP"

.PP
Definition at line 20647 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_pressed_holo_dark = 2131165236\fC [static]\fP"

.PP
Definition at line 20650 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_pressed_holo_light = 2131165237\fC [static]\fP"

.PP
Definition at line 20653 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_selector_background_transition_holo_dark = 2131165238\fC [static]\fP"

.PP
Definition at line 20656 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_selector_background_transition_holo_light = 2131165239\fC [static]\fP"

.PP
Definition at line 20659 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_selector_disabled_holo_dark = 2131165240\fC [static]\fP"

.PP
Definition at line 20662 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_selector_disabled_holo_light = 2131165241\fC [static]\fP"

.PP
Definition at line 20665 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_selector_holo_dark = 2131165242\fC [static]\fP"

.PP
Definition at line 20668 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_list_selector_holo_light = 2131165243\fC [static]\fP"

.PP
Definition at line 20671 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_menu_hardkey_panel_mtrl_mult = 2131165244\fC [static]\fP"

.PP
Definition at line 20674 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_popup_background_mtrl_mult = 2131165245\fC [static]\fP"

.PP
Definition at line 20677 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ratingbar_indicator_material = 2131165246\fC [static]\fP"

.PP
Definition at line 20680 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ratingbar_material = 2131165247\fC [static]\fP"

.PP
Definition at line 20683 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_ratingbar_small_material = 2131165248\fC [static]\fP"

.PP
Definition at line 20686 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_scrubber_control_off_mtrl_alpha = 2131165249\fC [static]\fP"

.PP
Definition at line 20689 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_scrubber_control_to_pressed_mtrl_000 = 2131165250\fC [static]\fP"

.PP
Definition at line 20692 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_scrubber_control_to_pressed_mtrl_005 = 2131165251\fC [static]\fP"

.PP
Definition at line 20695 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_scrubber_primary_mtrl_alpha = 2131165252\fC [static]\fP"

.PP
Definition at line 20698 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_scrubber_track_mtrl_alpha = 2131165253\fC [static]\fP"

.PP
Definition at line 20701 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_seekbar_thumb_material = 2131165254\fC [static]\fP"

.PP
Definition at line 20704 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_seekbar_tick_mark_material = 2131165255\fC [static]\fP"

.PP
Definition at line 20707 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_seekbar_track_material = 2131165256\fC [static]\fP"

.PP
Definition at line 20710 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_spinner_mtrl_am_alpha = 2131165257\fC [static]\fP"

.PP
Definition at line 20713 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_spinner_textfield_background_material = 2131165258\fC [static]\fP"

.PP
Definition at line 20716 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_switch_thumb_material = 2131165259\fC [static]\fP"

.PP
Definition at line 20719 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_switch_track_mtrl_alpha = 2131165260\fC [static]\fP"

.PP
Definition at line 20722 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_tab_indicator_material = 2131165261\fC [static]\fP"

.PP
Definition at line 20725 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_tab_indicator_mtrl_alpha = 2131165262\fC [static]\fP"

.PP
Definition at line 20728 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_cursor_material = 2131165263\fC [static]\fP"

.PP
Definition at line 20746 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_select_handle_left_mtrl_dark = 2131165264\fC [static]\fP"

.PP
Definition at line 20749 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_select_handle_left_mtrl_light = 2131165265\fC [static]\fP"

.PP
Definition at line 20752 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_select_handle_middle_mtrl_dark = 2131165266\fC [static]\fP"

.PP
Definition at line 20755 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_select_handle_middle_mtrl_light = 2131165267\fC [static]\fP"

.PP
Definition at line 20758 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_select_handle_right_mtrl_dark = 2131165268\fC [static]\fP"

.PP
Definition at line 20761 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_text_select_handle_right_mtrl_light = 2131165269\fC [static]\fP"

.PP
Definition at line 20764 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_textfield_activated_mtrl_alpha = 2131165270\fC [static]\fP"

.PP
Definition at line 20731 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_textfield_default_mtrl_alpha = 2131165271\fC [static]\fP"

.PP
Definition at line 20734 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_textfield_search_activated_mtrl_alpha = 2131165272\fC [static]\fP"

.PP
Definition at line 20737 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_textfield_search_default_mtrl_alpha = 2131165273\fC [static]\fP"

.PP
Definition at line 20740 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_textfield_search_material = 2131165274\fC [static]\fP"

.PP
Definition at line 20743 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.abc_vector_test = 2131165275\fC [static]\fP"

.PP
Definition at line 20767 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.AppLogo = 2131165276\fC [static]\fP"

.PP
Definition at line 20770 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar1 = 2131165277\fC [static]\fP"

.PP
Definition at line 20940 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar10 = 2131165278\fC [static]\fP"

.PP
Definition at line 20943 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar11 = 2131165279\fC [static]\fP"

.PP
Definition at line 20946 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar12 = 2131165280\fC [static]\fP"

.PP
Definition at line 20949 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar13 = 2131165281\fC [static]\fP"

.PP
Definition at line 20952 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar14 = 2131165282\fC [static]\fP"

.PP
Definition at line 20955 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar15 = 2131165283\fC [static]\fP"

.PP
Definition at line 20958 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar16 = 2131165284\fC [static]\fP"

.PP
Definition at line 20961 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar17 = 2131165285\fC [static]\fP"

.PP
Definition at line 20964 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar18 = 2131165286\fC [static]\fP"

.PP
Definition at line 20967 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar19 = 2131165287\fC [static]\fP"

.PP
Definition at line 20970 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar2 = 2131165288\fC [static]\fP"

.PP
Definition at line 20973 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar20 = 2131165289\fC [static]\fP"

.PP
Definition at line 20976 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar21 = 2131165290\fC [static]\fP"

.PP
Definition at line 20979 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar22 = 2131165291\fC [static]\fP"

.PP
Definition at line 20982 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar23 = 2131165292\fC [static]\fP"

.PP
Definition at line 20985 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar24 = 2131165293\fC [static]\fP"

.PP
Definition at line 20988 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar25 = 2131165294\fC [static]\fP"

.PP
Definition at line 20991 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar26 = 2131165295\fC [static]\fP"

.PP
Definition at line 20994 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar27 = 2131165296\fC [static]\fP"

.PP
Definition at line 20997 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar28 = 2131165297\fC [static]\fP"

.PP
Definition at line 21000 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar29 = 2131165298\fC [static]\fP"

.PP
Definition at line 21003 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar3 = 2131165299\fC [static]\fP"

.PP
Definition at line 21006 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar30 = 2131165300\fC [static]\fP"

.PP
Definition at line 21009 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar4 = 2131165301\fC [static]\fP"

.PP
Definition at line 21012 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar5 = 2131165302\fC [static]\fP"

.PP
Definition at line 21015 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar6 = 2131165303\fC [static]\fP"

.PP
Definition at line 21018 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar7 = 2131165304\fC [static]\fP"

.PP
Definition at line 21021 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar8 = 2131165305\fC [static]\fP"

.PP
Definition at line 21024 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.Avatar9 = 2131165306\fC [static]\fP"

.PP
Definition at line 21027 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.avd_hide_password = 2131165277\fC [static]\fP"

.PP
Definition at line 20773 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.avd_show_password = 2131165278\fC [static]\fP"

.PP
Definition at line 20776 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_checkbox_checked_mtrl = 2131165279\fC [static]\fP"

.PP
Definition at line 20779 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_checkbox_checked_to_unchecked_mtrl_animation = 2131165280\fC [static]\fP"

.PP
Definition at line 20782 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_checkbox_unchecked_mtrl = 2131165281\fC [static]\fP"

.PP
Definition at line 20785 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_checkbox_unchecked_to_checked_mtrl_animation = 2131165282\fC [static]\fP"

.PP
Definition at line 20788 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_radio_off_mtrl = 2131165283\fC [static]\fP"

.PP
Definition at line 20791 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_radio_off_to_on_mtrl_animation = 2131165284\fC [static]\fP"

.PP
Definition at line 20794 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_radio_on_mtrl = 2131165285\fC [static]\fP"

.PP
Definition at line 20797 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.btn_radio_on_to_off_mtrl_animation = 2131165286\fC [static]\fP"

.PP
Definition at line 20800 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.clear_button_icon = 2131165317\fC [static]\fP"

.PP
Definition at line 21060 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_full_open_on_phone = 2131165287\fC [static]\fP"

.PP
Definition at line 20803 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_dark = 2131165288\fC [static]\fP"

.PP
Definition at line 20806 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_dark_focused = 2131165289\fC [static]\fP"

.PP
Definition at line 20809 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_dark_normal = 2131165290\fC [static]\fP"

.PP
Definition at line 20812 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_dark_normal_background = 2131165291\fC [static]\fP"

.PP
Definition at line 20815 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_disabled = 2131165292\fC [static]\fP"

.PP
Definition at line 20818 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_light = 2131165293\fC [static]\fP"

.PP
Definition at line 20821 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_light_focused = 2131165294\fC [static]\fP"

.PP
Definition at line 20824 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_light_normal = 2131165295\fC [static]\fP"

.PP
Definition at line 20827 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_icon_light_normal_background = 2131165296\fC [static]\fP"

.PP
Definition at line 20830 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_dark = 2131165297\fC [static]\fP"

.PP
Definition at line 20833 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_dark_focused = 2131165298\fC [static]\fP"

.PP
Definition at line 20836 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_dark_normal = 2131165299\fC [static]\fP"

.PP
Definition at line 20839 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_dark_normal_background = 2131165300\fC [static]\fP"

.PP
Definition at line 20842 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_disabled = 2131165301\fC [static]\fP"

.PP
Definition at line 20845 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_light = 2131165302\fC [static]\fP"

.PP
Definition at line 20848 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_light_focused = 2131165303\fC [static]\fP"

.PP
Definition at line 20851 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_light_normal = 2131165304\fC [static]\fP"

.PP
Definition at line 20854 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.common_google_signin_btn_text_light_normal_background = 2131165305\fC [static]\fP"

.PP
Definition at line 20857 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.design_bottom_navigation_item_background = 2131165306\fC [static]\fP"

.PP
Definition at line 20860 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.design_fab_background = 2131165307\fC [static]\fP"

.PP
Definition at line 20863 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.design_ic_visibility = 2131165308\fC [static]\fP"

.PP
Definition at line 20866 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.design_ic_visibility_off = 2131165309\fC [static]\fP"

.PP
Definition at line 20869 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.design_password_eye = 2131165310\fC [static]\fP"

.PP
Definition at line 20872 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.design_snackbar_background = 2131165311\fC [static]\fP"

.PP
Definition at line 20875 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.googleg_disabled_color_18 = 2131165312\fC [static]\fP"

.PP
Definition at line 20878 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.googleg_standard_color_18 = 2131165313\fC [static]\fP"

.PP
Definition at line 20881 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_clock_black_24dp = 2131165314\fC [static]\fP"

.PP
Definition at line 20884 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_errorstatus = 2131165315\fC [static]\fP"

.PP
Definition at line 20887 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_keyboard_black_24dp = 2131165316\fC [static]\fP"

.PP
Definition at line 20890 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_mtrl_checked_circle = 2131165317\fC [static]\fP"

.PP
Definition at line 20893 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_mtrl_chip_checked_black = 2131165318\fC [static]\fP"

.PP
Definition at line 20896 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_mtrl_chip_checked_circle = 2131165319\fC [static]\fP"

.PP
Definition at line 20899 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_mtrl_chip_close_circle = 2131165320\fC [static]\fP"

.PP
Definition at line 20902 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.ic_successstatus = 2131165321\fC [static]\fP"

.PP
Definition at line 20905 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.input_layout_drop_down_icon = 2131165353\fC [static]\fP"

.PP
Definition at line 21174 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.inputlayout_togglecollapseicon = 2131165354\fC [static]\fP"

.PP
Definition at line 21168 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.inputlayout_togglevisibleicon = 2131165355\fC [static]\fP"

.PP
Definition at line 21171 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_cursor_drawable = 2131165322\fC [static]\fP"

.PP
Definition at line 20908 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_calendar_black_24dp = 2131165323\fC [static]\fP"

.PP
Definition at line 20911 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_clear_black_24dp = 2131165324\fC [static]\fP"

.PP
Definition at line 20914 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_edit_black_24dp = 2131165325\fC [static]\fP"

.PP
Definition at line 20917 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_keyboard_arrow_left_black_24dp = 2131165326\fC [static]\fP"

.PP
Definition at line 20920 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_keyboard_arrow_next_black_24dp = 2131165327\fC [static]\fP"

.PP
Definition at line 20923 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_keyboard_arrow_previous_black_24dp = 2131165328\fC [static]\fP"

.PP
Definition at line 20926 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_keyboard_arrow_right_black_24dp = 2131165329\fC [static]\fP"

.PP
Definition at line 20929 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_menu_arrow_down_black_24dp = 2131165330\fC [static]\fP"

.PP
Definition at line 20932 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.material_ic_menu_arrow_up_black_24dp = 2131165331\fC [static]\fP"

.PP
Definition at line 20935 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_dialog_background = 2131165332\fC [static]\fP"

.PP
Definition at line 20938 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_dropdown_arrow = 2131165333\fC [static]\fP"

.PP
Definition at line 20941 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_ic_arrow_drop_down = 2131165334\fC [static]\fP"

.PP
Definition at line 20944 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_ic_arrow_drop_up = 2131165335\fC [static]\fP"

.PP
Definition at line 20947 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_ic_cancel = 2131165336\fC [static]\fP"

.PP
Definition at line 20950 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_ic_error = 2131165337\fC [static]\fP"

.PP
Definition at line 20953 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_popupmenu_background = 2131165338\fC [static]\fP"

.PP
Definition at line 20956 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_popupmenu_background_dark = 2131165339\fC [static]\fP"

.PP
Definition at line 20959 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.mtrl_tabs_default_indicator = 2131165340\fC [static]\fP"

.PP
Definition at line 20962 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.navigation_empty_icon = 2131165341\fC [static]\fP"

.PP
Definition at line 20965 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_action_background = 2131165342\fC [static]\fP"

.PP
Definition at line 20968 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_bg = 2131165343\fC [static]\fP"

.PP
Definition at line 20971 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_bg_low = 2131165344\fC [static]\fP"

.PP
Definition at line 20974 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_bg_low_normal = 2131165345\fC [static]\fP"

.PP
Definition at line 20977 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_bg_low_pressed = 2131165346\fC [static]\fP"

.PP
Definition at line 20980 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_bg_normal = 2131165347\fC [static]\fP"

.PP
Definition at line 20983 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_bg_normal_pressed = 2131165348\fC [static]\fP"

.PP
Definition at line 20986 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_icon_background = 2131165349\fC [static]\fP"

.PP
Definition at line 20989 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_template_icon_bg = 2131165350\fC [static]\fP"

.PP
Definition at line 20992 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_template_icon_low_bg = 2131165351\fC [static]\fP"

.PP
Definition at line 20995 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notification_tile_bg = 2131165352\fC [static]\fP"

.PP
Definition at line 20998 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.notify_panel_notification_icon_bg = 2131165353\fC [static]\fP"

.PP
Definition at line 21001 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.roundedbg = 2131165354\fC [static]\fP"

.PP
Definition at line 21004 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.roundedbgdark = 2131165355\fC [static]\fP"

.PP
Definition at line 21007 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.test_custom_background = 2131165356\fC [static]\fP"

.PP
Definition at line 21010 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.tooltip_frame_dark = 2131165357\fC [static]\fP"

.PP
Definition at line 21013 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Drawable\&.tooltip_frame_light = 2131165358\fC [static]\fP"

.PP
Definition at line 21016 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
