.TH "Application_Green_Quake.ViewModels.GetData" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.GetData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBSetData\fP ()"
.br
.ti -1c
.RI "async void \fBSetLvl\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBusername\fP = ''"
.br
.ti -1c
.RI "static string \fBbio\fP = ''"
.br
.ti -1c
.RI "static int \fBpoints\fP = 0"
.br
.ti -1c
.RI "static int \fBlvl\fP = 0"
.br
.ti -1c
.RI "static string \fBnation\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file GetData\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.GetData\&.SetData ()"
This function sets the data to be used for the font end in this application\&. It sets the username, bio, points, nation and lvl for the logged in user\&. These are saved in global public variables that are used across the application for front end\&. 
.PP
Definition at line 29 of file GetData\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.GetData\&.SetLvl ()"
This function just sets the level of the user in a global static variable shared across all the classes to be displayed for the front end\&. 
.PP
Definition at line 66 of file GetData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Application_Green_Quake\&.ViewModels\&.GetData\&.bio = ''\fC [static]\fP"

.PP
Definition at line 20 of file GetData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetData\&.lvl = 0\fC [static]\fP"

.PP
Definition at line 22 of file GetData\&.cs\&.
.SS "string Application_Green_Quake\&.ViewModels\&.GetData\&.nation = ''\fC [static]\fP"

.PP
Definition at line 23 of file GetData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetData\&.points = 0\fC [static]\fP"

.PP
Definition at line 21 of file GetData\&.cs\&.
.SS "string Application_Green_Quake\&.ViewModels\&.GetData\&.username = ''\fC [static]\fP"

.PP
Definition at line 19 of file GetData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
