.TH "Application_Green_Quake.Droid.Resource.Color" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Color
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_background_cache_hint_selector_material_dark\fP = 2131034112"
.br
.ti -1c
.RI "const int \fBabc_background_cache_hint_selector_material_light\fP = 2131034113"
.br
.ti -1c
.RI "const int \fBabc_btn_colored_borderless_text_material\fP = 2131034114"
.br
.ti -1c
.RI "const int \fBabc_btn_colored_text_material\fP = 2131034115"
.br
.ti -1c
.RI "const int \fBabc_color_highlight_material\fP = 2131034116"
.br
.ti -1c
.RI "const int \fBabc_decor_view_status_guard\fP = 2131034117"
.br
.ti -1c
.RI "const int \fBabc_decor_view_status_guard_light\fP = 2131034118"
.br
.ti -1c
.RI "const int \fBabc_hint_foreground_material_dark\fP = 2131034119"
.br
.ti -1c
.RI "const int \fBabc_hint_foreground_material_light\fP = 2131034120"
.br
.ti -1c
.RI "const int \fBabc_primary_text_disable_only_material_dark\fP = 2131034121"
.br
.ti -1c
.RI "const int \fBabc_primary_text_disable_only_material_light\fP = 2131034122"
.br
.ti -1c
.RI "const int \fBabc_primary_text_material_dark\fP = 2131034123"
.br
.ti -1c
.RI "const int \fBabc_primary_text_material_light\fP = 2131034124"
.br
.ti -1c
.RI "const int \fBabc_search_url_text\fP = 2131034125"
.br
.ti -1c
.RI "const int \fBabc_search_url_text_normal\fP = 2131034126"
.br
.ti -1c
.RI "const int \fBabc_search_url_text_pressed\fP = 2131034127"
.br
.ti -1c
.RI "const int \fBabc_search_url_text_selected\fP = 2131034128"
.br
.ti -1c
.RI "const int \fBabc_secondary_text_material_dark\fP = 2131034129"
.br
.ti -1c
.RI "const int \fBabc_secondary_text_material_light\fP = 2131034130"
.br
.ti -1c
.RI "const int \fBabc_tint_btn_checkable\fP = 2131034131"
.br
.ti -1c
.RI "const int \fBabc_tint_default\fP = 2131034132"
.br
.ti -1c
.RI "const int \fBabc_tint_edittext\fP = 2131034133"
.br
.ti -1c
.RI "const int \fBabc_tint_seek_thumb\fP = 2131034134"
.br
.ti -1c
.RI "const int \fBabc_tint_spinner\fP = 2131034135"
.br
.ti -1c
.RI "const int \fBabc_tint_switch_track\fP = 2131034136"
.br
.ti -1c
.RI "const int \fBaccent_material_dark\fP = 2131034137"
.br
.ti -1c
.RI "const int \fBaccent_material_light\fP = 2131034138"
.br
.ti -1c
.RI "const int \fBandroidx_core_ripple_material_light\fP = 2131034139"
.br
.ti -1c
.RI "const int \fBandroidx_core_secondary_text_default_material_light\fP = 2131034140"
.br
.ti -1c
.RI "const int \fBbackground_floating_material_dark\fP = 2131034141"
.br
.ti -1c
.RI "const int \fBbackground_floating_material_light\fP = 2131034142"
.br
.ti -1c
.RI "const int \fBbackground_material_dark\fP = 2131034143"
.br
.ti -1c
.RI "const int \fBbackground_material_light\fP = 2131034144"
.br
.ti -1c
.RI "const int \fBbright_foreground_disabled_material_dark\fP = 2131034145"
.br
.ti -1c
.RI "const int \fBbright_foreground_disabled_material_light\fP = 2131034146"
.br
.ti -1c
.RI "const int \fBbright_foreground_inverse_material_dark\fP = 2131034147"
.br
.ti -1c
.RI "const int \fBbright_foreground_inverse_material_light\fP = 2131034148"
.br
.ti -1c
.RI "const int \fBbright_foreground_material_dark\fP = 2131034149"
.br
.ti -1c
.RI "const int \fBbright_foreground_material_light\fP = 2131034150"
.br
.ti -1c
.RI "const int \fBbrowser_actions_bg_grey\fP = 2131034151"
.br
.ti -1c
.RI "const int \fBbrowser_actions_divider_color\fP = 2131034152"
.br
.ti -1c
.RI "const int \fBbrowser_actions_text_color\fP = 2131034153"
.br
.ti -1c
.RI "const int \fBbrowser_actions_title_color\fP = 2131034154"
.br
.ti -1c
.RI "const int \fBbutton_material_dark\fP = 2131034155"
.br
.ti -1c
.RI "const int \fBbutton_material_light\fP = 2131034156"
.br
.ti -1c
.RI "const int \fBcardview_dark_background\fP = 2131034157"
.br
.ti -1c
.RI "const int \fBcardview_light_background\fP = 2131034158"
.br
.ti -1c
.RI "const int \fBcardview_shadow_end_color\fP = 2131034159"
.br
.ti -1c
.RI "const int \fBcardview_shadow_start_color\fP = 2131034160"
.br
.ti -1c
.RI "const int \fBcheckbox_themeable_attribute_color\fP = 2131034161"
.br
.ti -1c
.RI "const int \fBcolorAccent\fP = 2131034162"
.br
.ti -1c
.RI "const int \fBcolorPrimary\fP = 2131034163"
.br
.ti -1c
.RI "const int \fBcolorPrimaryDark\fP = 2131034164"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark\fP = 2131034165"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_default\fP = 2131034166"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_disabled\fP = 2131034167"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_focused\fP = 2131034168"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_dark_pressed\fP = 2131034169"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light\fP = 2131034170"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_default\fP = 2131034171"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_disabled\fP = 2131034172"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_focused\fP = 2131034173"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_text_light_pressed\fP = 2131034174"
.br
.ti -1c
.RI "const int \fBcommon_google_signin_btn_tint\fP = 2131034175"
.br
.ti -1c
.RI "const int \fBdesign_bottom_navigation_shadow_color\fP = 2131034176"
.br
.ti -1c
.RI "const int \fBdesign_box_stroke_color\fP = 2131034177"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_background\fP = 2131034178"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_error\fP = 2131034179"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_on_background\fP = 2131034180"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_on_error\fP = 2131034181"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_on_primary\fP = 2131034182"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_on_secondary\fP = 2131034183"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_on_surface\fP = 2131034184"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_primary\fP = 2131034185"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_primary_dark\fP = 2131034186"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_primary_variant\fP = 2131034187"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_secondary\fP = 2131034188"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_secondary_variant\fP = 2131034189"
.br
.ti -1c
.RI "const int \fBdesign_dark_default_color_surface\fP = 2131034190"
.br
.ti -1c
.RI "const int \fBdesign_default_color_background\fP = 2131034191"
.br
.ti -1c
.RI "const int \fBdesign_default_color_error\fP = 2131034192"
.br
.ti -1c
.RI "const int \fBdesign_default_color_on_background\fP = 2131034193"
.br
.ti -1c
.RI "const int \fBdesign_default_color_on_error\fP = 2131034194"
.br
.ti -1c
.RI "const int \fBdesign_default_color_on_primary\fP = 2131034195"
.br
.ti -1c
.RI "const int \fBdesign_default_color_on_secondary\fP = 2131034196"
.br
.ti -1c
.RI "const int \fBdesign_default_color_on_surface\fP = 2131034197"
.br
.ti -1c
.RI "const int \fBdesign_default_color_primary\fP = 2131034198"
.br
.ti -1c
.RI "const int \fBdesign_default_color_primary_dark\fP = 2131034199"
.br
.ti -1c
.RI "const int \fBdesign_default_color_primary_variant\fP = 2131034200"
.br
.ti -1c
.RI "const int \fBdesign_default_color_secondary\fP = 2131034201"
.br
.ti -1c
.RI "const int \fBdesign_default_color_secondary_variant\fP = 2131034202"
.br
.ti -1c
.RI "const int \fBdesign_default_color_surface\fP = 2131034203"
.br
.ti -1c
.RI "const int \fBdesign_error\fP = 2131034204"
.br
.ti -1c
.RI "const int \fBdesign_fab_shadow_end_color\fP = 2131034205"
.br
.ti -1c
.RI "const int \fBdesign_fab_shadow_mid_color\fP = 2131034206"
.br
.ti -1c
.RI "const int \fBdesign_fab_shadow_start_color\fP = 2131034207"
.br
.ti -1c
.RI "const int \fBdesign_fab_stroke_end_inner_color\fP = 2131034208"
.br
.ti -1c
.RI "const int \fBdesign_fab_stroke_end_outer_color\fP = 2131034209"
.br
.ti -1c
.RI "const int \fBdesign_fab_stroke_top_inner_color\fP = 2131034210"
.br
.ti -1c
.RI "const int \fBdesign_fab_stroke_top_outer_color\fP = 2131034211"
.br
.ti -1c
.RI "const int \fBdesign_icon_tint\fP = 2131034212"
.br
.ti -1c
.RI "const int \fBdesign_snackbar_background_color\fP = 2131034213"
.br
.ti -1c
.RI "const int \fBdim_foreground_disabled_material_dark\fP = 2131034214"
.br
.ti -1c
.RI "const int \fBdim_foreground_disabled_material_light\fP = 2131034215"
.br
.ti -1c
.RI "const int \fBdim_foreground_material_dark\fP = 2131034216"
.br
.ti -1c
.RI "const int \fBdim_foreground_material_light\fP = 2131034217"
.br
.ti -1c
.RI "const int \fBerror_color_material_dark\fP = 2131034218"
.br
.ti -1c
.RI "const int \fBerror_color_material_light\fP = 2131034219"
.br
.ti -1c
.RI "const int \fBforeground_material_dark\fP = 2131034220"
.br
.ti -1c
.RI "const int \fBforeground_material_light\fP = 2131034221"
.br
.ti -1c
.RI "const int \fBhighlighted_text_material_dark\fP = 2131034222"
.br
.ti -1c
.RI "const int \fBhighlighted_text_material_light\fP = 2131034223"
.br
.ti -1c
.RI "const int \fBlauncher_background\fP = 2131034224"
.br
.ti -1c
.RI "const int \fBmaterial_blue_grey_800\fP = 2131034225"
.br
.ti -1c
.RI "const int \fBmaterial_blue_grey_900\fP = 2131034226"
.br
.ti -1c
.RI "const int \fBmaterial_blue_grey_950\fP = 2131034227"
.br
.ti -1c
.RI "const int \fBmaterial_cursor_color\fP = 2131034228"
.br
.ti -1c
.RI "const int \fBmaterial_deep_teal_200\fP = 2131034229"
.br
.ti -1c
.RI "const int \fBmaterial_deep_teal_500\fP = 2131034230"
.br
.ti -1c
.RI "const int \fBmaterial_grey_100\fP = 2131034231"
.br
.ti -1c
.RI "const int \fBmaterial_grey_300\fP = 2131034232"
.br
.ti -1c
.RI "const int \fBmaterial_grey_50\fP = 2131034233"
.br
.ti -1c
.RI "const int \fBmaterial_grey_600\fP = 2131034234"
.br
.ti -1c
.RI "const int \fBmaterial_grey_800\fP = 2131034235"
.br
.ti -1c
.RI "const int \fBmaterial_grey_850\fP = 2131034236"
.br
.ti -1c
.RI "const int \fBmaterial_grey_900\fP = 2131034237"
.br
.ti -1c
.RI "const int \fBmaterial_on_background_disabled\fP = 2131034238"
.br
.ti -1c
.RI "const int \fBmaterial_on_background_emphasis_high_type\fP = 2131034239"
.br
.ti -1c
.RI "const int \fBmaterial_on_background_emphasis_medium\fP = 2131034240"
.br
.ti -1c
.RI "const int \fBmaterial_on_primary_disabled\fP = 2131034241"
.br
.ti -1c
.RI "const int \fBmaterial_on_primary_emphasis_high_type\fP = 2131034242"
.br
.ti -1c
.RI "const int \fBmaterial_on_primary_emphasis_medium\fP = 2131034243"
.br
.ti -1c
.RI "const int \fBmaterial_on_surface_disabled\fP = 2131034244"
.br
.ti -1c
.RI "const int \fBmaterial_on_surface_emphasis_high_type\fP = 2131034245"
.br
.ti -1c
.RI "const int \fBmaterial_on_surface_emphasis_medium\fP = 2131034246"
.br
.ti -1c
.RI "const int \fBmaterial_on_surface_stroke\fP = 2131034247"
.br
.ti -1c
.RI "const int \fBmaterial_slider_active_tick_marks_color\fP = 2131034248"
.br
.ti -1c
.RI "const int \fBmaterial_slider_active_track_color\fP = 2131034249"
.br
.ti -1c
.RI "const int \fBmaterial_slider_halo_color\fP = 2131034250"
.br
.ti -1c
.RI "const int \fBmaterial_slider_inactive_tick_marks_color\fP = 2131034251"
.br
.ti -1c
.RI "const int \fBmaterial_slider_inactive_track_color\fP = 2131034252"
.br
.ti -1c
.RI "const int \fBmaterial_slider_thumb_color\fP = 2131034253"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_button_background\fP = 2131034254"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_button_stroke\fP = 2131034255"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_clockface\fP = 2131034257"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_clock_text_color\fP = 2131034256"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_modebutton_tint\fP = 2131034258"
.br
.ti -1c
.RI "const int \fBmtrl_bottom_nav_colored_item_tint\fP = 2131034259"
.br
.ti -1c
.RI "const int \fBmtrl_bottom_nav_colored_ripple_color\fP = 2131034260"
.br
.ti -1c
.RI "const int \fBmtrl_bottom_nav_item_tint\fP = 2131034261"
.br
.ti -1c
.RI "const int \fBmtrl_bottom_nav_ripple_color\fP = 2131034262"
.br
.ti -1c
.RI "const int \fBmtrl_btn_bg_color_selector\fP = 2131034263"
.br
.ti -1c
.RI "const int \fBmtrl_btn_ripple_color\fP = 2131034264"
.br
.ti -1c
.RI "const int \fBmtrl_btn_stroke_color_selector\fP = 2131034265"
.br
.ti -1c
.RI "const int \fBmtrl_btn_text_btn_bg_color_selector\fP = 2131034266"
.br
.ti -1c
.RI "const int \fBmtrl_btn_text_btn_ripple_color\fP = 2131034267"
.br
.ti -1c
.RI "const int \fBmtrl_btn_text_color_disabled\fP = 2131034268"
.br
.ti -1c
.RI "const int \fBmtrl_btn_text_color_selector\fP = 2131034269"
.br
.ti -1c
.RI "const int \fBmtrl_btn_transparent_bg_color\fP = 2131034270"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_item_stroke_color\fP = 2131034271"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_selected_range\fP = 2131034272"
.br
.ti -1c
.RI "const int \fBmtrl_card_view_foreground\fP = 2131034273"
.br
.ti -1c
.RI "const int \fBmtrl_card_view_ripple\fP = 2131034274"
.br
.ti -1c
.RI "const int \fBmtrl_chip_background_color\fP = 2131034275"
.br
.ti -1c
.RI "const int \fBmtrl_chip_close_icon_tint\fP = 2131034276"
.br
.ti -1c
.RI "const int \fBmtrl_chip_surface_color\fP = 2131034277"
.br
.ti -1c
.RI "const int \fBmtrl_chip_text_color\fP = 2131034278"
.br
.ti -1c
.RI "const int \fBmtrl_choice_chip_background_color\fP = 2131034279"
.br
.ti -1c
.RI "const int \fBmtrl_choice_chip_ripple_color\fP = 2131034280"
.br
.ti -1c
.RI "const int \fBmtrl_choice_chip_text_color\fP = 2131034281"
.br
.ti -1c
.RI "const int \fBmtrl_error\fP = 2131034282"
.br
.ti -1c
.RI "const int \fBmtrl_fab_bg_color_selector\fP = 2131034283"
.br
.ti -1c
.RI "const int \fBmtrl_fab_icon_text_color_selector\fP = 2131034284"
.br
.ti -1c
.RI "const int \fBmtrl_fab_ripple_color\fP = 2131034285"
.br
.ti -1c
.RI "const int \fBmtrl_filled_background_color\fP = 2131034286"
.br
.ti -1c
.RI "const int \fBmtrl_filled_icon_tint\fP = 2131034287"
.br
.ti -1c
.RI "const int \fBmtrl_filled_stroke_color\fP = 2131034288"
.br
.ti -1c
.RI "const int \fBmtrl_indicator_text_color\fP = 2131034289"
.br
.ti -1c
.RI "const int \fBmtrl_navigation_item_background_color\fP = 2131034290"
.br
.ti -1c
.RI "const int \fBmtrl_navigation_item_icon_tint\fP = 2131034291"
.br
.ti -1c
.RI "const int \fBmtrl_navigation_item_text_color\fP = 2131034292"
.br
.ti -1c
.RI "const int \fBmtrl_on_primary_text_btn_text_color_selector\fP = 2131034293"
.br
.ti -1c
.RI "const int \fBmtrl_on_surface_ripple_color\fP = 2131034294"
.br
.ti -1c
.RI "const int \fBmtrl_outlined_icon_tint\fP = 2131034295"
.br
.ti -1c
.RI "const int \fBmtrl_outlined_stroke_color\fP = 2131034296"
.br
.ti -1c
.RI "const int \fBmtrl_popupmenu_overlay_color\fP = 2131034297"
.br
.ti -1c
.RI "const int \fBmtrl_scrim_color\fP = 2131034298"
.br
.ti -1c
.RI "const int \fBmtrl_tabs_colored_ripple_color\fP = 2131034299"
.br
.ti -1c
.RI "const int \fBmtrl_tabs_icon_color_selector\fP = 2131034300"
.br
.ti -1c
.RI "const int \fBmtrl_tabs_icon_color_selector_colored\fP = 2131034301"
.br
.ti -1c
.RI "const int \fBmtrl_tabs_legacy_text_color_selector\fP = 2131034302"
.br
.ti -1c
.RI "const int \fBmtrl_tabs_ripple_color\fP = 2131034303"
.br
.ti -1c
.RI "const int \fBmtrl_textinput_default_box_stroke_color\fP = 2131034305"
.br
.ti -1c
.RI "const int \fBmtrl_textinput_disabled_color\fP = 2131034306"
.br
.ti -1c
.RI "const int \fBmtrl_textinput_filled_box_default_background_color\fP = 2131034307"
.br
.ti -1c
.RI "const int \fBmtrl_textinput_focused_box_stroke_color\fP = 2131034308"
.br
.ti -1c
.RI "const int \fBmtrl_textinput_hovered_box_stroke_color\fP = 2131034309"
.br
.ti -1c
.RI "const int \fBmtrl_text_btn_text_color_selector\fP = 2131034304"
.br
.ti -1c
.RI "const int \fBnotification_action_color_filter\fP = 2131034310"
.br
.ti -1c
.RI "const int \fBnotification_icon_bg_color\fP = 2131034311"
.br
.ti -1c
.RI "const int \fBnotification_material_background_media_default_color\fP = 2131034312"
.br
.ti -1c
.RI "const int \fBprimary_dark_material_dark\fP = 2131034313"
.br
.ti -1c
.RI "const int \fBprimary_dark_material_light\fP = 2131034314"
.br
.ti -1c
.RI "const int \fBprimary_material_dark\fP = 2131034315"
.br
.ti -1c
.RI "const int \fBprimary_material_light\fP = 2131034316"
.br
.ti -1c
.RI "const int \fBprimary_text_default_material_dark\fP = 2131034317"
.br
.ti -1c
.RI "const int \fBprimary_text_default_material_light\fP = 2131034318"
.br
.ti -1c
.RI "const int \fBprimary_text_disabled_material_dark\fP = 2131034319"
.br
.ti -1c
.RI "const int \fBprimary_text_disabled_material_light\fP = 2131034320"
.br
.ti -1c
.RI "const int \fBradiobutton_themeable_attribute_color\fP = 2131034321"
.br
.ti -1c
.RI "const int \fBripple_material_dark\fP = 2131034322"
.br
.ti -1c
.RI "const int \fBripple_material_light\fP = 2131034323"
.br
.ti -1c
.RI "const int \fBsecondary_text_default_material_dark\fP = 2131034324"
.br
.ti -1c
.RI "const int \fBsecondary_text_default_material_light\fP = 2131034325"
.br
.ti -1c
.RI "const int \fBsecondary_text_disabled_material_dark\fP = 2131034326"
.br
.ti -1c
.RI "const int \fBsecondary_text_disabled_material_light\fP = 2131034327"
.br
.ti -1c
.RI "const int \fBswitch_thumb_disabled_material_dark\fP = 2131034328"
.br
.ti -1c
.RI "const int \fBswitch_thumb_disabled_material_light\fP = 2131034329"
.br
.ti -1c
.RI "const int \fBswitch_thumb_material_dark\fP = 2131034330"
.br
.ti -1c
.RI "const int \fBswitch_thumb_material_light\fP = 2131034331"
.br
.ti -1c
.RI "const int \fBswitch_thumb_normal_material_dark\fP = 2131034332"
.br
.ti -1c
.RI "const int \fBswitch_thumb_normal_material_light\fP = 2131034333"
.br
.ti -1c
.RI "const int \fBtest_mtrl_calendar_day\fP = 2131034334"
.br
.ti -1c
.RI "const int \fBtest_mtrl_calendar_day_selected\fP = 2131034335"
.br
.ti -1c
.RI "const int \fBtooltip_background_dark\fP = 2131034336"
.br
.ti -1c
.RI "const int \fBtooltip_background_light\fP = 2131034337"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18625 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_background_cache_hint_selector_material_dark = 2131034112\fC [static]\fP"

.PP
Definition at line 18629 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_background_cache_hint_selector_material_light = 2131034113\fC [static]\fP"

.PP
Definition at line 18632 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_btn_colored_borderless_text_material = 2131034114\fC [static]\fP"

.PP
Definition at line 18635 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_btn_colored_text_material = 2131034115\fC [static]\fP"

.PP
Definition at line 18638 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_color_highlight_material = 2131034116\fC [static]\fP"

.PP
Definition at line 18641 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_decor_view_status_guard = 2131034117\fC [static]\fP"

.PP
Definition at line 18644 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_decor_view_status_guard_light = 2131034118\fC [static]\fP"

.PP
Definition at line 18647 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_hint_foreground_material_dark = 2131034119\fC [static]\fP"

.PP
Definition at line 18650 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_hint_foreground_material_light = 2131034120\fC [static]\fP"

.PP
Definition at line 18653 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_primary_text_disable_only_material_dark = 2131034121\fC [static]\fP"

.PP
Definition at line 18656 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_primary_text_disable_only_material_light = 2131034122\fC [static]\fP"

.PP
Definition at line 18659 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_primary_text_material_dark = 2131034123\fC [static]\fP"

.PP
Definition at line 18662 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_primary_text_material_light = 2131034124\fC [static]\fP"

.PP
Definition at line 18665 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_search_url_text = 2131034125\fC [static]\fP"

.PP
Definition at line 18668 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_search_url_text_normal = 2131034126\fC [static]\fP"

.PP
Definition at line 18671 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_search_url_text_pressed = 2131034127\fC [static]\fP"

.PP
Definition at line 18674 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_search_url_text_selected = 2131034128\fC [static]\fP"

.PP
Definition at line 18677 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_secondary_text_material_dark = 2131034129\fC [static]\fP"

.PP
Definition at line 18680 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_secondary_text_material_light = 2131034130\fC [static]\fP"

.PP
Definition at line 18683 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_tint_btn_checkable = 2131034131\fC [static]\fP"

.PP
Definition at line 18686 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_tint_default = 2131034132\fC [static]\fP"

.PP
Definition at line 18689 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_tint_edittext = 2131034133\fC [static]\fP"

.PP
Definition at line 18692 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_tint_seek_thumb = 2131034134\fC [static]\fP"

.PP
Definition at line 18695 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_tint_spinner = 2131034135\fC [static]\fP"

.PP
Definition at line 18698 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.abc_tint_switch_track = 2131034136\fC [static]\fP"

.PP
Definition at line 18701 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.accent_material_dark = 2131034137\fC [static]\fP"

.PP
Definition at line 18704 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.accent_material_light = 2131034138\fC [static]\fP"

.PP
Definition at line 18707 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.androidx_core_ripple_material_light = 2131034139\fC [static]\fP"

.PP
Definition at line 18710 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.androidx_core_secondary_text_default_material_light = 2131034140\fC [static]\fP"

.PP
Definition at line 18713 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.background_floating_material_dark = 2131034141\fC [static]\fP"

.PP
Definition at line 18716 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.background_floating_material_light = 2131034142\fC [static]\fP"

.PP
Definition at line 18719 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.background_material_dark = 2131034143\fC [static]\fP"

.PP
Definition at line 18722 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.background_material_light = 2131034144\fC [static]\fP"

.PP
Definition at line 18725 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.bright_foreground_disabled_material_dark = 2131034145\fC [static]\fP"

.PP
Definition at line 18728 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.bright_foreground_disabled_material_light = 2131034146\fC [static]\fP"

.PP
Definition at line 18731 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.bright_foreground_inverse_material_dark = 2131034147\fC [static]\fP"

.PP
Definition at line 18734 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.bright_foreground_inverse_material_light = 2131034148\fC [static]\fP"

.PP
Definition at line 18737 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.bright_foreground_material_dark = 2131034149\fC [static]\fP"

.PP
Definition at line 18740 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.bright_foreground_material_light = 2131034150\fC [static]\fP"

.PP
Definition at line 18743 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.browser_actions_bg_grey = 2131034151\fC [static]\fP"

.PP
Definition at line 18746 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.browser_actions_divider_color = 2131034152\fC [static]\fP"

.PP
Definition at line 18749 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.browser_actions_text_color = 2131034153\fC [static]\fP"

.PP
Definition at line 18752 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.browser_actions_title_color = 2131034154\fC [static]\fP"

.PP
Definition at line 18755 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.button_material_dark = 2131034155\fC [static]\fP"

.PP
Definition at line 18758 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.button_material_light = 2131034156\fC [static]\fP"

.PP
Definition at line 18761 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.cardview_dark_background = 2131034157\fC [static]\fP"

.PP
Definition at line 18764 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.cardview_light_background = 2131034158\fC [static]\fP"

.PP
Definition at line 18767 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.cardview_shadow_end_color = 2131034159\fC [static]\fP"

.PP
Definition at line 18770 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.cardview_shadow_start_color = 2131034160\fC [static]\fP"

.PP
Definition at line 18773 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.checkbox_themeable_attribute_color = 2131034161\fC [static]\fP"

.PP
Definition at line 18776 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.colorAccent = 2131034162\fC [static]\fP"

.PP
Definition at line 18779 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.colorPrimary = 2131034163\fC [static]\fP"

.PP
Definition at line 18782 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.colorPrimaryDark = 2131034164\fC [static]\fP"

.PP
Definition at line 18785 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_dark = 2131034165\fC [static]\fP"

.PP
Definition at line 18788 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_dark_default = 2131034166\fC [static]\fP"

.PP
Definition at line 18791 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_dark_disabled = 2131034167\fC [static]\fP"

.PP
Definition at line 18794 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_dark_focused = 2131034168\fC [static]\fP"

.PP
Definition at line 18797 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_dark_pressed = 2131034169\fC [static]\fP"

.PP
Definition at line 18800 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_light = 2131034170\fC [static]\fP"

.PP
Definition at line 18803 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_light_default = 2131034171\fC [static]\fP"

.PP
Definition at line 18806 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_light_disabled = 2131034172\fC [static]\fP"

.PP
Definition at line 18809 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_light_focused = 2131034173\fC [static]\fP"

.PP
Definition at line 18812 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_text_light_pressed = 2131034174\fC [static]\fP"

.PP
Definition at line 18815 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.common_google_signin_btn_tint = 2131034175\fC [static]\fP"

.PP
Definition at line 18818 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_bottom_navigation_shadow_color = 2131034176\fC [static]\fP"

.PP
Definition at line 18821 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_box_stroke_color = 2131034177\fC [static]\fP"

.PP
Definition at line 18824 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_background = 2131034178\fC [static]\fP"

.PP
Definition at line 18827 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_error = 2131034179\fC [static]\fP"

.PP
Definition at line 18830 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_on_background = 2131034180\fC [static]\fP"

.PP
Definition at line 18833 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_on_error = 2131034181\fC [static]\fP"

.PP
Definition at line 18836 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_on_primary = 2131034182\fC [static]\fP"

.PP
Definition at line 18839 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_on_secondary = 2131034183\fC [static]\fP"

.PP
Definition at line 18842 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_on_surface = 2131034184\fC [static]\fP"

.PP
Definition at line 18845 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_primary = 2131034185\fC [static]\fP"

.PP
Definition at line 18848 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_primary_dark = 2131034186\fC [static]\fP"

.PP
Definition at line 18851 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_primary_variant = 2131034187\fC [static]\fP"

.PP
Definition at line 18854 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_secondary = 2131034188\fC [static]\fP"

.PP
Definition at line 18857 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_secondary_variant = 2131034189\fC [static]\fP"

.PP
Definition at line 18860 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_dark_default_color_surface = 2131034190\fC [static]\fP"

.PP
Definition at line 18863 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_background = 2131034191\fC [static]\fP"

.PP
Definition at line 18866 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_error = 2131034192\fC [static]\fP"

.PP
Definition at line 18869 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_on_background = 2131034193\fC [static]\fP"

.PP
Definition at line 18872 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_on_error = 2131034194\fC [static]\fP"

.PP
Definition at line 18875 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_on_primary = 2131034195\fC [static]\fP"

.PP
Definition at line 18878 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_on_secondary = 2131034196\fC [static]\fP"

.PP
Definition at line 18881 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_on_surface = 2131034197\fC [static]\fP"

.PP
Definition at line 18884 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_primary = 2131034198\fC [static]\fP"

.PP
Definition at line 18887 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_primary_dark = 2131034199\fC [static]\fP"

.PP
Definition at line 18890 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_primary_variant = 2131034200\fC [static]\fP"

.PP
Definition at line 18893 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_secondary = 2131034201\fC [static]\fP"

.PP
Definition at line 18896 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_secondary_variant = 2131034202\fC [static]\fP"

.PP
Definition at line 18899 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_default_color_surface = 2131034203\fC [static]\fP"

.PP
Definition at line 18902 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_error = 2131034204\fC [static]\fP"

.PP
Definition at line 18905 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_shadow_end_color = 2131034205\fC [static]\fP"

.PP
Definition at line 18908 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_shadow_mid_color = 2131034206\fC [static]\fP"

.PP
Definition at line 18911 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_shadow_start_color = 2131034207\fC [static]\fP"

.PP
Definition at line 18914 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_stroke_end_inner_color = 2131034208\fC [static]\fP"

.PP
Definition at line 18917 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_stroke_end_outer_color = 2131034209\fC [static]\fP"

.PP
Definition at line 18920 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_stroke_top_inner_color = 2131034210\fC [static]\fP"

.PP
Definition at line 18923 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_fab_stroke_top_outer_color = 2131034211\fC [static]\fP"

.PP
Definition at line 18926 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_icon_tint = 2131034212\fC [static]\fP"

.PP
Definition at line 18929 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.design_snackbar_background_color = 2131034213\fC [static]\fP"

.PP
Definition at line 18932 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.dim_foreground_disabled_material_dark = 2131034214\fC [static]\fP"

.PP
Definition at line 18935 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.dim_foreground_disabled_material_light = 2131034215\fC [static]\fP"

.PP
Definition at line 18938 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.dim_foreground_material_dark = 2131034216\fC [static]\fP"

.PP
Definition at line 18941 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.dim_foreground_material_light = 2131034217\fC [static]\fP"

.PP
Definition at line 18944 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.error_color_material_dark = 2131034218\fC [static]\fP"

.PP
Definition at line 18947 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.error_color_material_light = 2131034219\fC [static]\fP"

.PP
Definition at line 18950 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.foreground_material_dark = 2131034220\fC [static]\fP"

.PP
Definition at line 18953 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.foreground_material_light = 2131034221\fC [static]\fP"

.PP
Definition at line 18956 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.highlighted_text_material_dark = 2131034222\fC [static]\fP"

.PP
Definition at line 18959 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.highlighted_text_material_light = 2131034223\fC [static]\fP"

.PP
Definition at line 18962 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.launcher_background = 2131034224\fC [static]\fP"

.PP
Definition at line 18965 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_blue_grey_800 = 2131034225\fC [static]\fP"

.PP
Definition at line 18968 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_blue_grey_900 = 2131034226\fC [static]\fP"

.PP
Definition at line 18971 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_blue_grey_950 = 2131034227\fC [static]\fP"

.PP
Definition at line 18974 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_cursor_color = 2131034228\fC [static]\fP"

.PP
Definition at line 18977 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_deep_teal_200 = 2131034229\fC [static]\fP"

.PP
Definition at line 18980 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_deep_teal_500 = 2131034230\fC [static]\fP"

.PP
Definition at line 18983 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_100 = 2131034231\fC [static]\fP"

.PP
Definition at line 18986 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_300 = 2131034232\fC [static]\fP"

.PP
Definition at line 18989 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_50 = 2131034233\fC [static]\fP"

.PP
Definition at line 18992 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_600 = 2131034234\fC [static]\fP"

.PP
Definition at line 18995 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_800 = 2131034235\fC [static]\fP"

.PP
Definition at line 18998 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_850 = 2131034236\fC [static]\fP"

.PP
Definition at line 19001 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_grey_900 = 2131034237\fC [static]\fP"

.PP
Definition at line 19004 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_background_disabled = 2131034238\fC [static]\fP"

.PP
Definition at line 19007 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_background_emphasis_high_type = 2131034239\fC [static]\fP"

.PP
Definition at line 19010 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_background_emphasis_medium = 2131034240\fC [static]\fP"

.PP
Definition at line 19013 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_primary_disabled = 2131034241\fC [static]\fP"

.PP
Definition at line 19016 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_primary_emphasis_high_type = 2131034242\fC [static]\fP"

.PP
Definition at line 19019 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_primary_emphasis_medium = 2131034243\fC [static]\fP"

.PP
Definition at line 19022 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_surface_disabled = 2131034244\fC [static]\fP"

.PP
Definition at line 19025 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_surface_emphasis_high_type = 2131034245\fC [static]\fP"

.PP
Definition at line 19028 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_surface_emphasis_medium = 2131034246\fC [static]\fP"

.PP
Definition at line 19031 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_on_surface_stroke = 2131034247\fC [static]\fP"

.PP
Definition at line 19034 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_slider_active_tick_marks_color = 2131034248\fC [static]\fP"

.PP
Definition at line 19037 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_slider_active_track_color = 2131034249\fC [static]\fP"

.PP
Definition at line 19040 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_slider_halo_color = 2131034250\fC [static]\fP"

.PP
Definition at line 19043 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_slider_inactive_tick_marks_color = 2131034251\fC [static]\fP"

.PP
Definition at line 19046 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_slider_inactive_track_color = 2131034252\fC [static]\fP"

.PP
Definition at line 19049 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_slider_thumb_color = 2131034253\fC [static]\fP"

.PP
Definition at line 19052 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_timepicker_button_background = 2131034254\fC [static]\fP"

.PP
Definition at line 19055 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_timepicker_button_stroke = 2131034255\fC [static]\fP"

.PP
Definition at line 19058 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_timepicker_clock_text_color = 2131034256\fC [static]\fP"

.PP
Definition at line 19064 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_timepicker_clockface = 2131034257\fC [static]\fP"

.PP
Definition at line 19061 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.material_timepicker_modebutton_tint = 2131034258\fC [static]\fP"

.PP
Definition at line 19067 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_bottom_nav_colored_item_tint = 2131034259\fC [static]\fP"

.PP
Definition at line 19070 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_bottom_nav_colored_ripple_color = 2131034260\fC [static]\fP"

.PP
Definition at line 19073 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_bottom_nav_item_tint = 2131034261\fC [static]\fP"

.PP
Definition at line 19076 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_bottom_nav_ripple_color = 2131034262\fC [static]\fP"

.PP
Definition at line 19079 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_bg_color_selector = 2131034263\fC [static]\fP"

.PP
Definition at line 19082 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_ripple_color = 2131034264\fC [static]\fP"

.PP
Definition at line 19085 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_stroke_color_selector = 2131034265\fC [static]\fP"

.PP
Definition at line 19088 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_text_btn_bg_color_selector = 2131034266\fC [static]\fP"

.PP
Definition at line 19091 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_text_btn_ripple_color = 2131034267\fC [static]\fP"

.PP
Definition at line 19094 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_text_color_disabled = 2131034268\fC [static]\fP"

.PP
Definition at line 19097 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_text_color_selector = 2131034269\fC [static]\fP"

.PP
Definition at line 19100 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_btn_transparent_bg_color = 2131034270\fC [static]\fP"

.PP
Definition at line 19103 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_calendar_item_stroke_color = 2131034271\fC [static]\fP"

.PP
Definition at line 19106 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_calendar_selected_range = 2131034272\fC [static]\fP"

.PP
Definition at line 19109 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_card_view_foreground = 2131034273\fC [static]\fP"

.PP
Definition at line 19112 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_card_view_ripple = 2131034274\fC [static]\fP"

.PP
Definition at line 19115 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_chip_background_color = 2131034275\fC [static]\fP"

.PP
Definition at line 19118 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_chip_close_icon_tint = 2131034276\fC [static]\fP"

.PP
Definition at line 19121 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_chip_surface_color = 2131034277\fC [static]\fP"

.PP
Definition at line 19124 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_chip_text_color = 2131034278\fC [static]\fP"

.PP
Definition at line 19127 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_choice_chip_background_color = 2131034279\fC [static]\fP"

.PP
Definition at line 19130 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_choice_chip_ripple_color = 2131034280\fC [static]\fP"

.PP
Definition at line 19133 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_choice_chip_text_color = 2131034281\fC [static]\fP"

.PP
Definition at line 19136 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_error = 2131034282\fC [static]\fP"

.PP
Definition at line 19139 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_fab_bg_color_selector = 2131034283\fC [static]\fP"

.PP
Definition at line 19142 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_fab_icon_text_color_selector = 2131034284\fC [static]\fP"

.PP
Definition at line 19145 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_fab_ripple_color = 2131034285\fC [static]\fP"

.PP
Definition at line 19148 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_filled_background_color = 2131034286\fC [static]\fP"

.PP
Definition at line 19151 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_filled_icon_tint = 2131034287\fC [static]\fP"

.PP
Definition at line 19154 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_filled_stroke_color = 2131034288\fC [static]\fP"

.PP
Definition at line 19157 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_indicator_text_color = 2131034289\fC [static]\fP"

.PP
Definition at line 19160 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_navigation_item_background_color = 2131034290\fC [static]\fP"

.PP
Definition at line 19163 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_navigation_item_icon_tint = 2131034291\fC [static]\fP"

.PP
Definition at line 19166 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_navigation_item_text_color = 2131034292\fC [static]\fP"

.PP
Definition at line 19169 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_on_primary_text_btn_text_color_selector = 2131034293\fC [static]\fP"

.PP
Definition at line 19172 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_on_surface_ripple_color = 2131034294\fC [static]\fP"

.PP
Definition at line 19175 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_outlined_icon_tint = 2131034295\fC [static]\fP"

.PP
Definition at line 19178 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_outlined_stroke_color = 2131034296\fC [static]\fP"

.PP
Definition at line 19181 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_popupmenu_overlay_color = 2131034297\fC [static]\fP"

.PP
Definition at line 19184 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_scrim_color = 2131034298\fC [static]\fP"

.PP
Definition at line 19187 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_tabs_colored_ripple_color = 2131034299\fC [static]\fP"

.PP
Definition at line 19190 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_tabs_icon_color_selector = 2131034300\fC [static]\fP"

.PP
Definition at line 19193 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_tabs_icon_color_selector_colored = 2131034301\fC [static]\fP"

.PP
Definition at line 19196 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_tabs_legacy_text_color_selector = 2131034302\fC [static]\fP"

.PP
Definition at line 19199 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_tabs_ripple_color = 2131034303\fC [static]\fP"

.PP
Definition at line 19202 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_text_btn_text_color_selector = 2131034304\fC [static]\fP"

.PP
Definition at line 19220 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_textinput_default_box_stroke_color = 2131034305\fC [static]\fP"

.PP
Definition at line 19205 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_textinput_disabled_color = 2131034306\fC [static]\fP"

.PP
Definition at line 19208 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_textinput_filled_box_default_background_color = 2131034307\fC [static]\fP"

.PP
Definition at line 19211 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_textinput_focused_box_stroke_color = 2131034308\fC [static]\fP"

.PP
Definition at line 19214 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.mtrl_textinput_hovered_box_stroke_color = 2131034309\fC [static]\fP"

.PP
Definition at line 19217 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.notification_action_color_filter = 2131034310\fC [static]\fP"

.PP
Definition at line 19223 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.notification_icon_bg_color = 2131034311\fC [static]\fP"

.PP
Definition at line 19226 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.notification_material_background_media_default_color = 2131034312\fC [static]\fP"

.PP
Definition at line 19229 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_dark_material_dark = 2131034313\fC [static]\fP"

.PP
Definition at line 19232 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_dark_material_light = 2131034314\fC [static]\fP"

.PP
Definition at line 19235 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_material_dark = 2131034315\fC [static]\fP"

.PP
Definition at line 19238 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_material_light = 2131034316\fC [static]\fP"

.PP
Definition at line 19241 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_text_default_material_dark = 2131034317\fC [static]\fP"

.PP
Definition at line 19244 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_text_default_material_light = 2131034318\fC [static]\fP"

.PP
Definition at line 19247 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_text_disabled_material_dark = 2131034319\fC [static]\fP"

.PP
Definition at line 19250 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.primary_text_disabled_material_light = 2131034320\fC [static]\fP"

.PP
Definition at line 19253 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.radiobutton_themeable_attribute_color = 2131034321\fC [static]\fP"

.PP
Definition at line 19256 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.ripple_material_dark = 2131034322\fC [static]\fP"

.PP
Definition at line 19259 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.ripple_material_light = 2131034323\fC [static]\fP"

.PP
Definition at line 19262 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.secondary_text_default_material_dark = 2131034324\fC [static]\fP"

.PP
Definition at line 19265 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.secondary_text_default_material_light = 2131034325\fC [static]\fP"

.PP
Definition at line 19268 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.secondary_text_disabled_material_dark = 2131034326\fC [static]\fP"

.PP
Definition at line 19271 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.secondary_text_disabled_material_light = 2131034327\fC [static]\fP"

.PP
Definition at line 19274 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.switch_thumb_disabled_material_dark = 2131034328\fC [static]\fP"

.PP
Definition at line 19277 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.switch_thumb_disabled_material_light = 2131034329\fC [static]\fP"

.PP
Definition at line 19280 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.switch_thumb_material_dark = 2131034330\fC [static]\fP"

.PP
Definition at line 19283 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.switch_thumb_material_light = 2131034331\fC [static]\fP"

.PP
Definition at line 19286 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.switch_thumb_normal_material_dark = 2131034332\fC [static]\fP"

.PP
Definition at line 19289 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.switch_thumb_normal_material_light = 2131034333\fC [static]\fP"

.PP
Definition at line 19292 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.test_mtrl_calendar_day = 2131034334\fC [static]\fP"

.PP
Definition at line 19295 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.test_mtrl_calendar_day_selected = 2131034335\fC [static]\fP"

.PP
Definition at line 19298 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.tooltip_background_dark = 2131034336\fC [static]\fP"

.PP
Definition at line 19301 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Color\&.tooltip_background_light = 2131034337\fC [static]\fP"

.PP
Definition at line 19304 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
