.TH "Application_Green_Quake.Models.Points" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.Points
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Points\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.Points\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file Points\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.Points\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file Points\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
