.TH "Application_Green_Quake.ViewModels.CommunityPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.CommunityPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBCreateGroupPoints\fP ()"
.br
.ti -1c
.RI "async void \fBCommunityPoints\fP ()"
.br
.ti -1c
.RI "async void \fBDonatePoints\fP ()"
.br
.ti -1c
.RI "async void \fBGroupPoints\fP ()"
.br
.ti -1c
.RI "async void \fBSharePoints\fP ()"
.br
.ti -1c
.RI "async void \fBawarenessPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file CommunityPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.CommunityPointsUpdate\&.awarenessPoints ()"
This function updates the points in the Community category by eight points\&. It also increments the number of logs logged in the Community category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 571 of file CommunityPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.CommunityPointsUpdate\&.CommunityPoints ()"
This function updates the points in the Community category by ten points\&. It also increments the number of logs logged in the Community category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 143 of file CommunityPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.CommunityPointsUpdate\&.CreateGroupPoints ()"
This function updates the points in the Community category by ten points\&. It also increments the number of logs logged in the Community category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 36 of file CommunityPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.CommunityPointsUpdate\&.DonatePoints ()"
This function updates the points in the Community category by ten points\&. It also increments the number of logs logged in the Community category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 250 of file CommunityPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.CommunityPointsUpdate\&.GroupPoints ()"
This function updates the points in the Community category by eight points\&. It also increments the number of logs logged in the Community category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 357 of file CommunityPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.CommunityPointsUpdate\&.SharePoints ()"
This function updates the points in the Community category by eight points\&. It also increments the number of logs logged in the Community category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 464 of file CommunityPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
