.TH "Application_Green_Quake.Droid.Resource.Layout" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Layout
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_action_bar_title_item\fP = 2131427328"
.br
.ti -1c
.RI "const int \fBabc_action_bar_up_container\fP = 2131427329"
.br
.ti -1c
.RI "const int \fBabc_action_menu_item_layout\fP = 2131427330"
.br
.ti -1c
.RI "const int \fBabc_action_menu_layout\fP = 2131427331"
.br
.ti -1c
.RI "const int \fBabc_action_mode_bar\fP = 2131427332"
.br
.ti -1c
.RI "const int \fBabc_action_mode_close_item_material\fP = 2131427333"
.br
.ti -1c
.RI "const int \fBabc_activity_chooser_view\fP = 2131427334"
.br
.ti -1c
.RI "const int \fBabc_activity_chooser_view_list_item\fP = 2131427335"
.br
.ti -1c
.RI "const int \fBabc_alert_dialog_button_bar_material\fP = 2131427336"
.br
.ti -1c
.RI "const int \fBabc_alert_dialog_material\fP = 2131427337"
.br
.ti -1c
.RI "const int \fBabc_alert_dialog_title_material\fP = 2131427338"
.br
.ti -1c
.RI "const int \fBabc_cascading_menu_item_layout\fP = 2131427339"
.br
.ti -1c
.RI "const int \fBabc_dialog_title_material\fP = 2131427340"
.br
.ti -1c
.RI "const int \fBabc_expanded_menu_layout\fP = 2131427341"
.br
.ti -1c
.RI "const int \fBabc_list_menu_item_checkbox\fP = 2131427342"
.br
.ti -1c
.RI "const int \fBabc_list_menu_item_icon\fP = 2131427343"
.br
.ti -1c
.RI "const int \fBabc_list_menu_item_layout\fP = 2131427344"
.br
.ti -1c
.RI "const int \fBabc_list_menu_item_radio\fP = 2131427345"
.br
.ti -1c
.RI "const int \fBabc_popup_menu_header_item_layout\fP = 2131427346"
.br
.ti -1c
.RI "const int \fBabc_popup_menu_item_layout\fP = 2131427347"
.br
.ti -1c
.RI "const int \fBabc_screen_content_include\fP = 2131427348"
.br
.ti -1c
.RI "const int \fBabc_screen_simple\fP = 2131427349"
.br
.ti -1c
.RI "const int \fBabc_screen_simple_overlay_action_mode\fP = 2131427350"
.br
.ti -1c
.RI "const int \fBabc_screen_toolbar\fP = 2131427351"
.br
.ti -1c
.RI "const int \fBabc_search_dropdown_item_icons_2line\fP = 2131427352"
.br
.ti -1c
.RI "const int \fBabc_search_view\fP = 2131427353"
.br
.ti -1c
.RI "const int \fBabc_select_dialog_material\fP = 2131427354"
.br
.ti -1c
.RI "const int \fBabc_tooltip\fP = 2131427355"
.br
.ti -1c
.RI "const int \fBBottomTabLayout\fP = 2131427356"
.br
.ti -1c
.RI "const int \fBbrowser_actions_context_menu_page\fP = 2131427357"
.br
.ti -1c
.RI "const int \fBbrowser_actions_context_menu_row\fP = 2131427358"
.br
.ti -1c
.RI "const int \fBcustom_dialog\fP = 2131427359"
.br
.ti -1c
.RI "const int \fBdesign_bottom_navigation_item\fP = 2131427360"
.br
.ti -1c
.RI "const int \fBdesign_bottom_sheet_dialog\fP = 2131427361"
.br
.ti -1c
.RI "const int \fBdesign_layout_snackbar\fP = 2131427362"
.br
.ti -1c
.RI "const int \fBdesign_layout_snackbar_include\fP = 2131427363"
.br
.ti -1c
.RI "const int \fBdesign_layout_tab_icon\fP = 2131427364"
.br
.ti -1c
.RI "const int \fBdesign_layout_tab_text\fP = 2131427365"
.br
.ti -1c
.RI "const int \fBdesign_menu_item_action_area\fP = 2131427366"
.br
.ti -1c
.RI "const int \fBdesign_navigation_item\fP = 2131427367"
.br
.ti -1c
.RI "const int \fBdesign_navigation_item_header\fP = 2131427368"
.br
.ti -1c
.RI "const int \fBdesign_navigation_item_separator\fP = 2131427369"
.br
.ti -1c
.RI "const int \fBdesign_navigation_item_subheader\fP = 2131427370"
.br
.ti -1c
.RI "const int \fBdesign_navigation_menu\fP = 2131427371"
.br
.ti -1c
.RI "const int \fBdesign_navigation_menu_item\fP = 2131427372"
.br
.ti -1c
.RI "const int \fBdesign_text_input_end_icon\fP = 2131427373"
.br
.ti -1c
.RI "const int \fBdesign_text_input_start_icon\fP = 2131427374"
.br
.ti -1c
.RI "const int \fBFallbackTabbarDoNotUse\fP = 2131427375"
.br
.ti -1c
.RI "const int \fBFallbackToolbarDoNotUse\fP = 2131427376"
.br
.ti -1c
.RI "const int \fBFlyoutContent\fP = 2131427377"
.br
.ti -1c
.RI "const int \fBloading\fP = 2131427378"
.br
.ti -1c
.RI "const int \fBloadingimage\fP = 2131427379"
.br
.ti -1c
.RI "const int \fBloadingprogress\fP = 2131427380"
.br
.ti -1c
.RI "const int \fBmaterial_chip_input_combo\fP = 2131427381"
.br
.ti -1c
.RI "const int \fBmaterial_clockface_textview\fP = 2131427386"
.br
.ti -1c
.RI "const int \fBmaterial_clockface_view\fP = 2131427387"
.br
.ti -1c
.RI "const int \fBmaterial_clock_display\fP = 2131427382"
.br
.ti -1c
.RI "const int \fBmaterial_clock_display_divider\fP = 2131427383"
.br
.ti -1c
.RI "const int \fBmaterial_clock_period_toggle\fP = 2131427384"
.br
.ti -1c
.RI "const int \fBmaterial_clock_period_toggle_land\fP = 2131427385"
.br
.ti -1c
.RI "const int \fBmaterial_radial_view_group\fP = 2131427388"
.br
.ti -1c
.RI "const int \fBmaterial_textinput_timepicker\fP = 2131427389"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker\fP = 2131427392"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_dialog\fP = 2131427393"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_textinput_display\fP = 2131427394"
.br
.ti -1c
.RI "const int \fBmaterial_time_chip\fP = 2131427390"
.br
.ti -1c
.RI "const int \fBmaterial_time_input\fP = 2131427391"
.br
.ti -1c
.RI "const int \fBmtrl_alert_dialog\fP = 2131427395"
.br
.ti -1c
.RI "const int \fBmtrl_alert_dialog_actions\fP = 2131427396"
.br
.ti -1c
.RI "const int \fBmtrl_alert_dialog_title\fP = 2131427397"
.br
.ti -1c
.RI "const int \fBmtrl_alert_select_dialog_item\fP = 2131427398"
.br
.ti -1c
.RI "const int \fBmtrl_alert_select_dialog_multichoice\fP = 2131427399"
.br
.ti -1c
.RI "const int \fBmtrl_alert_select_dialog_singlechoice\fP = 2131427400"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_day\fP = 2131427401"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_days_of_week\fP = 2131427403"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_day_of_week\fP = 2131427402"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_horizontal\fP = 2131427404"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_month\fP = 2131427405"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_months\fP = 2131427408"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_month_labeled\fP = 2131427406"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_month_navigation\fP = 2131427407"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_vertical\fP = 2131427409"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_year\fP = 2131427410"
.br
.ti -1c
.RI "const int \fBmtrl_layout_snackbar\fP = 2131427411"
.br
.ti -1c
.RI "const int \fBmtrl_layout_snackbar_include\fP = 2131427412"
.br
.ti -1c
.RI "const int \fBmtrl_picker_actions\fP = 2131427413"
.br
.ti -1c
.RI "const int \fBmtrl_picker_dialog\fP = 2131427414"
.br
.ti -1c
.RI "const int \fBmtrl_picker_fullscreen\fP = 2131427415"
.br
.ti -1c
.RI "const int \fBmtrl_picker_header_dialog\fP = 2131427416"
.br
.ti -1c
.RI "const int \fBmtrl_picker_header_fullscreen\fP = 2131427417"
.br
.ti -1c
.RI "const int \fBmtrl_picker_header_selection_text\fP = 2131427418"
.br
.ti -1c
.RI "const int \fBmtrl_picker_header_title_text\fP = 2131427419"
.br
.ti -1c
.RI "const int \fBmtrl_picker_header_toggle\fP = 2131427420"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_date\fP = 2131427421"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_date_range\fP = 2131427422"
.br
.ti -1c
.RI "const int \fBnotification_action\fP = 2131427423"
.br
.ti -1c
.RI "const int \fBnotification_action_tombstone\fP = 2131427424"
.br
.ti -1c
.RI "const int \fBnotification_media_action\fP = 2131427425"
.br
.ti -1c
.RI "const int \fBnotification_media_cancel_action\fP = 2131427426"
.br
.ti -1c
.RI "const int \fBnotification_template_big_media\fP = 2131427427"
.br
.ti -1c
.RI "const int \fBnotification_template_big_media_custom\fP = 2131427428"
.br
.ti -1c
.RI "const int \fBnotification_template_big_media_narrow\fP = 2131427429"
.br
.ti -1c
.RI "const int \fBnotification_template_big_media_narrow_custom\fP = 2131427430"
.br
.ti -1c
.RI "const int \fBnotification_template_custom_big\fP = 2131427431"
.br
.ti -1c
.RI "const int \fBnotification_template_icon_group\fP = 2131427432"
.br
.ti -1c
.RI "const int \fBnotification_template_lines_media\fP = 2131427433"
.br
.ti -1c
.RI "const int \fBnotification_template_media\fP = 2131427434"
.br
.ti -1c
.RI "const int \fBnotification_template_media_custom\fP = 2131427435"
.br
.ti -1c
.RI "const int \fBnotification_template_part_chronometer\fP = 2131427436"
.br
.ti -1c
.RI "const int \fBnotification_template_part_time\fP = 2131427437"
.br
.ti -1c
.RI "const int \fBRootLayout\fP = 2131427438"
.br
.ti -1c
.RI "const int \fBselect_dialog_item_material\fP = 2131427439"
.br
.ti -1c
.RI "const int \fBselect_dialog_multichoice_material\fP = 2131427440"
.br
.ti -1c
.RI "const int \fBselect_dialog_singlechoice_material\fP = 2131427441"
.br
.ti -1c
.RI "const int \fBShellContent\fP = 2131427442"
.br
.ti -1c
.RI "const int \fBsupport_simple_spinner_dropdown_item\fP = 2131427443"
.br
.ti -1c
.RI "const int \fBTabbar\fP = 2131427444"
.br
.ti -1c
.RI "const int \fBtest_action_chip\fP = 2131427445"
.br
.ti -1c
.RI "const int \fBtest_chip_zero_corner_radius\fP = 2131427446"
.br
.ti -1c
.RI "const int \fBtest_design_checkbox\fP = 2131427447"
.br
.ti -1c
.RI "const int \fBtest_design_radiobutton\fP = 2131427448"
.br
.ti -1c
.RI "const int \fBtest_reflow_chipgroup\fP = 2131427449"
.br
.ti -1c
.RI "const int \fBtest_toolbar\fP = 2131427450"
.br
.ti -1c
.RI "const int \fBtest_toolbar_custom_background\fP = 2131427451"
.br
.ti -1c
.RI "const int \fBtest_toolbar_elevation\fP = 2131427452"
.br
.ti -1c
.RI "const int \fBtest_toolbar_surface\fP = 2131427453"
.br
.ti -1c
.RI "const int \fBtext_view_without_line_height\fP = 2131427458"
.br
.ti -1c
.RI "const int \fBtext_view_with_line_height_from_appearance\fP = 2131427454"
.br
.ti -1c
.RI "const int \fBtext_view_with_line_height_from_layout\fP = 2131427455"
.br
.ti -1c
.RI "const int \fBtext_view_with_line_height_from_style\fP = 2131427456"
.br
.ti -1c
.RI "const int \fBtext_view_with_theme_line_height\fP = 2131427457"
.br
.ti -1c
.RI "const int \fBToolbar\fP = 2131427459"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22519 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_action_bar_title_item = 2131427328\fC [static]\fP"

.PP
Definition at line 22523 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_action_bar_up_container = 2131427329\fC [static]\fP"

.PP
Definition at line 22526 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_action_menu_item_layout = 2131427330\fC [static]\fP"

.PP
Definition at line 22529 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_action_menu_layout = 2131427331\fC [static]\fP"

.PP
Definition at line 22532 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_action_mode_bar = 2131427332\fC [static]\fP"

.PP
Definition at line 22535 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_action_mode_close_item_material = 2131427333\fC [static]\fP"

.PP
Definition at line 22538 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_activity_chooser_view = 2131427334\fC [static]\fP"

.PP
Definition at line 22541 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_activity_chooser_view_list_item = 2131427335\fC [static]\fP"

.PP
Definition at line 22544 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_alert_dialog_button_bar_material = 2131427336\fC [static]\fP"

.PP
Definition at line 22547 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_alert_dialog_material = 2131427337\fC [static]\fP"

.PP
Definition at line 22550 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_alert_dialog_title_material = 2131427338\fC [static]\fP"

.PP
Definition at line 22553 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_cascading_menu_item_layout = 2131427339\fC [static]\fP"

.PP
Definition at line 22556 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_dialog_title_material = 2131427340\fC [static]\fP"

.PP
Definition at line 22559 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_expanded_menu_layout = 2131427341\fC [static]\fP"

.PP
Definition at line 22562 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_list_menu_item_checkbox = 2131427342\fC [static]\fP"

.PP
Definition at line 22565 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_list_menu_item_icon = 2131427343\fC [static]\fP"

.PP
Definition at line 22568 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_list_menu_item_layout = 2131427344\fC [static]\fP"

.PP
Definition at line 22571 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_list_menu_item_radio = 2131427345\fC [static]\fP"

.PP
Definition at line 22574 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_popup_menu_header_item_layout = 2131427346\fC [static]\fP"

.PP
Definition at line 22577 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_popup_menu_item_layout = 2131427347\fC [static]\fP"

.PP
Definition at line 22580 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_screen_content_include = 2131427348\fC [static]\fP"

.PP
Definition at line 22583 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_screen_simple = 2131427349\fC [static]\fP"

.PP
Definition at line 22586 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_screen_simple_overlay_action_mode = 2131427350\fC [static]\fP"

.PP
Definition at line 22589 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_screen_toolbar = 2131427351\fC [static]\fP"

.PP
Definition at line 22592 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_search_dropdown_item_icons_2line = 2131427352\fC [static]\fP"

.PP
Definition at line 22595 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_search_view = 2131427353\fC [static]\fP"

.PP
Definition at line 22598 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_select_dialog_material = 2131427354\fC [static]\fP"

.PP
Definition at line 22601 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.abc_tooltip = 2131427355\fC [static]\fP"

.PP
Definition at line 22604 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.BottomTabLayout = 2131427356\fC [static]\fP"

.PP
Definition at line 22607 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.browser_actions_context_menu_page = 2131427357\fC [static]\fP"

.PP
Definition at line 22610 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.browser_actions_context_menu_row = 2131427358\fC [static]\fP"

.PP
Definition at line 22613 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.custom_dialog = 2131427359\fC [static]\fP"

.PP
Definition at line 22616 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_bottom_navigation_item = 2131427360\fC [static]\fP"

.PP
Definition at line 22619 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_bottom_sheet_dialog = 2131427361\fC [static]\fP"

.PP
Definition at line 22622 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_layout_snackbar = 2131427362\fC [static]\fP"

.PP
Definition at line 22625 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_layout_snackbar_include = 2131427363\fC [static]\fP"

.PP
Definition at line 22628 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_layout_tab_icon = 2131427364\fC [static]\fP"

.PP
Definition at line 22631 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_layout_tab_text = 2131427365\fC [static]\fP"

.PP
Definition at line 22634 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_menu_item_action_area = 2131427366\fC [static]\fP"

.PP
Definition at line 22637 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_navigation_item = 2131427367\fC [static]\fP"

.PP
Definition at line 22640 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_navigation_item_header = 2131427368\fC [static]\fP"

.PP
Definition at line 22643 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_navigation_item_separator = 2131427369\fC [static]\fP"

.PP
Definition at line 22646 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_navigation_item_subheader = 2131427370\fC [static]\fP"

.PP
Definition at line 22649 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_navigation_menu = 2131427371\fC [static]\fP"

.PP
Definition at line 22652 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_navigation_menu_item = 2131427372\fC [static]\fP"

.PP
Definition at line 22655 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_text_input_end_icon = 2131427373\fC [static]\fP"

.PP
Definition at line 22658 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.design_text_input_start_icon = 2131427374\fC [static]\fP"

.PP
Definition at line 22661 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.FallbackTabbarDoNotUse = 2131427375\fC [static]\fP"

.PP
Definition at line 22664 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.FallbackToolbarDoNotUse = 2131427376\fC [static]\fP"

.PP
Definition at line 22667 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.FlyoutContent = 2131427377\fC [static]\fP"

.PP
Definition at line 22670 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.loading = 2131427378\fC [static]\fP"

.PP
Definition at line 22673 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.loadingimage = 2131427379\fC [static]\fP"

.PP
Definition at line 22676 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.loadingprogress = 2131427380\fC [static]\fP"

.PP
Definition at line 22679 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_chip_input_combo = 2131427381\fC [static]\fP"

.PP
Definition at line 22682 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_clock_display = 2131427382\fC [static]\fP"

.PP
Definition at line 22691 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_clock_display_divider = 2131427383\fC [static]\fP"

.PP
Definition at line 22694 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_clock_period_toggle = 2131427384\fC [static]\fP"

.PP
Definition at line 22697 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_clock_period_toggle_land = 2131427385\fC [static]\fP"

.PP
Definition at line 22700 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_clockface_textview = 2131427386\fC [static]\fP"

.PP
Definition at line 22685 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_clockface_view = 2131427387\fC [static]\fP"

.PP
Definition at line 22688 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_radial_view_group = 2131427388\fC [static]\fP"

.PP
Definition at line 22703 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_textinput_timepicker = 2131427389\fC [static]\fP"

.PP
Definition at line 22706 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_time_chip = 2131427390\fC [static]\fP"

.PP
Definition at line 22718 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_time_input = 2131427391\fC [static]\fP"

.PP
Definition at line 22721 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_timepicker = 2131427392\fC [static]\fP"

.PP
Definition at line 22709 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_timepicker_dialog = 2131427393\fC [static]\fP"

.PP
Definition at line 22712 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.material_timepicker_textinput_display = 2131427394\fC [static]\fP"

.PP
Definition at line 22715 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_alert_dialog = 2131427395\fC [static]\fP"

.PP
Definition at line 22724 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_alert_dialog_actions = 2131427396\fC [static]\fP"

.PP
Definition at line 22727 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_alert_dialog_title = 2131427397\fC [static]\fP"

.PP
Definition at line 22730 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_alert_select_dialog_item = 2131427398\fC [static]\fP"

.PP
Definition at line 22733 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_alert_select_dialog_multichoice = 2131427399\fC [static]\fP"

.PP
Definition at line 22736 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_alert_select_dialog_singlechoice = 2131427400\fC [static]\fP"

.PP
Definition at line 22739 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_day = 2131427401\fC [static]\fP"

.PP
Definition at line 22742 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_day_of_week = 2131427402\fC [static]\fP"

.PP
Definition at line 22748 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_days_of_week = 2131427403\fC [static]\fP"

.PP
Definition at line 22745 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_horizontal = 2131427404\fC [static]\fP"

.PP
Definition at line 22751 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_month = 2131427405\fC [static]\fP"

.PP
Definition at line 22754 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_month_labeled = 2131427406\fC [static]\fP"

.PP
Definition at line 22760 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_month_navigation = 2131427407\fC [static]\fP"

.PP
Definition at line 22763 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_months = 2131427408\fC [static]\fP"

.PP
Definition at line 22757 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_vertical = 2131427409\fC [static]\fP"

.PP
Definition at line 22766 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_calendar_year = 2131427410\fC [static]\fP"

.PP
Definition at line 22769 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_layout_snackbar = 2131427411\fC [static]\fP"

.PP
Definition at line 22772 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_layout_snackbar_include = 2131427412\fC [static]\fP"

.PP
Definition at line 22775 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_actions = 2131427413\fC [static]\fP"

.PP
Definition at line 22778 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_dialog = 2131427414\fC [static]\fP"

.PP
Definition at line 22781 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_fullscreen = 2131427415\fC [static]\fP"

.PP
Definition at line 22784 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_header_dialog = 2131427416\fC [static]\fP"

.PP
Definition at line 22787 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_header_fullscreen = 2131427417\fC [static]\fP"

.PP
Definition at line 22790 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_header_selection_text = 2131427418\fC [static]\fP"

.PP
Definition at line 22793 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_header_title_text = 2131427419\fC [static]\fP"

.PP
Definition at line 22796 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_header_toggle = 2131427420\fC [static]\fP"

.PP
Definition at line 22799 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_text_input_date = 2131427421\fC [static]\fP"

.PP
Definition at line 22802 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.mtrl_picker_text_input_date_range = 2131427422\fC [static]\fP"

.PP
Definition at line 22805 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_action = 2131427423\fC [static]\fP"

.PP
Definition at line 22808 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_action_tombstone = 2131427424\fC [static]\fP"

.PP
Definition at line 22811 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_media_action = 2131427425\fC [static]\fP"

.PP
Definition at line 22814 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_media_cancel_action = 2131427426\fC [static]\fP"

.PP
Definition at line 22817 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_big_media = 2131427427\fC [static]\fP"

.PP
Definition at line 22820 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_big_media_custom = 2131427428\fC [static]\fP"

.PP
Definition at line 22823 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_big_media_narrow = 2131427429\fC [static]\fP"

.PP
Definition at line 22826 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_big_media_narrow_custom = 2131427430\fC [static]\fP"

.PP
Definition at line 22829 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_custom_big = 2131427431\fC [static]\fP"

.PP
Definition at line 22832 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_icon_group = 2131427432\fC [static]\fP"

.PP
Definition at line 22835 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_lines_media = 2131427433\fC [static]\fP"

.PP
Definition at line 22838 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_media = 2131427434\fC [static]\fP"

.PP
Definition at line 22841 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_media_custom = 2131427435\fC [static]\fP"

.PP
Definition at line 22844 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_part_chronometer = 2131427436\fC [static]\fP"

.PP
Definition at line 22847 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.notification_template_part_time = 2131427437\fC [static]\fP"

.PP
Definition at line 22850 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.RootLayout = 2131427438\fC [static]\fP"

.PP
Definition at line 22853 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.select_dialog_item_material = 2131427439\fC [static]\fP"

.PP
Definition at line 22856 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.select_dialog_multichoice_material = 2131427440\fC [static]\fP"

.PP
Definition at line 22859 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.select_dialog_singlechoice_material = 2131427441\fC [static]\fP"

.PP
Definition at line 22862 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.ShellContent = 2131427442\fC [static]\fP"

.PP
Definition at line 22865 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.support_simple_spinner_dropdown_item = 2131427443\fC [static]\fP"

.PP
Definition at line 22868 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.Tabbar = 2131427444\fC [static]\fP"

.PP
Definition at line 22871 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_action_chip = 2131427445\fC [static]\fP"

.PP
Definition at line 22874 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_chip_zero_corner_radius = 2131427446\fC [static]\fP"

.PP
Definition at line 22877 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_design_checkbox = 2131427447\fC [static]\fP"

.PP
Definition at line 22880 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_design_radiobutton = 2131427448\fC [static]\fP"

.PP
Definition at line 22883 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_reflow_chipgroup = 2131427449\fC [static]\fP"

.PP
Definition at line 22886 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_toolbar = 2131427450\fC [static]\fP"

.PP
Definition at line 22889 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_toolbar_custom_background = 2131427451\fC [static]\fP"

.PP
Definition at line 22892 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_toolbar_elevation = 2131427452\fC [static]\fP"

.PP
Definition at line 22895 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.test_toolbar_surface = 2131427453\fC [static]\fP"

.PP
Definition at line 22898 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.text_view_with_line_height_from_appearance = 2131427454\fC [static]\fP"

.PP
Definition at line 22904 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.text_view_with_line_height_from_layout = 2131427455\fC [static]\fP"

.PP
Definition at line 22907 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.text_view_with_line_height_from_style = 2131427456\fC [static]\fP"

.PP
Definition at line 22910 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.text_view_with_theme_line_height = 2131427457\fC [static]\fP"

.PP
Definition at line 22913 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.text_view_without_line_height = 2131427458\fC [static]\fP"

.PP
Definition at line 22901 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Layout\&.Toolbar = 2131427459\fC [static]\fP"

.PP
Definition at line 22916 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
