.TH "Application_Green_Quake.Views.LoginSplashPage" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.LoginSplashPage
.SH SYNOPSIS
.br
.PP
.PP
Inherits ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginSplashPage\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file LoginSplashPage\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.LoginSplashPage\&.LoginSplashPage ()"
This function fires when the Login button is clicked\&. It provides the splash screen and then navigates to the main menu right after\&. 
.PP
Definition at line 19 of file LoginSplashPage\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async void Application_Green_Quake\&.Views\&.LoginSplashPage\&.OnAppearing ()\fC [protected]\fP"

.PP
Definition at line 43 of file LoginSplashPage\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
