.TH "Application_Green_Quake.Models.FoodAndDrinkPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.FoodAndDrinkPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBorganicCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBeatAllCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBfoodDeliverCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnoMeatCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBownCoffeeCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBreCoffeeMugCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBsaveLeftOversCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBsteelStrawCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBwaterOverFizzyCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file FoodAndDrinkPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.eatAllCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.foodDeliverCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.noMeatCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.organicCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.ownCoffeeCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.reCoffeeMugCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.saveLeftOversCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.steelStrawCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file FoodAndDrinkPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file FoodAndDrinkPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.FoodAndDrinkPoints\&.waterOverFizzyCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file FoodAndDrinkPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
