.TH "Application_Green_Quake.Models.ShoppingPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.ShoppingPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBclothNapkinCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBclothTowelCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBapplianceCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBproductCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBtoothbrushCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBclothesCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBfoodCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBlocalCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBlooseLeafCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBorganicFoodCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBreusableCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBreBatCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBreBagCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file ShoppingPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.applianceCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.clothesCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.clothNapkinCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.clothTowelCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.foodCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.localCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.looseLeafCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.organicFoodCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.productCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.reBagCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.reBatCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.reusableCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file ShoppingPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.ShoppingPoints\&.toothbrushCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file ShoppingPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.ShoppingPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file ShoppingPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
