.TH "Application Green Quake.Android/obj/Debug/110/android/src/mono/com/microsoft/appcenter/channel Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/110/android/src/mono/com/microsoft/appcenter/channel Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBChannel_GroupListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBChannel_ListenerImplementor\&.java\fP"
.br
.in -1c
