.TH "Application Green Quake.Android/obj/Debug/100/android/src/mono/androidx/core Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/100/android/src/mono/androidx/core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapp\fP"
.br
.ti -1c
.RI "directory \fBos\fP"
.br
.ti -1c
.RI "directory \fBview\fP"
.br
.ti -1c
.RI "directory \fBwidget\fP"
.br
.in -1c
