.TH "Application Green Quake.Android/obj/Debug/110/android/src/xamarin Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/110/android/src/xamarin Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBessentials\fP"
.br
.in -1c
