.TH "Application Green Quake/Views/EcoActions/Outdoors Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/Outdoors Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGoCamping\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPicnic\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlantABush\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlantAFlower\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlantATree\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBScoop\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSetUpFruitGarden\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSetUpHerbGarden\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSetUpVegetableGarden\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBUpBirdfeeder\&.xaml\&.cs\fP"
.br
.in -1c
