.TH "Application Green Quake.Android/obj/Debug/110/android/src/mono/androidx/appcompat/widget Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/110/android/src/mono/androidx/appcompat/widget Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActionMenuView_OnMenuItemClickListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBContentFrameLayout_OnAttachListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBFitWindowsViewGroup_OnFitSystemWindowsListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBMenuItemHoverListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBPopupMenu_OnDismissListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBPopupMenu_OnMenuItemClickListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBSearchView_OnCloseListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBSearchView_OnQueryTextListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBSearchView_OnSuggestionListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBShareActionProvider_OnShareTargetSelectedListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBToolbar_OnMenuItemClickListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBViewStubCompat_OnInflateListenerImplementor\&.java\fP"
.br
.in -1c
