.TH "Application Green Quake/obj/Release/netstandard2.0 Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Release/netstandard2.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBViews\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETStandard,Version=v2\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBApp\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBApplication Green Quake\&.AssemblyInfo\&.cs\fP"
.br
.in -1c
