.TH "Application Green Quake.Android/obj/Release/110/android/src/androidx Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/androidx Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBappcompat\fP"
.br
.ti -1c
.RI "directory \fBbrowser\fP"
.br
.ti -1c
.RI "directory \fBcardview\fP"
.br
.ti -1c
.RI "directory \fBconstraintlayout\fP"
.br
.ti -1c
.RI "directory \fBcoordinatorlayout\fP"
.br
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBdrawerlayout\fP"
.br
.ti -1c
.RI "directory \fBfragment\fP"
.br
.ti -1c
.RI "directory \fBlifecycle\fP"
.br
.ti -1c
.RI "directory \fBmedia\fP"
.br
.ti -1c
.RI "directory \fBrecyclerview\fP"
.br
.ti -1c
.RI "directory \fBsavedstate\fP"
.br
.ti -1c
.RI "directory \fBswiperefreshlayout\fP"
.br
.ti -1c
.RI "directory \fBtransition\fP"
.br
.ti -1c
.RI "directory \fBviewpager2\fP"
.br
.in -1c
