.TH "Application Green Quake.Android/obj/Release/110/android/src/mono/androidx/appcompat/app Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/mono/androidx/appcompat/app Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActionBar_OnMenuVisibilityListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBActionBar_OnNavigationListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBActionBar_TabListenerImplementor\&.java\fP"
.br
.in -1c
