.TH "Application Green Quake/obj/Release/netstandard2.0/Views/EcoActions/Habits Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Release/netstandard2.0/Views/EcoActions/Habits Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBrushingTeeth\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBDishwasherFull\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBShowerInstead\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBTimedShower\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBTurnOffLights\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBUseMatches\&.xaml\&.g\&.cs\fP"
.br
.in -1c
