.TH "Application Green Quake/Views/EcoActions/Community Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/Community Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCreateEnvironmentalGroup\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBDoCommunity\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBDonateItems\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBEnvironmentalGroups\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBShareThisApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSpreadAwareness\&.xaml\&.cs\fP"
.br
.in -1c
