.TH "Application Green Quake/Views Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEcoActions\fP"
.br
.ti -1c
.RI "directory \fBLeaderboardPage\fP"
.br
.ti -1c
.RI "directory \fBProfilePage\fP"
.br
.ti -1c
.RI "directory \fBRefillPage\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBForgotPasswordPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBLoginSplashPage\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainMenu\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSignUpPage\&.xaml\&.cs\fP"
.br
.in -1c
