.TH "Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions/Shopping Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions/Shopping Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClothNapkins\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBClothTowels\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBEcoFreidnlyApplicance\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBEcoFriendlyProduct\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBEcoFriendlyToothbrush\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBEthicalClothes\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBFoodInBulk\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBLocalProduct\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBLooseLeafTea\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBOrganicFood\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBPurchaseReusableWater\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBReBatteries\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBReusableBag\&.xaml\&.g\&.cs\fP"
.br
.in -1c
