.TH "Application Green Quake/Views/EcoActions/Work Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/Work Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBothSidesPaper\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBOffElectronics\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBWorkingRemotely\&.xaml\&.cs\fP"
.br
.in -1c
