.TH "Application Green Quake.Android/obj/Release/110/android/src/crc64396a3fe5f8138e3f Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/crc64396a3fe5f8138e3f Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCustomTabsServiceConnectionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBKeepAliveService\&.java\fP"
.br
.in -1c
