.TH "Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAdvancedPageItems\fP"
.br
.ti -1c
.RI "directory \fBCommunity\fP"
.br
.ti -1c
.RI "directory \fBEcoActionsMenu\fP"
.br
.ti -1c
.RI "directory \fBEcoActionsSubMenu\fP"
.br
.ti -1c
.RI "directory \fBEnergy\fP"
.br
.ti -1c
.RI "directory \fBFoodAndDrink\fP"
.br
.ti -1c
.RI "directory \fBHabits\fP"
.br
.ti -1c
.RI "directory \fBHome\fP"
.br
.ti -1c
.RI "directory \fBOutdoors\fP"
.br
.ti -1c
.RI "directory \fBShopping\fP"
.br
.ti -1c
.RI "directory \fBTravel\fP"
.br
.ti -1c
.RI "directory \fBWaste\fP"
.br
.ti -1c
.RI "directory \fBWater\fP"
.br
.ti -1c
.RI "directory \fBWork\fP"
.br
.in -1c
