.TH "Application Green Quake/Views/EcoActions/Home Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/Home Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAirOutHome\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBNonHarmfulProducts\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBOutsideOnce\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlantIntoHome\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBToiletFlushes\&.xaml\&.cs\fP"
.br
.in -1c
