.TH "Application Green Quake.Android/obj/Release/100 Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/100 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBandroid\fP"
.br
.ti -1c
.RI "directory \fBdesigntime\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMonoAndroid,Version=v10\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.in -1c
