.TH "Application Green Quake.Android/obj/Debug/110/android/src/crc64a0e0a82d0db9a07d Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/110/android/src/crc64a0e0a82d0db9a07d Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccelerometerListener\&.java\fP"
.br
.ti -1c
.RI "file \fBActivityLifecycleContextListener\&.java\fP"
.br
.ti -1c
.RI "file \fBBarometerListener\&.java\fP"
.br
.ti -1c
.RI "file \fBBatteryBroadcastReceiver\&.java\fP"
.br
.ti -1c
.RI "file \fBClipboardChangeListener\&.java\fP"
.br
.ti -1c
.RI "file \fBConnectivityBroadcastReceiver\&.java\fP"
.br
.ti -1c
.RI "file \fBEnergySaverBroadcastReceiver\&.java\fP"
.br
.ti -1c
.RI "file \fBGyroscopeListener\&.java\fP"
.br
.ti -1c
.RI "file \fBIntermediateActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBListener\&.java\fP"
.br
.ti -1c
.RI "file \fBMagnetometerListener\&.java\fP"
.br
.ti -1c
.RI "file \fBOrientationSensorListener\&.java\fP"
.br
.ti -1c
.RI "file \fBSensorListener\&.java\fP"
.br
.ti -1c
.RI "file \fBSingleLocationListener\&.java\fP"
.br
.ti -1c
.RI "file \fBTextToSpeechImplementation\&.java\fP"
.br
.ti -1c
.RI "file \fBWebAuthenticatorCallbackActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBWebAuthenticatorIntermediateActivity\&.java\fP"
.br
.in -1c
