.TH "Application Green Quake.Android/obj/Debug/100/android/src/mono/androidx/fragment/app Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/100/android/src/mono/androidx/fragment/app Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFragmentManager_OnBackStackChangedListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBFragmentOnAttachListenerImplementor\&.java\fP"
.br
.ti -1c
.RI "file \fBFragmentResultListenerImplementor\&.java\fP"
.br
.in -1c
