.TH "Application Green Quake.Android/obj/Release/110/android/compressed_assemblies.arm64-v8a-data.inc" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/compressed_assemblies.arm64-v8a-data.inc
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
