.TH "crc643f46942d9dd1fff9.FormsAnimationDrawable" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.FormsAnimationDrawable
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.graphics\&.drawable\&.AnimationDrawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.AnimationDrawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.AnimationDrawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.AnimationDrawable, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormsAnimationDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisRunning\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "boolean \fBselectDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsAnimationDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisRunning\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "boolean \fBselectDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsAnimationDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisRunning\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "boolean \fBselectDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsAnimationDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisRunning\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "boolean \fBselectDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file FormsAnimationDrawable\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.FormsAnimationDrawable ()"

.PP
Definition at line 22 of file FormsAnimationDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.FormsAnimationDrawable ()"

.PP
Definition at line 22 of file FormsAnimationDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.FormsAnimationDrawable ()"

.PP
Definition at line 22 of file FormsAnimationDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.FormsAnimationDrawable ()"

.PP
Definition at line 22 of file FormsAnimationDrawable\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.isRunning ()"

.PP
Definition at line 30 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.isRunning ()"

.PP
Definition at line 30 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.isRunning ()"

.PP
Definition at line 30 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.isRunning ()"

.PP
Definition at line 30 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 62 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 62 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 62 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 62 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 69 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 69 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 69 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 69 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.selectDrawable (int p0)"

.PP
Definition at line 54 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.selectDrawable (int p0)"

.PP
Definition at line 54 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.selectDrawable (int p0)"

.PP
Definition at line 54 of file FormsAnimationDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.selectDrawable (int p0)"

.PP
Definition at line 54 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.start ()"

.PP
Definition at line 38 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.start ()"

.PP
Definition at line 38 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.start ()"

.PP
Definition at line 38 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.start ()"

.PP
Definition at line 38 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.stop ()"

.PP
Definition at line 46 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.stop ()"

.PP
Definition at line 46 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.stop ()"

.PP
Definition at line 46 of file FormsAnimationDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.stop ()"

.PP
Definition at line 46 of file FormsAnimationDrawable\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.FormsAnimationDrawable\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file FormsAnimationDrawable\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
