.TH "crc64435a5ac349fa9fda" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64435a5ac349fa9fda
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivityLifecycleContextListener\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
