.TH "crc644103bb497e895a1b.InputLayoutBorder" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc644103bb497e895a1b.InputLayoutBorder
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.view\&.View, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputLayoutBorder\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBInputLayoutBorder\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBInputLayoutBorder\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBInputLayoutBorder\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file InputLayoutBorder\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc644103bb497e895a1b\&.InputLayoutBorder\&.InputLayoutBorder (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file InputLayoutBorder\&.java\&.
.SS "crc644103bb497e895a1b\&.InputLayoutBorder\&.InputLayoutBorder (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file InputLayoutBorder\&.java\&.
.SS "crc644103bb497e895a1b\&.InputLayoutBorder\&.InputLayoutBorder (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file InputLayoutBorder\&.java\&.
.SS "crc644103bb497e895a1b\&.InputLayoutBorder\&.InputLayoutBorder (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file InputLayoutBorder\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc644103bb497e895a1b\&.InputLayoutBorder\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file InputLayoutBorder\&.java\&.
.SS "void crc644103bb497e895a1b\&.InputLayoutBorder\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file InputLayoutBorder\&.java\&.
.SS "void crc644103bb497e895a1b\&.InputLayoutBorder\&.onDraw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 51 of file InputLayoutBorder\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String crc644103bb497e895a1b\&.InputLayoutBorder\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file InputLayoutBorder\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
