.TH "crc64a25b61d9f8ee364f" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a25b61d9f8ee364f
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFloatArrayEvaluator\fP"
.br
.ti -1c
.RI "class \fBRectEvaluator\fP"
.br
.ti -1c
.RI "class \fBTransitionUtils\fP"
.br
.ti -1c
.RI "class \fBTransitionUtils_MatrixEvaluator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
