.TH "crc643f46942d9dd1fff9.ShellSearchViewAdapter" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.ShellSearchViewAdapter
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.widget\&.BaseAdapter, mono\&.android\&.IGCUserPeer, android\&.widget\&.Filterable, android\&.widget\&.BaseAdapter, mono\&.android\&.IGCUserPeer, android\&.widget\&.Filterable, android\&.widget\&.BaseAdapter, mono\&.android\&.IGCUserPeer, android\&.widget\&.Filterable, android\&.widget\&.BaseAdapter, mono\&.android\&.IGCUserPeer, and android\&.widget\&.Filterable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShellSearchViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "android\&.view\&.View \fBgetView\fP (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"
.br
.ti -1c
.RI "android\&.widget\&.Filter \fBgetFilter\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "android\&.view\&.View \fBgetView\fP (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"
.br
.ti -1c
.RI "android\&.widget\&.Filter \fBgetFilter\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "android\&.view\&.View \fBgetView\fP (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"
.br
.ti -1c
.RI "android\&.widget\&.Filter \fBgetFilter\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "android\&.view\&.View \fBgetView\fP (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"
.br
.ti -1c
.RI "android\&.widget\&.Filter \fBgetFilter\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ShellSearchViewAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.ShellSearchViewAdapter ()"

.PP
Definition at line 24 of file ShellSearchViewAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.ShellSearchViewAdapter ()"

.PP
Definition at line 24 of file ShellSearchViewAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.ShellSearchViewAdapter ()"

.PP
Definition at line 24 of file ShellSearchViewAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.ShellSearchViewAdapter ()"

.PP
Definition at line 24 of file ShellSearchViewAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getCount ()"

.PP
Definition at line 32 of file ShellSearchViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getCount ()"

.PP
Definition at line 32 of file ShellSearchViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getCount ()"

.PP
Definition at line 32 of file ShellSearchViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getCount ()"

.PP
Definition at line 32 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.widget\&.Filter crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getFilter ()"

.PP
Definition at line 64 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.widget\&.Filter crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getFilter ()"

.PP
Definition at line 64 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.widget\&.Filter crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getFilter ()"

.PP
Definition at line 64 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.widget\&.Filter crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getFilter ()"

.PP
Definition at line 64 of file ShellSearchViewAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItem (int p0)"

.PP
Definition at line 40 of file ShellSearchViewAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItem (int p0)"

.PP
Definition at line 40 of file ShellSearchViewAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItem (int p0)"

.PP
Definition at line 40 of file ShellSearchViewAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItem (int p0)"

.PP
Definition at line 40 of file ShellSearchViewAdapter\&.java\&.
.SS "long crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItemId (int p0)"

.PP
Definition at line 48 of file ShellSearchViewAdapter\&.java\&.
.SS "long crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItemId (int p0)"

.PP
Definition at line 48 of file ShellSearchViewAdapter\&.java\&.
.SS "long crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItemId (int p0)"

.PP
Definition at line 48 of file ShellSearchViewAdapter\&.java\&.
.SS "long crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getItemId (int p0)"

.PP
Definition at line 48 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getView (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"

.PP
Definition at line 56 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getView (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"

.PP
Definition at line 56 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getView (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"

.PP
Definition at line 56 of file ShellSearchViewAdapter\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.getView (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"

.PP
Definition at line 56 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file ShellSearchViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file ShellSearchViewAdapter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.ShellSearchViewAdapter\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file ShellSearchViewAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
