.TH "crc64a0e0a82d0db9a07d.SingleLocationListener" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a0e0a82d0db9a07d.SingleLocationListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.location\&.LocationListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.location\&.LocationListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.location\&.LocationListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and android\&.location\&.LocationListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleLocationListener\fP ()"
.br
.ti -1c
.RI "void \fBonLocationChanged\fP (android\&.location\&.Location p0)"
.br
.ti -1c
.RI "void \fBonProviderDisabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonProviderEnabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonStatusChanged\fP (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSingleLocationListener\fP ()"
.br
.ti -1c
.RI "void \fBonLocationChanged\fP (android\&.location\&.Location p0)"
.br
.ti -1c
.RI "void \fBonProviderDisabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonProviderEnabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonStatusChanged\fP (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSingleLocationListener\fP ()"
.br
.ti -1c
.RI "void \fBonLocationChanged\fP (android\&.location\&.Location p0)"
.br
.ti -1c
.RI "void \fBonProviderDisabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonProviderEnabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonStatusChanged\fP (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSingleLocationListener\fP ()"
.br
.ti -1c
.RI "void \fBonLocationChanged\fP (android\&.location\&.Location p0)"
.br
.ti -1c
.RI "void \fBonProviderDisabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonProviderEnabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonStatusChanged\fP (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file SingleLocationListener\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.SingleLocationListener ()"

.PP
Definition at line 23 of file SingleLocationListener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.SingleLocationListener ()"

.PP
Definition at line 23 of file SingleLocationListener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.SingleLocationListener ()"

.PP
Definition at line 23 of file SingleLocationListener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.SingleLocationListener ()"

.PP
Definition at line 23 of file SingleLocationListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 63 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 63 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 63 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 63 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidClearReferences ()"

.PP
Definition at line 70 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidClearReferences ()"

.PP
Definition at line 70 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidClearReferences ()"

.PP
Definition at line 70 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.monodroidClearReferences ()"

.PP
Definition at line 70 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onLocationChanged (android\&.location\&.Location p0)"

.PP
Definition at line 31 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onLocationChanged (android\&.location\&.Location p0)"

.PP
Definition at line 31 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onLocationChanged (android\&.location\&.Location p0)"

.PP
Definition at line 31 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onLocationChanged (android\&.location\&.Location p0)"

.PP
Definition at line 31 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderDisabled (java\&.lang\&.String p0)"

.PP
Definition at line 39 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderDisabled (java\&.lang\&.String p0)"

.PP
Definition at line 39 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderDisabled (java\&.lang\&.String p0)"

.PP
Definition at line 39 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderDisabled (java\&.lang\&.String p0)"

.PP
Definition at line 39 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderEnabled (java\&.lang\&.String p0)"

.PP
Definition at line 47 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderEnabled (java\&.lang\&.String p0)"

.PP
Definition at line 47 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderEnabled (java\&.lang\&.String p0)"

.PP
Definition at line 47 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onProviderEnabled (java\&.lang\&.String p0)"

.PP
Definition at line 47 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onStatusChanged (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"

.PP
Definition at line 55 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onStatusChanged (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"

.PP
Definition at line 55 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onStatusChanged (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"

.PP
Definition at line 55 of file SingleLocationListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.onStatusChanged (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"

.PP
Definition at line 55 of file SingleLocationListener\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64a0e0a82d0db9a07d\&.SingleLocationListener\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file SingleLocationListener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
