.TH "crc64a0e0a82d0db9a07d" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a0e0a82d0db9a07d
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccelerometerListener\fP"
.br
.ti -1c
.RI "class \fBActivityLifecycleContextListener\fP"
.br
.ti -1c
.RI "class \fBBarometerListener\fP"
.br
.ti -1c
.RI "class \fBBatteryBroadcastReceiver\fP"
.br
.ti -1c
.RI "class \fBClipboardChangeListener\fP"
.br
.ti -1c
.RI "class \fBConnectivityBroadcastReceiver\fP"
.br
.ti -1c
.RI "class \fBEnergySaverBroadcastReceiver\fP"
.br
.ti -1c
.RI "class \fBGyroscopeListener\fP"
.br
.ti -1c
.RI "class \fBIntermediateActivity\fP"
.br
.ti -1c
.RI "class \fBListener\fP"
.br
.ti -1c
.RI "class \fBMagnetometerListener\fP"
.br
.ti -1c
.RI "class \fBOrientationSensorListener\fP"
.br
.ti -1c
.RI "class \fBSensorListener\fP"
.br
.ti -1c
.RI "class \fBSingleLocationListener\fP"
.br
.ti -1c
.RI "class \fBTextToSpeechImplementation\fP"
.br
.ti -1c
.RI "class \fBWebAuthenticatorCallbackActivity\fP"
.br
.ti -1c
.RI "class \fBWebAuthenticatorIntermediateActivity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
