.TH "crc643f46942d9dd1fff9.InnerGestureListener" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.InnerGestureListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.view\&.GestureDetector\&.OnGestureListener, android\&.view\&.GestureDetector\&.OnDoubleTapListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.view\&.GestureDetector\&.OnGestureListener, android\&.view\&.GestureDetector\&.OnDoubleTapListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.view\&.GestureDetector\&.OnGestureListener, android\&.view\&.GestureDetector\&.OnDoubleTapListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.view\&.GestureDetector\&.OnGestureListener, and android\&.view\&.GestureDetector\&.OnDoubleTapListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInnerGestureListener\fP ()"
.br
.ti -1c
.RI "boolean \fBonDown\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonFling\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonLongPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonScroll\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonShowPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapUp\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTap\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTapEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapConfirmed\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBInnerGestureListener\fP ()"
.br
.ti -1c
.RI "boolean \fBonDown\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonFling\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonLongPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonScroll\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonShowPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapUp\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTap\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTapEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapConfirmed\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBInnerGestureListener\fP ()"
.br
.ti -1c
.RI "boolean \fBonDown\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonFling\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonLongPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonScroll\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonShowPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapUp\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTap\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTapEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapConfirmed\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBInnerGestureListener\fP ()"
.br
.ti -1c
.RI "boolean \fBonDown\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonFling\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonLongPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonScroll\fP (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBonShowPress\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapUp\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTap\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonDoubleTapEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonSingleTapConfirmed\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file InnerGestureListener\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.InnerGestureListener\&.InnerGestureListener ()"

.PP
Definition at line 29 of file InnerGestureListener\&.java\&.
.SS "crc643f46942d9dd1fff9\&.InnerGestureListener\&.InnerGestureListener ()"

.PP
Definition at line 29 of file InnerGestureListener\&.java\&.
.SS "crc643f46942d9dd1fff9\&.InnerGestureListener\&.InnerGestureListener ()"

.PP
Definition at line 29 of file InnerGestureListener\&.java\&.
.SS "crc643f46942d9dd1fff9\&.InnerGestureListener\&.InnerGestureListener ()"

.PP
Definition at line 29 of file InnerGestureListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 109 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 109 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 109 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 109 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidClearReferences ()"

.PP
Definition at line 116 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidClearReferences ()"

.PP
Definition at line 116 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidClearReferences ()"

.PP
Definition at line 116 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.monodroidClearReferences ()"

.PP
Definition at line 116 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTap (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 85 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTap (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 85 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTap (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 85 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTap (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 85 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTapEvent (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 93 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTapEvent (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 93 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTapEvent (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 93 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDoubleTapEvent (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 93 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDown (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 37 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDown (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 37 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDown (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 37 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onDown (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 37 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onFling (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 45 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onFling (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 45 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onFling (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 45 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onFling (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 45 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onLongPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 53 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onLongPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 53 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onLongPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 53 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onLongPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 53 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onScroll (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 61 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onScroll (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 61 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onScroll (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 61 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onScroll (android\&.view\&.MotionEvent p0, android\&.view\&.MotionEvent p1, float p2, float p3)"

.PP
Definition at line 61 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onShowPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 69 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onShowPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 69 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onShowPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 69 of file InnerGestureListener\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.InnerGestureListener\&.onShowPress (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 69 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapConfirmed (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 101 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapConfirmed (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 101 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapConfirmed (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 101 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapConfirmed (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 101 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapUp (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 77 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapUp (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 77 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapUp (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 77 of file InnerGestureListener\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.InnerGestureListener\&.onSingleTapUp (android\&.view\&.MotionEvent p0)"

.PP
Definition at line 77 of file InnerGestureListener\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.InnerGestureListener\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 12 of file InnerGestureListener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
