.TH "crc643f46942d9dd1fff9.CollectionViewRenderer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.CollectionViewRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBCollectionViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file CollectionViewRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file CollectionViewRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.CollectionViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file CollectionViewRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 42 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 42 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 42 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 42 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 49 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 49 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 49 of file CollectionViewRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.GroupableItemsViewRenderer_3\fP\&.
.PP
Definition at line 49 of file CollectionViewRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.CollectionViewRenderer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file CollectionViewRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
