.TH "crc643f46942d9dd1fff9.EmptyViewAdapter" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.EmptyViewAdapter
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.recyclerview\&.widget\&.RecyclerView\&.Adapter, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.RecyclerView\&.Adapter, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.RecyclerView\&.Adapter, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.RecyclerView\&.Adapter, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmptyViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetItemCount\fP ()"
.br
.ti -1c
.RI "void \fBonViewRecycled\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"
.br
.ti -1c
.RI "void \fBonBindViewHolder\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"
.br
.ti -1c
.RI "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder \fBonCreateViewHolder\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEmptyViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetItemCount\fP ()"
.br
.ti -1c
.RI "void \fBonViewRecycled\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"
.br
.ti -1c
.RI "void \fBonBindViewHolder\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"
.br
.ti -1c
.RI "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder \fBonCreateViewHolder\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEmptyViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetItemCount\fP ()"
.br
.ti -1c
.RI "void \fBonViewRecycled\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"
.br
.ti -1c
.RI "void \fBonBindViewHolder\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"
.br
.ti -1c
.RI "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder \fBonCreateViewHolder\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEmptyViewAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetItemCount\fP ()"
.br
.ti -1c
.RI "void \fBonViewRecycled\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"
.br
.ti -1c
.RI "void \fBonBindViewHolder\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"
.br
.ti -1c
.RI "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder \fBonCreateViewHolder\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file EmptyViewAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.EmptyViewAdapter ()"

.PP
Definition at line 23 of file EmptyViewAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.EmptyViewAdapter ()"

.PP
Definition at line 23 of file EmptyViewAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.EmptyViewAdapter ()"

.PP
Definition at line 23 of file EmptyViewAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.EmptyViewAdapter ()"

.PP
Definition at line 23 of file EmptyViewAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemCount ()"

.PP
Definition at line 31 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemCount ()"

.PP
Definition at line 31 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemCount ()"

.PP
Definition at line 31 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemCount ()"

.PP
Definition at line 31 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemViewType (int p0)"

.PP
Definition at line 63 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemViewType (int p0)"

.PP
Definition at line 63 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemViewType (int p0)"

.PP
Definition at line 63 of file EmptyViewAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.getItemViewType (int p0)"

.PP
Definition at line 63 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 71 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 71 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 71 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 71 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 78 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 78 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 78 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 78 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onBindViewHolder (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"

.PP
Definition at line 47 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onBindViewHolder (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"

.PP
Definition at line 47 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onBindViewHolder (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"

.PP
Definition at line 47 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onBindViewHolder (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0, int p1)"

.PP
Definition at line 47 of file EmptyViewAdapter\&.java\&.
.SS "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onCreateViewHolder (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 55 of file EmptyViewAdapter\&.java\&.
.SS "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onCreateViewHolder (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 55 of file EmptyViewAdapter\&.java\&.
.SS "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onCreateViewHolder (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 55 of file EmptyViewAdapter\&.java\&.
.SS "androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onCreateViewHolder (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 55 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onViewRecycled (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"

.PP
Definition at line 39 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onViewRecycled (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"

.PP
Definition at line 39 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onViewRecycled (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"

.PP
Definition at line 39 of file EmptyViewAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.onViewRecycled (androidx\&.recyclerview\&.widget\&.RecyclerView\&.ViewHolder p0)"

.PP
Definition at line 39 of file EmptyViewAdapter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.EmptyViewAdapter\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file EmptyViewAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
