.TH "crc643f46942d9dd1fff9.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.widget\&.LinearLayout, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfocusSearch\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfocusSearch\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfocusSearch\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfocusSearch\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.focusSearch (int p0)"

.PP
Definition at line 51 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.focusSearch (int p0)"

.PP
Definition at line 51 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.focusSearch (int p0)"

.PP
Definition at line 51 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.focusSearch (int p0)"

.PP
Definition at line 51 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file ShellFlyoutRecyclerAdapter_LinearLayoutWithFocus\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
