.TH "crc643f46942d9dd1fff9.EndSnapHelper" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.EndSnapHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEndSnapHelper\fP ()"
.br
.ti -1c
.RI "int[] \fBcalculateDistanceToFinalSnap\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEndSnapHelper\fP ()"
.br
.ti -1c
.RI "int[] \fBcalculateDistanceToFinalSnap\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEndSnapHelper\fP ()"
.br
.ti -1c
.RI "int[] \fBcalculateDistanceToFinalSnap\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEndSnapHelper\fP ()"
.br
.ti -1c
.RI "int[] \fBcalculateDistanceToFinalSnap\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file EndSnapHelper\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.EndSnapHelper\&.EndSnapHelper ()"

.PP
Definition at line 20 of file EndSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EndSnapHelper\&.EndSnapHelper ()"

.PP
Definition at line 20 of file EndSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EndSnapHelper\&.EndSnapHelper ()"

.PP
Definition at line 20 of file EndSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EndSnapHelper\&.EndSnapHelper ()"

.PP
Definition at line 20 of file EndSnapHelper\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int [] crc643f46942d9dd1fff9\&.EndSnapHelper\&.calculateDistanceToFinalSnap (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file EndSnapHelper\&.java\&.
.SS "int [] crc643f46942d9dd1fff9\&.EndSnapHelper\&.calculateDistanceToFinalSnap (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file EndSnapHelper\&.java\&.
.SS "int [] crc643f46942d9dd1fff9\&.EndSnapHelper\&.calculateDistanceToFinalSnap (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file EndSnapHelper\&.java\&.
.SS "int [] crc643f46942d9dd1fff9\&.EndSnapHelper\&.calculateDistanceToFinalSnap (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file EndSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.EndSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 36 of file EndSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.EndSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 36 of file EndSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.EndSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 36 of file EndSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.EndSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 36 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 44 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 44 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 44 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 44 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 51 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 51 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 51 of file EndSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EndSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.EdgeSnapHelper\fP\&.
.PP
Definition at line 51 of file EndSnapHelper\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.EndSnapHelper\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file EndSnapHelper\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
