.TH "crc64a0e0a82d0db9a07d.TextToSpeechImplementation" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a0e0a82d0db9a07d.TextToSpeechImplementation
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.speech\&.tts\&.TextToSpeech\&.OnInitListener, android\&.speech\&.tts\&.TextToSpeech\&.OnUtteranceCompletedListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.speech\&.tts\&.TextToSpeech\&.OnInitListener, android\&.speech\&.tts\&.TextToSpeech\&.OnUtteranceCompletedListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.speech\&.tts\&.TextToSpeech\&.OnInitListener, android\&.speech\&.tts\&.TextToSpeech\&.OnUtteranceCompletedListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.speech\&.tts\&.TextToSpeech\&.OnInitListener, and android\&.speech\&.tts\&.TextToSpeech\&.OnUtteranceCompletedListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextToSpeechImplementation\fP ()"
.br
.ti -1c
.RI "void \fBonInit\fP (int p0)"
.br
.ti -1c
.RI "void \fBonUtteranceCompleted\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBTextToSpeechImplementation\fP ()"
.br
.ti -1c
.RI "void \fBonInit\fP (int p0)"
.br
.ti -1c
.RI "void \fBonUtteranceCompleted\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBTextToSpeechImplementation\fP ()"
.br
.ti -1c
.RI "void \fBonInit\fP (int p0)"
.br
.ti -1c
.RI "void \fBonUtteranceCompleted\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBTextToSpeechImplementation\fP ()"
.br
.ti -1c
.RI "void \fBonInit\fP (int p0)"
.br
.ti -1c
.RI "void \fBonUtteranceCompleted\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TextToSpeechImplementation\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.TextToSpeechImplementation ()"

.PP
Definition at line 22 of file TextToSpeechImplementation\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.TextToSpeechImplementation ()"

.PP
Definition at line 22 of file TextToSpeechImplementation\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.TextToSpeechImplementation ()"

.PP
Definition at line 22 of file TextToSpeechImplementation\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.TextToSpeechImplementation ()"

.PP
Definition at line 22 of file TextToSpeechImplementation\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onInit (int p0)"

.PP
Definition at line 30 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onInit (int p0)"

.PP
Definition at line 30 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onInit (int p0)"

.PP
Definition at line 30 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onInit (int p0)"

.PP
Definition at line 30 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onUtteranceCompleted (java\&.lang\&.String p0)"

.PP
Definition at line 38 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onUtteranceCompleted (java\&.lang\&.String p0)"

.PP
Definition at line 38 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onUtteranceCompleted (java\&.lang\&.String p0)"

.PP
Definition at line 38 of file TextToSpeechImplementation\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.onUtteranceCompleted (java\&.lang\&.String p0)"

.PP
Definition at line 38 of file TextToSpeechImplementation\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64a0e0a82d0db9a07d\&.TextToSpeechImplementation\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 12 of file TextToSpeechImplementation\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
