.TH "crc64f606ab658bf2774f.SfShimmerRenderer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64f606ab658bf2774f.SfShimmerRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.ViewRenderer\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSfShimmerRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSfShimmerRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSfShimmerRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBdispatchDraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file SfShimmerRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64f606ab658bf2774f\&.SfShimmerRenderer\&.SfShimmerRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 20 of file SfShimmerRenderer\&.java\&.
.SS "crc64f606ab658bf2774f\&.SfShimmerRenderer\&.SfShimmerRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 28 of file SfShimmerRenderer\&.java\&.
.SS "crc64f606ab658bf2774f\&.SfShimmerRenderer\&.SfShimmerRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 36 of file SfShimmerRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64f606ab658bf2774f\&.SfShimmerRenderer\&.dispatchDraw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 52 of file SfShimmerRenderer\&.java\&.
.SS "void crc64f606ab658bf2774f\&.SfShimmerRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer\fP\&.
.PP
Definition at line 60 of file SfShimmerRenderer\&.java\&.
.SS "void crc64f606ab658bf2774f\&.SfShimmerRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer\fP\&.
.PP
Definition at line 67 of file SfShimmerRenderer\&.java\&.
.SS "void crc64f606ab658bf2774f\&.SfShimmerRenderer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 44 of file SfShimmerRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String crc64f606ab658bf2774f\&.SfShimmerRenderer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file SfShimmerRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
