.TH "crc646957603ea1820544.MediaPickerActivity" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc646957603ea1820544.MediaPickerActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, android\&.media\&.MediaScannerConnection\&.OnScanCompletedListener, android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, android\&.media\&.MediaScannerConnection\&.OnScanCompletedListener, android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, android\&.media\&.MediaScannerConnection\&.OnScanCompletedListener, android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, and android\&.media\&.MediaScannerConnection\&.OnScanCompletedListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMediaPickerActivity\fP ()"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonScanCompleted\fP (java\&.lang\&.String p0, android\&.net\&.Uri p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBMediaPickerActivity\fP ()"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonScanCompleted\fP (java\&.lang\&.String p0, android\&.net\&.Uri p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBMediaPickerActivity\fP ()"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonScanCompleted\fP (java\&.lang\&.String p0, android\&.net\&.Uri p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBMediaPickerActivity\fP ()"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonScanCompleted\fP (java\&.lang\&.String p0, android\&.net\&.Uri p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file MediaPickerActivity\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc646957603ea1820544\&.MediaPickerActivity\&.MediaPickerActivity ()"

.PP
Definition at line 24 of file MediaPickerActivity\&.java\&.
.SS "crc646957603ea1820544\&.MediaPickerActivity\&.MediaPickerActivity ()"

.PP
Definition at line 24 of file MediaPickerActivity\&.java\&.
.SS "crc646957603ea1820544\&.MediaPickerActivity\&.MediaPickerActivity ()"

.PP
Definition at line 24 of file MediaPickerActivity\&.java\&.
.SS "crc646957603ea1820544\&.MediaPickerActivity\&.MediaPickerActivity ()"

.PP
Definition at line 24 of file MediaPickerActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 72 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.monodroidClearReferences ()"

.PP
Definition at line 79 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 48 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 48 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 48 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 48 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 40 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 40 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 40 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 40 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onDestroy ()"

.PP
Definition at line 56 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onDestroy ()"

.PP
Definition at line 56 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onDestroy ()"

.PP
Definition at line 56 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onDestroy ()"

.PP
Definition at line 56 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onSaveInstanceState (android\&.os\&.Bundle p0)"

.PP
Definition at line 32 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onSaveInstanceState (android\&.os\&.Bundle p0)"

.PP
Definition at line 32 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onSaveInstanceState (android\&.os\&.Bundle p0)"

.PP
Definition at line 32 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onSaveInstanceState (android\&.os\&.Bundle p0)"

.PP
Definition at line 32 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onScanCompleted (java\&.lang\&.String p0, android\&.net\&.Uri p1)"

.PP
Definition at line 64 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onScanCompleted (java\&.lang\&.String p0, android\&.net\&.Uri p1)"

.PP
Definition at line 64 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onScanCompleted (java\&.lang\&.String p0, android\&.net\&.Uri p1)"

.PP
Definition at line 64 of file MediaPickerActivity\&.java\&.
.SS "void crc646957603ea1820544\&.MediaPickerActivity\&.onScanCompleted (java\&.lang\&.String p0, android\&.net\&.Uri p1)"

.PP
Definition at line 64 of file MediaPickerActivity\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc646957603ea1820544\&.MediaPickerActivity\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file MediaPickerActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
