.TH "crc64350623dcb797cc38.AndroidHttpClientAdapter" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64350623dcb797cc38.AndroidHttpClientAdapter
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.microsoft\&.appcenter\&.http\&.HttpClient, java\&.io\&.Closeable, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.microsoft\&.appcenter\&.http\&.HttpClient, and java\&.io\&.Closeable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndroidHttpClientAdapter\fP ()"
.br
.ti -1c
.RI "com\&.microsoft\&.appcenter\&.http\&.ServiceCall \fBcallAsync\fP (java\&.lang\&.String p0, java\&.lang\&.String p1, java\&.util\&.Map p2, com\&.microsoft\&.appcenter\&.http\&.HttpClient\&.CallTemplate p3, com\&.microsoft\&.appcenter\&.http\&.ServiceCallback p4)"
.br
.ti -1c
.RI "void \fBreopen\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBAndroidHttpClientAdapter\fP ()"
.br
.ti -1c
.RI "com\&.microsoft\&.appcenter\&.http\&.ServiceCall \fBcallAsync\fP (java\&.lang\&.String p0, java\&.lang\&.String p1, java\&.util\&.Map p2, com\&.microsoft\&.appcenter\&.http\&.HttpClient\&.CallTemplate p3, com\&.microsoft\&.appcenter\&.http\&.ServiceCallback p4)"
.br
.ti -1c
.RI "void \fBreopen\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file AndroidHttpClientAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.AndroidHttpClientAdapter ()"

.PP
Definition at line 23 of file AndroidHttpClientAdapter\&.java\&.
.SS "crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.AndroidHttpClientAdapter ()"

.PP
Definition at line 23 of file AndroidHttpClientAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "com\&.microsoft\&.appcenter\&.http\&.ServiceCall crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.callAsync (java\&.lang\&.String p0, java\&.lang\&.String p1, java\&.util\&.Map p2, com\&.microsoft\&.appcenter\&.http\&.HttpClient\&.CallTemplate p3, com\&.microsoft\&.appcenter\&.http\&.ServiceCallback p4)"

.PP
Definition at line 31 of file AndroidHttpClientAdapter\&.java\&.
.SS "com\&.microsoft\&.appcenter\&.http\&.ServiceCall crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.callAsync (java\&.lang\&.String p0, java\&.lang\&.String p1, java\&.util\&.Map p2, com\&.microsoft\&.appcenter\&.http\&.HttpClient\&.CallTemplate p3, com\&.microsoft\&.appcenter\&.http\&.ServiceCallback p4)"

.PP
Definition at line 31 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.close ()"

.PP
Definition at line 47 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.close ()"

.PP
Definition at line 47 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 55 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 55 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 62 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 62 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.reopen ()"

.PP
Definition at line 39 of file AndroidHttpClientAdapter\&.java\&.
.SS "void crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.reopen ()"

.PP
Definition at line 39 of file AndroidHttpClientAdapter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64350623dcb797cc38\&.AndroidHttpClientAdapter\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 12 of file AndroidHttpClientAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
