.TH "crc643f46942d9dd1fff9.CarouselPageAdapter" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.CarouselPageAdapter
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.viewpager\&.widget\&.PagerAdapter, mono\&.android\&.IGCUserPeer, androidx\&.viewpager\&.widget\&.ViewPager\&.OnPageChangeListener, androidx\&.viewpager\&.widget\&.PagerAdapter, mono\&.android\&.IGCUserPeer, androidx\&.viewpager\&.widget\&.ViewPager\&.OnPageChangeListener, androidx\&.viewpager\&.widget\&.PagerAdapter, mono\&.android\&.IGCUserPeer, androidx\&.viewpager\&.widget\&.ViewPager\&.OnPageChangeListener, androidx\&.viewpager\&.widget\&.PagerAdapter, mono\&.android\&.IGCUserPeer, and androidx\&.viewpager\&.widget\&.ViewPager\&.OnPageChangeListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCarouselPageAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "void \fBdestroyItem\fP (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBinstantiateItem\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "boolean \fBisViewFromObject\fP (android\&.view\&.View p0, java\&.lang\&.Object p1)"
.br
.ti -1c
.RI "void \fBonPageScrollStateChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBonPageScrolled\fP (int p0, float p1, int p2)"
.br
.ti -1c
.RI "void \fBonPageSelected\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCarouselPageAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "void \fBdestroyItem\fP (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBinstantiateItem\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "boolean \fBisViewFromObject\fP (android\&.view\&.View p0, java\&.lang\&.Object p1)"
.br
.ti -1c
.RI "void \fBonPageScrollStateChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBonPageScrolled\fP (int p0, float p1, int p2)"
.br
.ti -1c
.RI "void \fBonPageSelected\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCarouselPageAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "void \fBdestroyItem\fP (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBinstantiateItem\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "boolean \fBisViewFromObject\fP (android\&.view\&.View p0, java\&.lang\&.Object p1)"
.br
.ti -1c
.RI "void \fBonPageScrollStateChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBonPageScrolled\fP (int p0, float p1, int p2)"
.br
.ti -1c
.RI "void \fBonPageSelected\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCarouselPageAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "void \fBdestroyItem\fP (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBinstantiateItem\fP (android\&.view\&.ViewGroup p0, int p1)"
.br
.ti -1c
.RI "boolean \fBisViewFromObject\fP (android\&.view\&.View p0, java\&.lang\&.Object p1)"
.br
.ti -1c
.RI "void \fBonPageScrollStateChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBonPageScrolled\fP (int p0, float p1, int p2)"
.br
.ti -1c
.RI "void \fBonPageSelected\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file CarouselPageAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.CarouselPageAdapter ()"

.PP
Definition at line 27 of file CarouselPageAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.CarouselPageAdapter ()"

.PP
Definition at line 27 of file CarouselPageAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.CarouselPageAdapter ()"

.PP
Definition at line 27 of file CarouselPageAdapter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.CarouselPageAdapter ()"

.PP
Definition at line 27 of file CarouselPageAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.destroyItem (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"

.PP
Definition at line 43 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.destroyItem (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"

.PP
Definition at line 43 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.destroyItem (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"

.PP
Definition at line 43 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.destroyItem (android\&.view\&.ViewGroup p0, int p1, java\&.lang\&.Object p2)"

.PP
Definition at line 43 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getCount ()"

.PP
Definition at line 35 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getCount ()"

.PP
Definition at line 35 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getCount ()"

.PP
Definition at line 35 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getCount ()"

.PP
Definition at line 35 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 51 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 51 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 51 of file CarouselPageAdapter\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 51 of file CarouselPageAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.instantiateItem (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 59 of file CarouselPageAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.instantiateItem (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 59 of file CarouselPageAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.instantiateItem (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 59 of file CarouselPageAdapter\&.java\&.
.SS "java\&.lang\&.Object crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.instantiateItem (android\&.view\&.ViewGroup p0, int p1)"

.PP
Definition at line 59 of file CarouselPageAdapter\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.isViewFromObject (android\&.view\&.View p0, java\&.lang\&.Object p1)"

.PP
Definition at line 67 of file CarouselPageAdapter\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.isViewFromObject (android\&.view\&.View p0, java\&.lang\&.Object p1)"

.PP
Definition at line 67 of file CarouselPageAdapter\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.isViewFromObject (android\&.view\&.View p0, java\&.lang\&.Object p1)"

.PP
Definition at line 67 of file CarouselPageAdapter\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.isViewFromObject (android\&.view\&.View p0, java\&.lang\&.Object p1)"

.PP
Definition at line 67 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrolled (int p0, float p1, int p2)"

.PP
Definition at line 83 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrolled (int p0, float p1, int p2)"

.PP
Definition at line 83 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrolled (int p0, float p1, int p2)"

.PP
Definition at line 83 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrolled (int p0, float p1, int p2)"

.PP
Definition at line 83 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrollStateChanged (int p0)"

.PP
Definition at line 75 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrollStateChanged (int p0)"

.PP
Definition at line 75 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrollStateChanged (int p0)"

.PP
Definition at line 75 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageScrollStateChanged (int p0)"

.PP
Definition at line 75 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageSelected (int p0)"

.PP
Definition at line 91 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageSelected (int p0)"

.PP
Definition at line 91 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageSelected (int p0)"

.PP
Definition at line 91 of file CarouselPageAdapter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.onPageSelected (int p0)"

.PP
Definition at line 91 of file CarouselPageAdapter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.CarouselPageAdapter\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file CarouselPageAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
