.TH "crc64d32ffa835eadac0e.DelegateSnapshotReadyCallback" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64d32ffa835eadac0e.DelegateSnapshotReadyCallback
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.SnapshotReadyCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.SnapshotReadyCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.SnapshotReadyCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.SnapshotReadyCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegateSnapshotReadyCallback\fP ()"
.br
.ti -1c
.RI "void \fBonSnapshotReady\fP (android\&.graphics\&.Bitmap p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDelegateSnapshotReadyCallback\fP ()"
.br
.ti -1c
.RI "void \fBonSnapshotReady\fP (android\&.graphics\&.Bitmap p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDelegateSnapshotReadyCallback\fP ()"
.br
.ti -1c
.RI "void \fBonSnapshotReady\fP (android\&.graphics\&.Bitmap p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDelegateSnapshotReadyCallback\fP ()"
.br
.ti -1c
.RI "void \fBonSnapshotReady\fP (android\&.graphics\&.Bitmap p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file DelegateSnapshotReadyCallback\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.DelegateSnapshotReadyCallback ()"

.PP
Definition at line 20 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.DelegateSnapshotReadyCallback ()"

.PP
Definition at line 20 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.DelegateSnapshotReadyCallback ()"

.PP
Definition at line 20 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.DelegateSnapshotReadyCallback ()"

.PP
Definition at line 20 of file DelegateSnapshotReadyCallback\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.onSnapshotReady (android\&.graphics\&.Bitmap p0)"

.PP
Definition at line 28 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.onSnapshotReady (android\&.graphics\&.Bitmap p0)"

.PP
Definition at line 28 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.onSnapshotReady (android\&.graphics\&.Bitmap p0)"

.PP
Definition at line 28 of file DelegateSnapshotReadyCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.onSnapshotReady (android\&.graphics\&.Bitmap p0)"

.PP
Definition at line 28 of file DelegateSnapshotReadyCallback\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64d32ffa835eadac0e\&.DelegateSnapshotReadyCallback\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file DelegateSnapshotReadyCallback\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
