.TH "crc643f46942d9dd1fff9.SingleSnapHelper" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.SingleSnapHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.recyclerview\&.widget\&.PagerSnapHelper, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.PagerSnapHelper, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.PagerSnapHelper, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.PagerSnapHelper, and mono\&.android\&.IGCUserPeer\&.
.PP
Inherited by \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleSnapHelper\fP ()"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "int \fBfindTargetSnapPosition\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSingleSnapHelper\fP ()"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "int \fBfindTargetSnapPosition\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSingleSnapHelper\fP ()"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "int \fBfindTargetSnapPosition\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSingleSnapHelper\fP ()"
.br
.ti -1c
.RI "android\&.view\&.View \fBfindSnapView\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"
.br
.ti -1c
.RI "int \fBfindTargetSnapPosition\fP (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file SingleSnapHelper\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.SingleSnapHelper\&.SingleSnapHelper ()"

.PP
Definition at line 20 of file SingleSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SingleSnapHelper\&.SingleSnapHelper ()"

.PP
Definition at line 20 of file SingleSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SingleSnapHelper\&.SingleSnapHelper ()"

.PP
Definition at line 20 of file SingleSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SingleSnapHelper\&.SingleSnapHelper ()"

.PP
Definition at line 20 of file SingleSnapHelper\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 28 of file SingleSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 28 of file SingleSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 28 of file SingleSnapHelper\&.java\&.
.SS "android\&.view\&.View crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findSnapView (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0)"

.PP
Definition at line 28 of file SingleSnapHelper\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findTargetSnapPosition (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"

.PP
Definition at line 36 of file SingleSnapHelper\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findTargetSnapPosition (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"

.PP
Definition at line 36 of file SingleSnapHelper\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findTargetSnapPosition (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"

.PP
Definition at line 36 of file SingleSnapHelper\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.SingleSnapHelper\&.findTargetSnapPosition (androidx\&.recyclerview\&.widget\&.RecyclerView\&.LayoutManager p0, int p1, int p2)"

.PP
Definition at line 36 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 44 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 44 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 44 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 44 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 51 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 51 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 51 of file SingleSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SingleSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSingleSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSingleSnapHelper\fP\&.
.PP
Definition at line 51 of file SingleSnapHelper\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.SingleSnapHelper\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file SingleSnapHelper\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
