.TH "crc6414252951f3f66c67" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc6414252951f3f66c67
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCarouselViewAdapter_2\fP"
.br
.ti -1c
.RI "class \fBRecyclerViewScrollListener_2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
