.TH "mono.android.app.ApplicationRegistration" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.android.app.ApplicationRegistration
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterApplications\fP ()"
.br
.ti -1c
.RI "static void \fBregisterApplications\fP ()"
.br
.ti -1c
.RI "static void \fBregisterApplications\fP ()"
.br
.ti -1c
.RI "static void \fBregisterApplications\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ApplicationRegistration\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mono\&.android\&.app\&.ApplicationRegistration\&.registerApplications ()\fC [static]\fP"

.PP
Definition at line 5 of file ApplicationRegistration\&.java\&.
.SS "static void mono\&.android\&.app\&.ApplicationRegistration\&.registerApplications ()\fC [static]\fP"

.PP
Definition at line 5 of file ApplicationRegistration\&.java\&.
.SS "static void mono\&.android\&.app\&.ApplicationRegistration\&.registerApplications ()\fC [static]\fP"

.PP
Definition at line 5 of file ApplicationRegistration\&.java\&.
.SS "static void mono\&.android\&.app\&.ApplicationRegistration\&.registerApplications ()\fC [static]\fP"

.PP
Definition at line 5 of file ApplicationRegistration\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
