.TH "mono.MonoPackageManager_Resources" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.MonoPackageManager_Resources
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static String[] \fBAssemblies\fP"
.br
.ti -1c
.RI "static String[] \fBDependencies\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file MonoPackageManager_Resources\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "String [] mono\&.MonoPackageManager_Resources\&.Assemblies\fC [static]\fP"

.PP
Definition at line 3 of file MonoPackageManager_Resources\&.java\&.
.SS "String [] mono\&.MonoPackageManager_Resources\&.Dependencies\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= new String[]{
    }
.fi
.PP
Definition at line 130 of file MonoPackageManager_Resources\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
