.TH "mono.androidx.appcompat.widget.PopupMenu_OnDismissListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.appcompat.widget.PopupMenu_OnDismissListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.widget\&.PopupMenu\&.OnDismissListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.widget\&.PopupMenu\&.OnDismissListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.widget\&.PopupMenu\&.OnDismissListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and androidx\&.appcompat\&.widget\&.PopupMenu\&.OnDismissListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopupMenu_OnDismissListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDismiss\fP (androidx\&.appcompat\&.widget\&.PopupMenu p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPopupMenu_OnDismissListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDismiss\fP (androidx\&.appcompat\&.widget\&.PopupMenu p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPopupMenu_OnDismissListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDismiss\fP (androidx\&.appcompat\&.widget\&.PopupMenu p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPopupMenu_OnDismissListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDismiss\fP (androidx\&.appcompat\&.widget\&.PopupMenu p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.PopupMenu_OnDismissListenerImplementor ()"

.PP
Definition at line 20 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.PopupMenu_OnDismissListenerImplementor ()"

.PP
Definition at line 20 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.PopupMenu_OnDismissListenerImplementor ()"

.PP
Definition at line 20 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.PopupMenu_OnDismissListenerImplementor ()"

.PP
Definition at line 20 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.onDismiss (androidx\&.appcompat\&.widget\&.PopupMenu p0)"

.PP
Definition at line 28 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.onDismiss (androidx\&.appcompat\&.widget\&.PopupMenu p0)"

.PP
Definition at line 28 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.onDismiss (androidx\&.appcompat\&.widget\&.PopupMenu p0)"

.PP
Definition at line 28 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.onDismiss (androidx\&.appcompat\&.widget\&.PopupMenu p0)"

.PP
Definition at line 28 of file PopupMenu_OnDismissListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.androidx\&.appcompat\&.widget\&.PopupMenu_OnDismissListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file PopupMenu_OnDismissListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
