.TH "mono.com.google.android.gms.dynamic.OnDelegateCreatedListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.com.google.android.gms.dynamic.OnDelegateCreatedListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOnDelegateCreatedListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDelegateCreated\fP (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBOnDelegateCreatedListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDelegateCreated\fP (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBOnDelegateCreatedListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDelegateCreated\fP (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBOnDelegateCreatedListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonDelegateCreated\fP (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.OnDelegateCreatedListenerImplementor ()"

.PP
Definition at line 20 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.OnDelegateCreatedListenerImplementor ()"

.PP
Definition at line 20 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.OnDelegateCreatedListenerImplementor ()"

.PP
Definition at line 20 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.OnDelegateCreatedListenerImplementor ()"

.PP
Definition at line 20 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.onDelegateCreated (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"

.PP
Definition at line 28 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.onDelegateCreated (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"

.PP
Definition at line 28 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.onDelegateCreated (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"

.PP
Definition at line 28 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SS "void mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.onDelegateCreated (com\&.google\&.android\&.gms\&.dynamic\&.LifecycleDelegate p0)"

.PP
Definition at line 28 of file OnDelegateCreatedListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.com\&.google\&.android\&.gms\&.dynamic\&.OnDelegateCreatedListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file OnDelegateCreatedListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
