.TH "mono.androidx.fragment.app" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.fragment.app
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFragmentManager_OnBackStackChangedListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBFragmentOnAttachListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBFragmentResultListenerImplementor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
