.TH "mono.androidx.appcompat.app" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.appcompat.app
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionBar_OnMenuVisibilityListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBActionBar_OnNavigationListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBActionBar_TabListenerImplementor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
