.TH "Application Green Quake.Android/obj/Release/110/android/src/com/google/android/material/R.java" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/com/google/android/material/R.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.anim\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.animator\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.attr\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.bool\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.color\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.dimen\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.drawable\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.id\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.integer\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.interpolator\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.layout\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.plurals\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.string\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.style\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.styleable\fP"
.br
.ti -1c
.RI "class \fBcom\&.google\&.android\&.material\&.R\&.xml\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.google\&.android\&.material\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
