var namespace_application___green___quake_1_1_views_1_1_eco_actions_1_1_advanced_page_items =
[
    [ "FixInsteadOfThrowAway", "class_application___green___quake_1_1_views_1_1_eco_actions_1_1_advanced_page_items_1_1_fix_instead_of_throw_away.html", "class_application___green___quake_1_1_views_1_1_eco_actions_1_1_advanced_page_items_1_1_fix_instead_of_throw_away" ]
];