.TH "androidx.savedstate.R" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
androidx.savedstate.R
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file R\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
