.TH "androidhud.ProgressWheel_SpinHandler" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
androidhud.ProgressWheel_SpinHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.os\&.Handler, mono\&.android\&.IGCUserPeer, android\&.os\&.Handler, mono\&.android\&.IGCUserPeer, android\&.os\&.Handler, mono\&.android\&.IGCUserPeer, android\&.os\&.Handler, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Handler\&.Callback p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"
.br
.ti -1c
.RI "void \fBhandleMessage\fP (android\&.os\&.Message p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Handler\&.Callback p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"
.br
.ti -1c
.RI "void \fBhandleMessage\fP (android\&.os\&.Message p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Handler\&.Callback p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"
.br
.ti -1c
.RI "void \fBhandleMessage\fP (android\&.os\&.Message p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP ()"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Handler\&.Callback p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0)"
.br
.ti -1c
.RI "\fBProgressWheel_SpinHandler\fP (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"
.br
.ti -1c
.RI "void \fBhandleMessage\fP (android\&.os\&.Message p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ProgressWheel_SpinHandler\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler ()"

.PP
Definition at line 19 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Handler\&.Callback p0)"

.PP
Definition at line 27 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0)"

.PP
Definition at line 35 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"

.PP
Definition at line 43 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler ()"

.PP
Definition at line 19 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Handler\&.Callback p0)"

.PP
Definition at line 27 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0)"

.PP
Definition at line 35 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"

.PP
Definition at line 43 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler ()"

.PP
Definition at line 19 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Handler\&.Callback p0)"

.PP
Definition at line 27 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0)"

.PP
Definition at line 35 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"

.PP
Definition at line 43 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler ()"

.PP
Definition at line 19 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Handler\&.Callback p0)"

.PP
Definition at line 27 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0)"

.PP
Definition at line 35 of file ProgressWheel_SpinHandler\&.java\&.
.SS "androidhud\&.ProgressWheel_SpinHandler\&.ProgressWheel_SpinHandler (android\&.os\&.Looper p0, android\&.os\&.Handler\&.Callback p1)"

.PP
Definition at line 43 of file ProgressWheel_SpinHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.handleMessage (android\&.os\&.Message p0)"

.PP
Definition at line 51 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.handleMessage (android\&.os\&.Message p0)"

.PP
Definition at line 51 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.handleMessage (android\&.os\&.Message p0)"

.PP
Definition at line 51 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.handleMessage (android\&.os\&.Message p0)"

.PP
Definition at line 51 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 59 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ProgressWheel_SpinHandler\&.java\&.
.SS "void androidhud\&.ProgressWheel_SpinHandler\&.monodroidClearReferences ()"

.PP
Definition at line 66 of file ProgressWheel_SpinHandler\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String androidhud\&.ProgressWheel_SpinHandler\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file ProgressWheel_SpinHandler\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
