.TH "Application_Green_Quake.Views.EcoActions.EcoActionsSubMenu" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.EcoActionsSubMenu
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdvancedPage\fP"
.br
.ti -1c
.RI "class \fBCommunityPage\fP"
.br
.ti -1c
.RI "class \fBEnergyPage\fP"
.br
.ti -1c
.RI "class \fBFoodAndDrinkPage\fP"
.br
.ti -1c
.RI "class \fBHabitsPage\fP"
.br
.ti -1c
.RI "class \fBHomePage\fP"
.br
.ti -1c
.RI "class \fBOutdoorsPage\fP"
.br
.ti -1c
.RI "class \fBShoppingPage\fP"
.br
.ti -1c
.RI "class \fBTravelPage\fP"
.br
.ti -1c
.RI "class \fBWastePage\fP"
.br
.ti -1c
.RI "class \fBWaterPage\fP"
.br
.ti -1c
.RI "class \fBWorkPage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
