.TH "Application_Green_Quake.ViewModels.GetBadgeData" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.GetBadgeData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBSetBadgeData\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBadvancedLog\fP = 0"
.br
.ti -1c
.RI "static int \fBhabitsLog\fP = 0"
.br
.ti -1c
.RI "static int \fBcommunityLog\fP = 0"
.br
.ti -1c
.RI "static int \fBenergyLog\fP = 0"
.br
.ti -1c
.RI "static int \fBfoodDrinkLog\fP = 0"
.br
.ti -1c
.RI "static int \fBhomeLog\fP = 0"
.br
.ti -1c
.RI "static int \fBoutdoorsLog\fP = 0"
.br
.ti -1c
.RI "static int \fBshoppingLog\fP = 0"
.br
.ti -1c
.RI "static int \fBtravelLog\fP = 0"
.br
.ti -1c
.RI "static int \fBwasteLog\fP = 0"
.br
.ti -1c
.RI "static int \fBwaterLog\fP = 0"
.br
.ti -1c
.RI "static int \fBworkLog\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file GetBadgeData\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.SetBadgeData ()"
This function sets the data that is needed for the badges screen 
.PP
Definition at line 35 of file GetBadgeData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.advancedLog = 0\fC [static]\fP"

.PP
Definition at line 19 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.communityLog = 0\fC [static]\fP"

.PP
Definition at line 21 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.energyLog = 0\fC [static]\fP"

.PP
Definition at line 22 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.foodDrinkLog = 0\fC [static]\fP"

.PP
Definition at line 23 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.habitsLog = 0\fC [static]\fP"

.PP
Definition at line 20 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.homeLog = 0\fC [static]\fP"

.PP
Definition at line 24 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.outdoorsLog = 0\fC [static]\fP"

.PP
Definition at line 25 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.shoppingLog = 0\fC [static]\fP"

.PP
Definition at line 26 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.travelLog = 0\fC [static]\fP"

.PP
Definition at line 27 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.wasteLog = 0\fC [static]\fP"

.PP
Definition at line 28 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.waterLog = 0\fC [static]\fP"

.PP
Definition at line 29 of file GetBadgeData\&.cs\&.
.SS "int Application_Green_Quake\&.ViewModels\&.GetBadgeData\&.workLog = 0\fC [static]\fP"

.PP
Definition at line 30 of file GetBadgeData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
