.TH "Application_Green_Quake.Views.EcoActions.Water" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.Water
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCisternDisplacement\fP"
.br
.ti -1c
.RI "class \fBRainBarrel\fP"
.br
.ti -1c
.RI "class \fBReusableWater\fP"
.br
.ti -1c
.RI "class \fBShowerBucket\fP"
.br
.ti -1c
.RI "class \fBWSShowerHead\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
