.TH "Application_Green_Quake.Droid.Resource.Integer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Integer
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_config_activityDefaultDur\fP = 2131296256"
.br
.ti -1c
.RI "const int \fBabc_config_activityShortDur\fP = 2131296257"
.br
.ti -1c
.RI "const int \fBapp_bar_elevation_anim_duration\fP = 2131296258"
.br
.ti -1c
.RI "const int \fBbottom_sheet_slide_duration\fP = 2131296259"
.br
.ti -1c
.RI "const int \fBcancel_button_image_alpha\fP = 2131296260"
.br
.ti -1c
.RI "const int \fBconfig_tooltipAnimTime\fP = 2131296261"
.br
.ti -1c
.RI "const int \fBdesign_snackbar_text_max_lines\fP = 2131296262"
.br
.ti -1c
.RI "const int \fBdesign_tab_indicator_anim_duration_ms\fP = 2131296263"
.br
.ti -1c
.RI "const int \fBgoogle_play_services_version\fP = 2131296264"
.br
.ti -1c
.RI "const int \fBhide_password_duration\fP = 2131296265"
.br
.ti -1c
.RI "const int \fBmtrl_badge_max_character_count\fP = 2131296266"
.br
.ti -1c
.RI "const int \fBmtrl_btn_anim_delay_ms\fP = 2131296267"
.br
.ti -1c
.RI "const int \fBmtrl_btn_anim_duration_ms\fP = 2131296268"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_header_orientation\fP = 2131296269"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_selection_text_lines\fP = 2131296270"
.br
.ti -1c
.RI "const int \fBmtrl_calendar_year_selector_span\fP = 2131296271"
.br
.ti -1c
.RI "const int \fBmtrl_card_anim_delay_ms\fP = 2131296272"
.br
.ti -1c
.RI "const int \fBmtrl_card_anim_duration_ms\fP = 2131296273"
.br
.ti -1c
.RI "const int \fBmtrl_chip_anim_duration\fP = 2131296274"
.br
.ti -1c
.RI "const int \fBmtrl_tab_indicator_anim_duration_ms\fP = 2131296275"
.br
.ti -1c
.RI "const int \fBshow_password_duration\fP = 2131296276"
.br
.ti -1c
.RI "const int \fBstatus_bar_notification_info_maxnum\fP = 2131296277"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22394 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.abc_config_activityDefaultDur = 2131296256\fC [static]\fP"

.PP
Definition at line 22398 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.abc_config_activityShortDur = 2131296257\fC [static]\fP"

.PP
Definition at line 22401 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.app_bar_elevation_anim_duration = 2131296258\fC [static]\fP"

.PP
Definition at line 22404 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.bottom_sheet_slide_duration = 2131296259\fC [static]\fP"

.PP
Definition at line 22407 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.cancel_button_image_alpha = 2131296260\fC [static]\fP"

.PP
Definition at line 22410 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.config_tooltipAnimTime = 2131296261\fC [static]\fP"

.PP
Definition at line 22413 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.design_snackbar_text_max_lines = 2131296262\fC [static]\fP"

.PP
Definition at line 22416 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.design_tab_indicator_anim_duration_ms = 2131296263\fC [static]\fP"

.PP
Definition at line 22419 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.google_play_services_version = 2131296264\fC [static]\fP"

.PP
Definition at line 22422 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.hide_password_duration = 2131296265\fC [static]\fP"

.PP
Definition at line 22425 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_badge_max_character_count = 2131296266\fC [static]\fP"

.PP
Definition at line 22428 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_btn_anim_delay_ms = 2131296267\fC [static]\fP"

.PP
Definition at line 22431 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_btn_anim_duration_ms = 2131296268\fC [static]\fP"

.PP
Definition at line 22434 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_calendar_header_orientation = 2131296269\fC [static]\fP"

.PP
Definition at line 22437 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_calendar_selection_text_lines = 2131296270\fC [static]\fP"

.PP
Definition at line 22440 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_calendar_year_selector_span = 2131296271\fC [static]\fP"

.PP
Definition at line 22443 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_card_anim_delay_ms = 2131296272\fC [static]\fP"

.PP
Definition at line 22446 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_card_anim_duration_ms = 2131296273\fC [static]\fP"

.PP
Definition at line 22449 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_chip_anim_duration = 2131296274\fC [static]\fP"

.PP
Definition at line 22452 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.mtrl_tab_indicator_anim_duration_ms = 2131296275\fC [static]\fP"

.PP
Definition at line 22455 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.show_password_duration = 2131296276\fC [static]\fP"

.PP
Definition at line 22458 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Integer\&.status_bar_notification_info_maxnum = 2131296277\fC [static]\fP"

.PP
Definition at line 22461 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
