.TH "Application_Green_Quake.Views.EcoActions.FoodAndDrink" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.FoodAndDrink
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBuyOrganicFood\fP"
.br
.ti -1c
.RI "class \fBEatAllYouMake\fP"
.br
.ti -1c
.RI "class \fBFoodDelivered\fP"
.br
.ti -1c
.RI "class \fBNoMeat\fP"
.br
.ti -1c
.RI "class \fBOwnCoffee\fP"
.br
.ti -1c
.RI "class \fBReCoffeeMug\fP"
.br
.ti -1c
.RI "class \fBSaveLeftOvers\fP"
.br
.ti -1c
.RI "class \fBSteelStraw\fP"
.br
.ti -1c
.RI "class \fBWaterOverFizzy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
