.TH "Application_Green_Quake.Droid.Resource.Animator" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Animator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBdesign_appbar_state_list_animator\fP = 2130837504"
.br
.ti -1c
.RI "const int \fBdesign_fab_hide_motion_spec\fP = 2130837505"
.br
.ti -1c
.RI "const int \fBdesign_fab_show_motion_spec\fP = 2130837506"
.br
.ti -1c
.RI "const int \fBfragment_close_enter\fP = 2130837507"
.br
.ti -1c
.RI "const int \fBfragment_close_exit\fP = 2130837508"
.br
.ti -1c
.RI "const int \fBfragment_fade_enter\fP = 2130837509"
.br
.ti -1c
.RI "const int \fBfragment_fade_exit\fP = 2130837510"
.br
.ti -1c
.RI "const int \fBfragment_open_enter\fP = 2130837511"
.br
.ti -1c
.RI "const int \fBfragment_open_exit\fP = 2130837512"
.br
.ti -1c
.RI "const int \fBlinear_indeterminate_line1_head_interpolator\fP = 2130837513"
.br
.ti -1c
.RI "const int \fBlinear_indeterminate_line1_tail_interpolator\fP = 2130837514"
.br
.ti -1c
.RI "const int \fBlinear_indeterminate_line2_head_interpolator\fP = 2130837515"
.br
.ti -1c
.RI "const int \fBlinear_indeterminate_line2_tail_interpolator\fP = 2130837516"
.br
.ti -1c
.RI "const int \fBmtrl_btn_state_list_anim\fP = 2130837517"
.br
.ti -1c
.RI "const int \fBmtrl_btn_unelevated_state_list_anim\fP = 2130837518"
.br
.ti -1c
.RI "const int \fBmtrl_card_state_list_anim\fP = 2130837519"
.br
.ti -1c
.RI "const int \fBmtrl_chip_state_list_anim\fP = 2130837520"
.br
.ti -1c
.RI "const int \fBmtrl_extended_fab_change_size_collapse_motion_spec\fP = 2130837521"
.br
.ti -1c
.RI "const int \fBmtrl_extended_fab_change_size_expand_motion_spec\fP = 2130837522"
.br
.ti -1c
.RI "const int \fBmtrl_extended_fab_hide_motion_spec\fP = 2130837523"
.br
.ti -1c
.RI "const int \fBmtrl_extended_fab_show_motion_spec\fP = 2130837524"
.br
.ti -1c
.RI "const int \fBmtrl_extended_fab_state_list_animator\fP = 2130837525"
.br
.ti -1c
.RI "const int \fBmtrl_fab_hide_motion_spec\fP = 2130837526"
.br
.ti -1c
.RI "const int \fBmtrl_fab_show_motion_spec\fP = 2130837527"
.br
.ti -1c
.RI "const int \fBmtrl_fab_transformation_sheet_collapse_spec\fP = 2130837528"
.br
.ti -1c
.RI "const int \fBmtrl_fab_transformation_sheet_expand_spec\fP = 2130837529"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15712 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.design_appbar_state_list_animator = 2130837504\fC [static]\fP"

.PP
Definition at line 15716 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.design_fab_hide_motion_spec = 2130837505\fC [static]\fP"

.PP
Definition at line 15719 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.design_fab_show_motion_spec = 2130837506\fC [static]\fP"

.PP
Definition at line 15722 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.fragment_close_enter = 2130837507\fC [static]\fP"

.PP
Definition at line 15725 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.fragment_close_exit = 2130837508\fC [static]\fP"

.PP
Definition at line 15728 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.fragment_fade_enter = 2130837509\fC [static]\fP"

.PP
Definition at line 15731 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.fragment_fade_exit = 2130837510\fC [static]\fP"

.PP
Definition at line 15734 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.fragment_open_enter = 2130837511\fC [static]\fP"

.PP
Definition at line 15737 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.fragment_open_exit = 2130837512\fC [static]\fP"

.PP
Definition at line 15740 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.linear_indeterminate_line1_head_interpolator = 2130837513\fC [static]\fP"

.PP
Definition at line 15743 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.linear_indeterminate_line1_tail_interpolator = 2130837514\fC [static]\fP"

.PP
Definition at line 15746 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.linear_indeterminate_line2_head_interpolator = 2130837515\fC [static]\fP"

.PP
Definition at line 15749 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.linear_indeterminate_line2_tail_interpolator = 2130837516\fC [static]\fP"

.PP
Definition at line 15752 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_btn_state_list_anim = 2130837517\fC [static]\fP"

.PP
Definition at line 15755 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_btn_unelevated_state_list_anim = 2130837518\fC [static]\fP"

.PP
Definition at line 15758 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_card_state_list_anim = 2130837519\fC [static]\fP"

.PP
Definition at line 15761 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_chip_state_list_anim = 2130837520\fC [static]\fP"

.PP
Definition at line 15764 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_extended_fab_change_size_collapse_motion_spec = 2130837521\fC [static]\fP"

.PP
Definition at line 15767 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_extended_fab_change_size_expand_motion_spec = 2130837522\fC [static]\fP"

.PP
Definition at line 15770 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_extended_fab_hide_motion_spec = 2130837523\fC [static]\fP"

.PP
Definition at line 15773 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_extended_fab_show_motion_spec = 2130837524\fC [static]\fP"

.PP
Definition at line 15776 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_extended_fab_state_list_animator = 2130837525\fC [static]\fP"

.PP
Definition at line 15779 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_fab_hide_motion_spec = 2130837526\fC [static]\fP"

.PP
Definition at line 15782 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_fab_show_motion_spec = 2130837527\fC [static]\fP"

.PP
Definition at line 15785 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_fab_transformation_sheet_collapse_spec = 2130837528\fC [static]\fP"

.PP
Definition at line 15788 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Animator\&.mtrl_fab_transformation_sheet_expand_spec = 2130837529\fC [static]\fP"

.PP
Definition at line 15791 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
