.TH "Application_Green_Quake.Droid.Resource.Boolean" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Boolean
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_action_bar_embed_tabs\fP = 2130968576"
.br
.ti -1c
.RI "const int \fBabc_allow_stacked_button_bar\fP = 2130968577"
.br
.ti -1c
.RI "const int \fBabc_config_actionMenuItemAllCaps\fP = 2130968578"
.br
.ti -1c
.RI "const int \fBmtrl_btn_textappearance_all_caps\fP = 2130968579"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18600 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Boolean\&.abc_action_bar_embed_tabs = 2130968576\fC [static]\fP"

.PP
Definition at line 18604 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Boolean\&.abc_allow_stacked_button_bar = 2130968577\fC [static]\fP"

.PP
Definition at line 18607 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Boolean\&.abc_config_actionMenuItemAllCaps = 2130968578\fC [static]\fP"

.PP
Definition at line 18610 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Boolean\&.mtrl_btn_textappearance_all_caps = 2130968579\fC [static]\fP"

.PP
Definition at line 18613 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
