.TH "Application_Green_Quake.Models.Station" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.Station
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBdescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlabel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBlatitude\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBlongitude\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Station\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Application_Green_Quake\&.Models\&.Station\&.description\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file Station\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.Station\&.label\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file Station\&.cs\&.
.SS "double Application_Green_Quake\&.Models\&.Station\&.latitude\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file Station\&.cs\&.
.SS "double Application_Green_Quake\&.Models\&.Station\&.longitude\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file Station\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
