.TH "Application_Green_Quake.Models.HabitsPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.HabitsPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBbrushingCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBfullWasherCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBshowerCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBtimedShowerCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBoffLigtsCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBmatchesCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file HabitsPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.brushingCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.fullWasherCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.matchesCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.offLigtsCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.showerCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file HabitsPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.HabitsPoints\&.timedShowerCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file HabitsPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.HabitsPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file HabitsPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
