.TH "Application_Green_Quake.Models.ImageResourceExtension" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.ImageResourceExtension
.SH SYNOPSIS
.br
.PP
.PP
Inherits IMarkupExtension\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBProvideValue\fP (IServiceProvider serviceProvider)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSource\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file ImageResourceExtension\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object Application_Green_Quake\&.Models\&.ImageResourceExtension\&.ProvideValue (IServiceProvider serviceProvider)"

.PP
Definition at line 21 of file ImageResourceExtension\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Application_Green_Quake\&.Models\&.ImageResourceExtension\&.Source\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file ImageResourceExtension\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
