.TH "Application_Green_Quake.Models.TravelPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.TravelPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcarpoolCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcycleCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBecoCarCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBtransportCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBwalkCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file TravelPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.carpoolCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file TravelPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.cycleCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file TravelPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.ecoCarCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file TravelPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file TravelPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file TravelPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.transportCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file TravelPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.TravelPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file TravelPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.TravelPoints\&.walkCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file TravelPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
