.TH "Application_Green_Quake.ViewModels.AdvancedPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.AdvancedPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBFixPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file AdvancedPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.AdvancedPointsUpdate\&.FixPoints ()"
This function updates the points in the Advanced category by ten points\&. It also increments the number of logs logged in the Advanced category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 29 of file AdvancedPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
