.TH "Application_Green_Quake.Droid.Resource.Interpolator" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.Interpolator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBbtn_checkbox_checked_mtrl_animation_interpolator_0\fP = 2131361792"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_checked_mtrl_animation_interpolator_1\fP = 2131361793"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_unchecked_mtrl_animation_interpolator_0\fP = 2131361794"
.br
.ti -1c
.RI "const int \fBbtn_checkbox_unchecked_mtrl_animation_interpolator_1\fP = 2131361795"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_off_mtrl_animation_interpolator_0\fP = 2131361796"
.br
.ti -1c
.RI "const int \fBbtn_radio_to_on_mtrl_animation_interpolator_0\fP = 2131361797"
.br
.ti -1c
.RI "const int \fBfast_out_slow_in\fP = 2131361798"
.br
.ti -1c
.RI "const int \fBmtrl_fast_out_linear_in\fP = 2131361799"
.br
.ti -1c
.RI "const int \fBmtrl_fast_out_slow_in\fP = 2131361800"
.br
.ti -1c
.RI "const int \fBmtrl_linear\fP = 2131361801"
.br
.ti -1c
.RI "const int \fBmtrl_linear_out_slow_in\fP = 2131361802"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22473 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.btn_checkbox_checked_mtrl_animation_interpolator_0 = 2131361792\fC [static]\fP"

.PP
Definition at line 22477 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.btn_checkbox_checked_mtrl_animation_interpolator_1 = 2131361793\fC [static]\fP"

.PP
Definition at line 22480 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.btn_checkbox_unchecked_mtrl_animation_interpolator_0 = 2131361794\fC [static]\fP"

.PP
Definition at line 22483 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.btn_checkbox_unchecked_mtrl_animation_interpolator_1 = 2131361795\fC [static]\fP"

.PP
Definition at line 22486 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.btn_radio_to_off_mtrl_animation_interpolator_0 = 2131361796\fC [static]\fP"

.PP
Definition at line 22489 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.btn_radio_to_on_mtrl_animation_interpolator_0 = 2131361797\fC [static]\fP"

.PP
Definition at line 22492 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.fast_out_slow_in = 2131361798\fC [static]\fP"

.PP
Definition at line 22495 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.mtrl_fast_out_linear_in = 2131361799\fC [static]\fP"

.PP
Definition at line 22498 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.mtrl_fast_out_slow_in = 2131361800\fC [static]\fP"

.PP
Definition at line 22501 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.mtrl_linear = 2131361801\fC [static]\fP"

.PP
Definition at line 22504 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.Interpolator\&.mtrl_linear_out_slow_in = 2131361802\fC [static]\fP"

.PP
Definition at line 22507 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
