.TH "Application_Green_Quake.Models.AppConstants" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.AppConstants
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBtwoPoints\fP = 2"
.br
.ti -1c
.RI "const int \fBfourPoints\fP = 4"
.br
.ti -1c
.RI "const int \fBsixPoints\fP = 6"
.br
.ti -1c
.RI "const int \fBeightPoints\fP = 8"
.br
.ti -1c
.RI "const int \fBtenPoints\fP = 10"
.br
.ti -1c
.RI "const string \fBgoogleMapsApiKey\fP = 'AIzaSyDf7Bq7gjei8Sp1AS_SWeapWyHe2rJtLmw'"
.br
.ti -1c
.RI "const string \fBtwoPointsMsg\fP = '2 Points Point Have been added'"
.br
.ti -1c
.RI "const string \fBfourPointsMsg\fP = '4 Points Point Have been added'"
.br
.ti -1c
.RI "const string \fBsixPointsMsg\fP = '6 Points Point Have been added'"
.br
.ti -1c
.RI "const string \fBeightPointsMsg\fP = '8 Points Point Have been added'"
.br
.ti -1c
.RI "const string \fBtenPointsMsg\fP = '10 Points Point Have been added'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file AppConstants\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Models\&.AppConstants\&.eightPoints = 8\fC [static]\fP"

.PP
Definition at line 17 of file AppConstants\&.cs\&.
.SS "const string Application_Green_Quake\&.Models\&.AppConstants\&.eightPointsMsg = '8 Points Point Have been added'\fC [static]\fP"

.PP
Definition at line 25 of file AppConstants\&.cs\&.
.SS "const int Application_Green_Quake\&.Models\&.AppConstants\&.fourPoints = 4\fC [static]\fP"

.PP
Definition at line 15 of file AppConstants\&.cs\&.
.SS "const string Application_Green_Quake\&.Models\&.AppConstants\&.fourPointsMsg = '4 Points Point Have been added'\fC [static]\fP"

.PP
Definition at line 23 of file AppConstants\&.cs\&.
.SS "const string Application_Green_Quake\&.Models\&.AppConstants\&.googleMapsApiKey = 'AIzaSyDf7Bq7gjei8Sp1AS_SWeapWyHe2rJtLmw'\fC [static]\fP"

.PP
Definition at line 21 of file AppConstants\&.cs\&.
.SS "const int Application_Green_Quake\&.Models\&.AppConstants\&.sixPoints = 6\fC [static]\fP"

.PP
Definition at line 16 of file AppConstants\&.cs\&.
.SS "const string Application_Green_Quake\&.Models\&.AppConstants\&.sixPointsMsg = '6 Points Point Have been added'\fC [static]\fP"

.PP
Definition at line 24 of file AppConstants\&.cs\&.
.SS "const int Application_Green_Quake\&.Models\&.AppConstants\&.tenPoints = 10\fC [static]\fP"

.PP
Definition at line 18 of file AppConstants\&.cs\&.
.SS "const string Application_Green_Quake\&.Models\&.AppConstants\&.tenPointsMsg = '10 Points Point Have been added'\fC [static]\fP"

.PP
Definition at line 26 of file AppConstants\&.cs\&.
.SS "const int Application_Green_Quake\&.Models\&.AppConstants\&.twoPoints = 2\fC [static]\fP"

.PP
Definition at line 14 of file AppConstants\&.cs\&.
.SS "const string Application_Green_Quake\&.Models\&.AppConstants\&.twoPointsMsg = '2 Points Point Have been added'\fC [static]\fP"

.PP
Definition at line 22 of file AppConstants\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
