.TH "Application Green Quake.Android/obj/Release/110/android/src/mono/android/app/ApplicationRegistration.java" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/mono/android/app/ApplicationRegistration.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmono\&.android\&.app\&.ApplicationRegistration\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBmono\&.android\&.app\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
