.TH "Application_Green_Quake.Views.LeaderboardPage.LeaderBoardPopUp" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.LeaderboardPage.LeaderBoardPopUp
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.RgPlugins\&.Popup\&.Pages\&.PopupPage, and global\&.RgPlugins\&.Popup\&.Pages\&.PopupPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLeaderBoardPopUp\fP (string username, int points, string rank, ImageSource image, string bio)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file LeaderBoardPopUp\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.LeaderboardPage\&.LeaderBoardPopUp\&.LeaderBoardPopUp (string username, int points, string rank, ImageSource image, string bio)"
\fBThe\fP \fBLeaderBoardPopUp\fP Constructor 
.PP
\fBParameters\fP
.RS 4
\fIusername\fP is the username to display 
.br
\fIpoints\fP are the points to display 
.br
\fIrank\fP is the rank to display 
.br
\fIimage\fP is the image to display 
.br
\fIbio\fP is the bio to display 
.RE
.PP

.PP
Definition at line 24 of file LeaderBoardPopUp\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
