.TH "Application_Green_Quake.Models.WaterPoints" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.WaterPoints
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnumberOfLogs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcisternCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBrainBarrelCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBreWaterCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBshowerBucketCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBwSShowerHeadCount\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file WaterPoints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.cisternCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file WaterPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.numberOfLogs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file WaterPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 14 of file WaterPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.rainBarrelCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file WaterPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.reWaterCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file WaterPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.showerBucketCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file WaterPoints\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.WaterPoints\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 13 of file WaterPoints\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.WaterPoints\&.wSShowerHeadCount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file WaterPoints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
