.TH "Application_Green_Quake.ViewModels.HabitsPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.HabitsPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBBrushingPoints\fP ()"
.br
.ti -1c
.RI "async void \fBDishWasherFullPoints\fP ()"
.br
.ti -1c
.RI "async void \fBShowerInsteadPoints\fP ()"
.br
.ti -1c
.RI "async void \fBTimedShowerInsteadPoints\fP ()"
.br
.ti -1c
.RI "async void \fBOffLightsPoints\fP ()"
.br
.ti -1c
.RI "async void \fBMatchesPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file HabitsPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.HabitsPointsUpdate\&.BrushingPoints ()"
This function updates the points in the Habits category by two points\&. It also increments the number of logs logged in the Habits category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 35 of file HabitsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.HabitsPointsUpdate\&.DishWasherFullPoints ()"
This function updates the points in the Habits category by eight points\&. It also increments the number of logs logged in the Habits category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 141 of file HabitsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.HabitsPointsUpdate\&.MatchesPoints ()"
This function updates the points in the Habits category by two points\&. It also increments the number of logs logged in the Habits category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 565 of file HabitsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.HabitsPointsUpdate\&.OffLightsPoints ()"
This function updates the points in the Habits category by two points\&. It also increments the number of logs logged in the Habits category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 459 of file HabitsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.HabitsPointsUpdate\&.ShowerInsteadPoints ()"
This function updates the points in the Habits category by six points\&. It also increments the number of logs logged in the Habits category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 247 of file HabitsPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.HabitsPointsUpdate\&.TimedShowerInsteadPoints ()"
This function updates the points in the Habits category by four points\&. It also increments the number of logs logged in the Habits category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 353 of file HabitsPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
