.TH "Application_Green_Quake.Droid.Resource.String" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Droid.Resource.String
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBabc_action_bar_home_description\fP = 2131623936"
.br
.ti -1c
.RI "const int \fBabc_action_bar_up_description\fP = 2131623937"
.br
.ti -1c
.RI "const int \fBabc_action_menu_overflow_description\fP = 2131623938"
.br
.ti -1c
.RI "const int \fBabc_action_mode_done\fP = 2131623939"
.br
.ti -1c
.RI "const int \fBabc_activitychooserview_choose_application\fP = 2131623941"
.br
.ti -1c
.RI "const int \fBabc_activity_chooser_view_see_all\fP = 2131623940"
.br
.ti -1c
.RI "const int \fBabc_capital_off\fP = 2131623942"
.br
.ti -1c
.RI "const int \fBabc_capital_on\fP = 2131623943"
.br
.ti -1c
.RI "const int \fBabc_menu_alt_shortcut_label\fP = 2131623944"
.br
.ti -1c
.RI "const int \fBabc_menu_ctrl_shortcut_label\fP = 2131623945"
.br
.ti -1c
.RI "const int \fBabc_menu_delete_shortcut_label\fP = 2131623946"
.br
.ti -1c
.RI "const int \fBabc_menu_enter_shortcut_label\fP = 2131623947"
.br
.ti -1c
.RI "const int \fBabc_menu_function_shortcut_label\fP = 2131623948"
.br
.ti -1c
.RI "const int \fBabc_menu_meta_shortcut_label\fP = 2131623949"
.br
.ti -1c
.RI "const int \fBabc_menu_shift_shortcut_label\fP = 2131623950"
.br
.ti -1c
.RI "const int \fBabc_menu_space_shortcut_label\fP = 2131623951"
.br
.ti -1c
.RI "const int \fBabc_menu_sym_shortcut_label\fP = 2131623952"
.br
.ti -1c
.RI "const int \fBabc_prepend_shortcut_label\fP = 2131623953"
.br
.ti -1c
.RI "const int \fBabc_searchview_description_clear\fP = 2131623955"
.br
.ti -1c
.RI "const int \fBabc_searchview_description_query\fP = 2131623956"
.br
.ti -1c
.RI "const int \fBabc_searchview_description_search\fP = 2131623957"
.br
.ti -1c
.RI "const int \fBabc_searchview_description_submit\fP = 2131623958"
.br
.ti -1c
.RI "const int \fBabc_searchview_description_voice\fP = 2131623959"
.br
.ti -1c
.RI "const int \fBabc_search_hint\fP = 2131623954"
.br
.ti -1c
.RI "const int \fBabc_shareactionprovider_share_with\fP = 2131623960"
.br
.ti -1c
.RI "const int \fBabc_shareactionprovider_share_with_application\fP = 2131623961"
.br
.ti -1c
.RI "const int \fBabc_toolbar_collapse_description\fP = 2131623962"
.br
.ti -1c
.RI "const int \fBappbar_scrolling_view_behavior\fP = 2131623963"
.br
.ti -1c
.RI "const int \fBbottomsheet_action_expand_halfway\fP = 2131623965"
.br
.ti -1c
.RI "const int \fBbottom_sheet_behavior\fP = 2131623964"
.br
.ti -1c
.RI "const int \fBcharacter_counter_content_description\fP = 2131623966"
.br
.ti -1c
.RI "const int \fBcharacter_counter_overflowed_content_description\fP = 2131623967"
.br
.ti -1c
.RI "const int \fBcharacter_counter_pattern\fP = 2131623968"
.br
.ti -1c
.RI "const int \fBchip_text\fP = 2131623969"
.br
.ti -1c
.RI "const int \fBclear_text_end_icon_content_description\fP = 2131623970"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_enable_button\fP = 2131623971"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_enable_text\fP = 2131623972"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_enable_title\fP = 2131623973"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_install_button\fP = 2131623974"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_install_text\fP = 2131623975"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_install_title\fP = 2131623976"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_notification_channel_name\fP = 2131623977"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_notification_ticker\fP = 2131623978"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_unknown_issue\fP = 2131623979"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_unsupported_text\fP = 2131623980"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_update_button\fP = 2131623981"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_update_text\fP = 2131623982"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_update_title\fP = 2131623983"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_updating_text\fP = 2131623984"
.br
.ti -1c
.RI "const int \fBcommon_google_play_services_wear_update_text\fP = 2131623985"
.br
.ti -1c
.RI "const int \fBcommon_open_on_phone\fP = 2131623986"
.br
.ti -1c
.RI "const int \fBcommon_signin_button_text\fP = 2131623987"
.br
.ti -1c
.RI "const int \fBcommon_signin_button_text_long\fP = 2131623988"
.br
.ti -1c
.RI "const int \fBcopy_toast_msg\fP = 2131623989"
.br
.ti -1c
.RI "const int \fBdefault_web_client_id\fP = 2131623990"
.br
.ti -1c
.RI "const int \fBerror_icon_content_description\fP = 2131623991"
.br
.ti -1c
.RI "const int \fBexposed_dropdown_menu_content_description\fP = 2131623992"
.br
.ti -1c
.RI "const int \fBfab_transformation_scrim_behavior\fP = 2131623993"
.br
.ti -1c
.RI "const int \fBfab_transformation_sheet_behavior\fP = 2131623994"
.br
.ti -1c
.RI "const int \fBfallback_menu_item_copy_link\fP = 2131623995"
.br
.ti -1c
.RI "const int \fBfallback_menu_item_open_in_browser\fP = 2131623996"
.br
.ti -1c
.RI "const int \fBfallback_menu_item_share_link\fP = 2131623997"
.br
.ti -1c
.RI "const int \fBfirebase_database_url\fP = 2131623998"
.br
.ti -1c
.RI "const int \fBgcm_defaultSenderId\fP = 2131623999"
.br
.ti -1c
.RI "const int \fBgoogle_api_key\fP = 2131624000"
.br
.ti -1c
.RI "const int \fBgoogle_app_id\fP = 2131624001"
.br
.ti -1c
.RI "const int \fBgoogle_crash_reporting_api_key\fP = 2131624002"
.br
.ti -1c
.RI "const int \fBgoogle_storage_bucket\fP = 2131624003"
.br
.ti -1c
.RI "const int \fBhide_bottom_view_on_scroll_behavior\fP = 2131624004"
.br
.ti -1c
.RI "const int \fBicon_content_description\fP = 2131624005"
.br
.ti -1c
.RI "const int \fBitem_view_role_description\fP = 2131624006"
.br
.ti -1c
.RI "const int \fBlibrary_name\fP = 2131624007"
.br
.ti -1c
.RI "const int \fBmaterial_clock_display_divider\fP = 2131624008"
.br
.ti -1c
.RI "const int \fBmaterial_clock_toggle_content_description\fP = 2131624009"
.br
.ti -1c
.RI "const int \fBmaterial_hour_selection\fP = 2131624010"
.br
.ti -1c
.RI "const int \fBmaterial_hour_suffix\fP = 2131624011"
.br
.ti -1c
.RI "const int \fBmaterial_minute_selection\fP = 2131624012"
.br
.ti -1c
.RI "const int \fBmaterial_minute_suffix\fP = 2131624013"
.br
.ti -1c
.RI "const int \fBmaterial_slider_range_end\fP = 2131624014"
.br
.ti -1c
.RI "const int \fBmaterial_slider_range_start\fP = 2131624015"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_am\fP = 2131624016"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_clock_mode_description\fP = 2131624017"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_hour\fP = 2131624018"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_minute\fP = 2131624019"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_pm\fP = 2131624020"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_select_time\fP = 2131624021"
.br
.ti -1c
.RI "const int \fBmaterial_timepicker_text_input_mode_description\fP = 2131624022"
.br
.ti -1c
.RI "const int \fBmtrl_badge_numberless_content_description\fP = 2131624023"
.br
.ti -1c
.RI "const int \fBmtrl_chip_close_icon_content_description\fP = 2131624024"
.br
.ti -1c
.RI "const int \fBmtrl_exceed_max_badge_number_content_description\fP = 2131624025"
.br
.ti -1c
.RI "const int \fBmtrl_exceed_max_badge_number_suffix\fP = 2131624026"
.br
.ti -1c
.RI "const int \fBmtrl_picker_a11y_next_month\fP = 2131624027"
.br
.ti -1c
.RI "const int \fBmtrl_picker_a11y_prev_month\fP = 2131624028"
.br
.ti -1c
.RI "const int \fBmtrl_picker_announce_current_selection\fP = 2131624029"
.br
.ti -1c
.RI "const int \fBmtrl_picker_cancel\fP = 2131624030"
.br
.ti -1c
.RI "const int \fBmtrl_picker_confirm\fP = 2131624031"
.br
.ti -1c
.RI "const int \fBmtrl_picker_date_header_selected\fP = 2131624032"
.br
.ti -1c
.RI "const int \fBmtrl_picker_date_header_title\fP = 2131624033"
.br
.ti -1c
.RI "const int \fBmtrl_picker_date_header_unselected\fP = 2131624034"
.br
.ti -1c
.RI "const int \fBmtrl_picker_day_of_week_column_header\fP = 2131624035"
.br
.ti -1c
.RI "const int \fBmtrl_picker_invalid_format\fP = 2131624036"
.br
.ti -1c
.RI "const int \fBmtrl_picker_invalid_format_example\fP = 2131624037"
.br
.ti -1c
.RI "const int \fBmtrl_picker_invalid_format_use\fP = 2131624038"
.br
.ti -1c
.RI "const int \fBmtrl_picker_invalid_range\fP = 2131624039"
.br
.ti -1c
.RI "const int \fBmtrl_picker_navigate_to_year_description\fP = 2131624040"
.br
.ti -1c
.RI "const int \fBmtrl_picker_out_of_range\fP = 2131624041"
.br
.ti -1c
.RI "const int \fBmtrl_picker_range_header_only_end_selected\fP = 2131624042"
.br
.ti -1c
.RI "const int \fBmtrl_picker_range_header_only_start_selected\fP = 2131624043"
.br
.ti -1c
.RI "const int \fBmtrl_picker_range_header_selected\fP = 2131624044"
.br
.ti -1c
.RI "const int \fBmtrl_picker_range_header_title\fP = 2131624045"
.br
.ti -1c
.RI "const int \fBmtrl_picker_range_header_unselected\fP = 2131624046"
.br
.ti -1c
.RI "const int \fBmtrl_picker_save\fP = 2131624047"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_date_hint\fP = 2131624048"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_date_range_end_hint\fP = 2131624049"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_date_range_start_hint\fP = 2131624050"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_day_abbr\fP = 2131624051"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_month_abbr\fP = 2131624052"
.br
.ti -1c
.RI "const int \fBmtrl_picker_text_input_year_abbr\fP = 2131624053"
.br
.ti -1c
.RI "const int \fBmtrl_picker_toggle_to_calendar_input_mode\fP = 2131624054"
.br
.ti -1c
.RI "const int \fBmtrl_picker_toggle_to_day_selection\fP = 2131624055"
.br
.ti -1c
.RI "const int \fBmtrl_picker_toggle_to_text_input_mode\fP = 2131624056"
.br
.ti -1c
.RI "const int \fBmtrl_picker_toggle_to_year_selection\fP = 2131624057"
.br
.ti -1c
.RI "const int \fBoverflow_tab_title\fP = 2131624058"
.br
.ti -1c
.RI "const int \fBpassword_toggle_content_description\fP = 2131624059"
.br
.ti -1c
.RI "const int \fBpath_password_eye\fP = 2131624060"
.br
.ti -1c
.RI "const int \fBpath_password_eye_mask_strike_through\fP = 2131624061"
.br
.ti -1c
.RI "const int \fBpath_password_eye_mask_visible\fP = 2131624062"
.br
.ti -1c
.RI "const int \fBpath_password_strike_through\fP = 2131624063"
.br
.ti -1c
.RI "const int \fBproject_id\fP = 2131624064"
.br
.ti -1c
.RI "const int \fBsearch_menu_title\fP = 2131624065"
.br
.ti -1c
.RI "const int \fBstatus_bar_notification_info_overflow\fP = 2131624066"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22966 of file Resource\&.designer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_action_bar_home_description = 2131623936\fC [static]\fP"

.PP
Definition at line 22970 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_action_bar_up_description = 2131623937\fC [static]\fP"

.PP
Definition at line 22973 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_action_menu_overflow_description = 2131623938\fC [static]\fP"

.PP
Definition at line 22976 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_action_mode_done = 2131623939\fC [static]\fP"

.PP
Definition at line 22979 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_activity_chooser_view_see_all = 2131623940\fC [static]\fP"

.PP
Definition at line 22985 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_activitychooserview_choose_application = 2131623941\fC [static]\fP"

.PP
Definition at line 22982 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_capital_off = 2131623942\fC [static]\fP"

.PP
Definition at line 22988 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_capital_on = 2131623943\fC [static]\fP"

.PP
Definition at line 22991 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_alt_shortcut_label = 2131623944\fC [static]\fP"

.PP
Definition at line 22994 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_ctrl_shortcut_label = 2131623945\fC [static]\fP"

.PP
Definition at line 22997 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_delete_shortcut_label = 2131623946\fC [static]\fP"

.PP
Definition at line 23000 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_enter_shortcut_label = 2131623947\fC [static]\fP"

.PP
Definition at line 23003 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_function_shortcut_label = 2131623948\fC [static]\fP"

.PP
Definition at line 23006 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_meta_shortcut_label = 2131623949\fC [static]\fP"

.PP
Definition at line 23009 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_shift_shortcut_label = 2131623950\fC [static]\fP"

.PP
Definition at line 23012 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_space_shortcut_label = 2131623951\fC [static]\fP"

.PP
Definition at line 23015 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_menu_sym_shortcut_label = 2131623952\fC [static]\fP"

.PP
Definition at line 23018 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_prepend_shortcut_label = 2131623953\fC [static]\fP"

.PP
Definition at line 23021 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_search_hint = 2131623954\fC [static]\fP"

.PP
Definition at line 23039 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_searchview_description_clear = 2131623955\fC [static]\fP"

.PP
Definition at line 23024 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_searchview_description_query = 2131623956\fC [static]\fP"

.PP
Definition at line 23027 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_searchview_description_search = 2131623957\fC [static]\fP"

.PP
Definition at line 23030 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_searchview_description_submit = 2131623958\fC [static]\fP"

.PP
Definition at line 23033 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_searchview_description_voice = 2131623959\fC [static]\fP"

.PP
Definition at line 23036 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_shareactionprovider_share_with = 2131623960\fC [static]\fP"

.PP
Definition at line 23042 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_shareactionprovider_share_with_application = 2131623961\fC [static]\fP"

.PP
Definition at line 23045 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.abc_toolbar_collapse_description = 2131623962\fC [static]\fP"

.PP
Definition at line 23048 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.appbar_scrolling_view_behavior = 2131623963\fC [static]\fP"

.PP
Definition at line 23051 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.bottom_sheet_behavior = 2131623964\fC [static]\fP"

.PP
Definition at line 23057 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.bottomsheet_action_expand_halfway = 2131623965\fC [static]\fP"

.PP
Definition at line 23054 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.character_counter_content_description = 2131623966\fC [static]\fP"

.PP
Definition at line 23060 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.character_counter_overflowed_content_description = 2131623967\fC [static]\fP"

.PP
Definition at line 23063 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.character_counter_pattern = 2131623968\fC [static]\fP"

.PP
Definition at line 23066 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.chip_text = 2131623969\fC [static]\fP"

.PP
Definition at line 23069 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.clear_text_end_icon_content_description = 2131623970\fC [static]\fP"

.PP
Definition at line 23072 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_enable_button = 2131623971\fC [static]\fP"

.PP
Definition at line 23075 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_enable_text = 2131623972\fC [static]\fP"

.PP
Definition at line 23078 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_enable_title = 2131623973\fC [static]\fP"

.PP
Definition at line 23081 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_install_button = 2131623974\fC [static]\fP"

.PP
Definition at line 23084 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_install_text = 2131623975\fC [static]\fP"

.PP
Definition at line 23087 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_install_title = 2131623976\fC [static]\fP"

.PP
Definition at line 23090 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_notification_channel_name = 2131623977\fC [static]\fP"

.PP
Definition at line 23093 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_notification_ticker = 2131623978\fC [static]\fP"

.PP
Definition at line 23096 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_unknown_issue = 2131623979\fC [static]\fP"

.PP
Definition at line 23099 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_unsupported_text = 2131623980\fC [static]\fP"

.PP
Definition at line 23102 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_update_button = 2131623981\fC [static]\fP"

.PP
Definition at line 23105 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_update_text = 2131623982\fC [static]\fP"

.PP
Definition at line 23108 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_update_title = 2131623983\fC [static]\fP"

.PP
Definition at line 23111 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_updating_text = 2131623984\fC [static]\fP"

.PP
Definition at line 23114 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_google_play_services_wear_update_text = 2131623985\fC [static]\fP"

.PP
Definition at line 23117 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_open_on_phone = 2131623986\fC [static]\fP"

.PP
Definition at line 23120 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_signin_button_text = 2131623987\fC [static]\fP"

.PP
Definition at line 23123 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.common_signin_button_text_long = 2131623988\fC [static]\fP"

.PP
Definition at line 23126 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.copy_toast_msg = 2131623989\fC [static]\fP"

.PP
Definition at line 23129 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.default_web_client_id = 2131623990\fC [static]\fP"

.PP
Definition at line 23132 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.error_icon_content_description = 2131623991\fC [static]\fP"

.PP
Definition at line 23135 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.exposed_dropdown_menu_content_description = 2131623992\fC [static]\fP"

.PP
Definition at line 23138 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.fab_transformation_scrim_behavior = 2131623993\fC [static]\fP"

.PP
Definition at line 23141 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.fab_transformation_sheet_behavior = 2131623994\fC [static]\fP"

.PP
Definition at line 23144 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.fallback_menu_item_copy_link = 2131623995\fC [static]\fP"

.PP
Definition at line 23147 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.fallback_menu_item_open_in_browser = 2131623996\fC [static]\fP"

.PP
Definition at line 23150 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.fallback_menu_item_share_link = 2131623997\fC [static]\fP"

.PP
Definition at line 23153 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.firebase_database_url = 2131623998\fC [static]\fP"

.PP
Definition at line 23156 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.gcm_defaultSenderId = 2131623999\fC [static]\fP"

.PP
Definition at line 23159 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.google_api_key = 2131624000\fC [static]\fP"

.PP
Definition at line 23162 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.google_app_id = 2131624001\fC [static]\fP"

.PP
Definition at line 23165 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.google_crash_reporting_api_key = 2131624002\fC [static]\fP"

.PP
Definition at line 23168 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.google_storage_bucket = 2131624003\fC [static]\fP"

.PP
Definition at line 23171 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.hide_bottom_view_on_scroll_behavior = 2131624004\fC [static]\fP"

.PP
Definition at line 23174 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.icon_content_description = 2131624005\fC [static]\fP"

.PP
Definition at line 23177 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.item_view_role_description = 2131624006\fC [static]\fP"

.PP
Definition at line 23180 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.library_name = 2131624007\fC [static]\fP"

.PP
Definition at line 23183 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_clock_display_divider = 2131624008\fC [static]\fP"

.PP
Definition at line 23186 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_clock_toggle_content_description = 2131624009\fC [static]\fP"

.PP
Definition at line 23189 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_hour_selection = 2131624010\fC [static]\fP"

.PP
Definition at line 23192 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_hour_suffix = 2131624011\fC [static]\fP"

.PP
Definition at line 23195 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_minute_selection = 2131624012\fC [static]\fP"

.PP
Definition at line 23198 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_minute_suffix = 2131624013\fC [static]\fP"

.PP
Definition at line 23201 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_slider_range_end = 2131624014\fC [static]\fP"

.PP
Definition at line 23204 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_slider_range_start = 2131624015\fC [static]\fP"

.PP
Definition at line 23207 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_am = 2131624016\fC [static]\fP"

.PP
Definition at line 23210 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_clock_mode_description = 2131624017\fC [static]\fP"

.PP
Definition at line 23213 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_hour = 2131624018\fC [static]\fP"

.PP
Definition at line 23216 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_minute = 2131624019\fC [static]\fP"

.PP
Definition at line 23219 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_pm = 2131624020\fC [static]\fP"

.PP
Definition at line 23222 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_select_time = 2131624021\fC [static]\fP"

.PP
Definition at line 23225 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.material_timepicker_text_input_mode_description = 2131624022\fC [static]\fP"

.PP
Definition at line 23228 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_badge_numberless_content_description = 2131624023\fC [static]\fP"

.PP
Definition at line 23231 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_chip_close_icon_content_description = 2131624024\fC [static]\fP"

.PP
Definition at line 23234 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_exceed_max_badge_number_content_description = 2131624025\fC [static]\fP"

.PP
Definition at line 23237 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_exceed_max_badge_number_suffix = 2131624026\fC [static]\fP"

.PP
Definition at line 23240 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_a11y_next_month = 2131624027\fC [static]\fP"

.PP
Definition at line 23243 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_a11y_prev_month = 2131624028\fC [static]\fP"

.PP
Definition at line 23246 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_announce_current_selection = 2131624029\fC [static]\fP"

.PP
Definition at line 23249 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_cancel = 2131624030\fC [static]\fP"

.PP
Definition at line 23252 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_confirm = 2131624031\fC [static]\fP"

.PP
Definition at line 23255 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_date_header_selected = 2131624032\fC [static]\fP"

.PP
Definition at line 23258 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_date_header_title = 2131624033\fC [static]\fP"

.PP
Definition at line 23261 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_date_header_unselected = 2131624034\fC [static]\fP"

.PP
Definition at line 23264 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_day_of_week_column_header = 2131624035\fC [static]\fP"

.PP
Definition at line 23267 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_invalid_format = 2131624036\fC [static]\fP"

.PP
Definition at line 23270 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_invalid_format_example = 2131624037\fC [static]\fP"

.PP
Definition at line 23273 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_invalid_format_use = 2131624038\fC [static]\fP"

.PP
Definition at line 23276 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_invalid_range = 2131624039\fC [static]\fP"

.PP
Definition at line 23279 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_navigate_to_year_description = 2131624040\fC [static]\fP"

.PP
Definition at line 23282 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_out_of_range = 2131624041\fC [static]\fP"

.PP
Definition at line 23285 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_range_header_only_end_selected = 2131624042\fC [static]\fP"

.PP
Definition at line 23288 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_range_header_only_start_selected = 2131624043\fC [static]\fP"

.PP
Definition at line 23291 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_range_header_selected = 2131624044\fC [static]\fP"

.PP
Definition at line 23294 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_range_header_title = 2131624045\fC [static]\fP"

.PP
Definition at line 23297 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_range_header_unselected = 2131624046\fC [static]\fP"

.PP
Definition at line 23300 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_save = 2131624047\fC [static]\fP"

.PP
Definition at line 23303 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_text_input_date_hint = 2131624048\fC [static]\fP"

.PP
Definition at line 23306 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_text_input_date_range_end_hint = 2131624049\fC [static]\fP"

.PP
Definition at line 23309 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_text_input_date_range_start_hint = 2131624050\fC [static]\fP"

.PP
Definition at line 23312 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_text_input_day_abbr = 2131624051\fC [static]\fP"

.PP
Definition at line 23315 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_text_input_month_abbr = 2131624052\fC [static]\fP"

.PP
Definition at line 23318 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_text_input_year_abbr = 2131624053\fC [static]\fP"

.PP
Definition at line 23321 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_toggle_to_calendar_input_mode = 2131624054\fC [static]\fP"

.PP
Definition at line 23324 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_toggle_to_day_selection = 2131624055\fC [static]\fP"

.PP
Definition at line 23327 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_toggle_to_text_input_mode = 2131624056\fC [static]\fP"

.PP
Definition at line 23330 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.mtrl_picker_toggle_to_year_selection = 2131624057\fC [static]\fP"

.PP
Definition at line 23333 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.overflow_tab_title = 2131624058\fC [static]\fP"

.PP
Definition at line 23336 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.password_toggle_content_description = 2131624059\fC [static]\fP"

.PP
Definition at line 23339 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.path_password_eye = 2131624060\fC [static]\fP"

.PP
Definition at line 23342 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.path_password_eye_mask_strike_through = 2131624061\fC [static]\fP"

.PP
Definition at line 23345 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.path_password_eye_mask_visible = 2131624062\fC [static]\fP"

.PP
Definition at line 23348 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.path_password_strike_through = 2131624063\fC [static]\fP"

.PP
Definition at line 23351 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.project_id = 2131624064\fC [static]\fP"

.PP
Definition at line 23354 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.search_menu_title = 2131624065\fC [static]\fP"

.PP
Definition at line 23357 of file Resource\&.designer\&.cs\&.
.SS "const int Application_Green_Quake\&.Droid\&.Resource\&.String\&.status_bar_notification_info_overflow = 2131624066\fC [static]\fP"

.PP
Definition at line 23360 of file Resource\&.designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
