.TH "Application_Green_Quake.Views.ProfilePage.Achievements" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.ProfilePage.Achievements
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.ContentPage, global\&.XamarinForms\&.ContentPage, and ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchievements\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file Achievements\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.ProfilePage\&.Achievements\&.Achievements ()"

.PP
Definition at line 20 of file Achievements\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Application_Green_Quake\&.Views\&.ProfilePage\&.Achievements\&.OnAppearing ()\fC [protected]\fP"
This function is called before the page is displayed\&. It displays the images as the criteria are met 
.PP
Definition at line 28 of file Achievements\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
