.TH "Application_Green_Quake.Views.EcoActions.Travel.PublicTransport" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.EcoActions.Travel.PublicTransport
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.ContentPage, global\&.XamarinForms\&.ContentPage, and ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPublicTransport\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file PublicTransport\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.EcoActions\&.Travel\&.PublicTransport\&.PublicTransport ()"

.PP
Definition at line 21 of file PublicTransport\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Application_Green_Quake\&.Views\&.EcoActions\&.Travel\&.PublicTransport\&.OnAppearing ()\fC [protected]\fP"
This function creates objects and calls their methods\&. First the security methods are called and if they return false call the points updating methods 
.PP
Definition at line 61 of file PublicTransport\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
