.TH "Application_Green_Quake.Views.MainMenu" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.MainMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.TabbedPage, global\&.XamarinForms\&.TabbedPage, and TabbedPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainMenu\fP ()"
.br
.ti -1c
.RI "\fBMainMenu\fP (int tab)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file MainMenu\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.MainMenu\&.MainMenu ()"

.PP
Definition at line 25 of file MainMenu\&.xaml\&.cs\&.
.SS "Application_Green_Quake\&.Views\&.MainMenu\&.MainMenu (int tab)"
\fBThe\fP constructor for Main menu 
.PP
\fBParameters\fP
.RS 4
\fItab\fP supplied to tell the class which tabbed page to display\&. 
.RE
.PP

.PP
Definition at line 35 of file MainMenu\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async void Application_Green_Quake\&.Views\&.MainMenu\&.OnAppearing ()\fC [protected]\fP"
This function is called before the page is displayed\&. 
.PP
Definition at line 69 of file MainMenu\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
