.TH "Application_Green_Quake.Models.LeaderBoard" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Models.LeaderBoard
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "ImageSource \fBimage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBusername\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBpoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBrank\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbio\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBnation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBuid\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file LeaderBoard\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Application_Green_Quake\&.Models\&.LeaderBoard\&.bio\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file LeaderBoard\&.cs\&.
.SS "ImageSource Application_Green_Quake\&.Models\&.LeaderBoard\&.image\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 15 of file LeaderBoard\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.LeaderBoard\&.nation\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file LeaderBoard\&.cs\&.
.SS "int Application_Green_Quake\&.Models\&.LeaderBoard\&.points\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 17 of file LeaderBoard\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.LeaderBoard\&.rank\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 18 of file LeaderBoard\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.LeaderBoard\&.uid\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 21 of file LeaderBoard\&.cs\&.
.SS "string Application_Green_Quake\&.Models\&.LeaderBoard\&.username\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file LeaderBoard\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
