.TH "Application_Green_Quake.ViewModels.PointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.PointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBUpdateByTenPoints\fP ()"
.br
.ti -1c
.RI "async void \fBUpdateByEightPoints\fP ()"
.br
.ti -1c
.RI "async void \fBUpdateBySixPoints\fP ()"
.br
.ti -1c
.RI "async void \fBUpdateByFourPoints\fP ()"
.br
.ti -1c
.RI "async void \fBUpdateByTwoPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file PointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.PointsUpdate\&.UpdateByEightPoints ()"
This function increases the points of a user by eight points\&. It also stores the current date and time under the Security Checks node and also increments the security counter if the point update is on the same day and if it is not then it sets it to zero\&. 
.PP
Definition at line 131 of file PointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.PointsUpdate\&.UpdateByFourPoints ()"
This function increases the points of a user by four points\&. It also stores the current date and time under the Security Checks node and also increments the security counter if the point update is on the same day and if it is not then it sets it to zero\&. 
.PP
Definition at line 326 of file PointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.PointsUpdate\&.UpdateBySixPoints ()"
This function increases the points of a user by six points\&. It also stores the current date and time under the Security Checks node and also increments the security counter if the point update is on the same day and if it is not then it sets it to zero\&. 
.PP
Definition at line 228 of file PointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.PointsUpdate\&.UpdateByTenPoints ()"
This function increases the points of a user by ten points\&. It also stores the current date and time under the Security Checks node and also increments the security counter if the point update is on the same day and if it is not then it sets it to zero\&. 
.PP
Definition at line 33 of file PointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.PointsUpdate\&.UpdateByTwoPoints ()"
This function increases the points of a user by two points\&. It also stores the current date and time under the Security Checks node and also increments the security counter if the point update is on the same day and if it is not then it sets it to zero\&. 
.PP
Definition at line 424 of file PointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
