.TH "Application_Green_Quake.iOS.AppDelegate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.iOS.AppDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.Platform\&.iOS\&.FormsApplicationDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBFinishedLaunching\fP (UIApplication app, NSDictionary options)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file AppDelegate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Application_Green_Quake\&.iOS\&.AppDelegate\&.FinishedLaunching (UIApplication app, NSDictionary options)"

.PP
Definition at line 20 of file AppDelegate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
