.TH "Application_Green_Quake.ViewModels.TravelPointsUpdate" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.ViewModels.TravelPointsUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBCarpoolPoints\fP ()"
.br
.ti -1c
.RI "async void \fBCyclePoints\fP ()"
.br
.ti -1c
.RI "async void \fBEcoCarPoints\fP ()"
.br
.ti -1c
.RI "async void \fBTransportPoints\fP ()"
.br
.ti -1c
.RI "async void \fBWalkPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file TravelPointsUpdate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Application_Green_Quake\&.ViewModels\&.TravelPointsUpdate\&.CarpoolPoints ()"
This function updates the points in the Travel category by six points\&. It also increments the number of logs logged in the Travel category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 35 of file TravelPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.TravelPointsUpdate\&.CyclePoints ()"
This function updates the points in the Travel category by ten points\&. It also increments the number of logs logged in the Travel category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 135 of file TravelPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.TravelPointsUpdate\&.EcoCarPoints ()"
This function updates the points in the Travel category by ten points\&. It also increments the number of logs logged in the Travel category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 235 of file TravelPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.TravelPointsUpdate\&.TransportPoints ()"
This function updates the points in the Travel category by eight points\&. It also increments the number of logs logged in the Travel category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 335 of file TravelPointsUpdate\&.cs\&.
.SS "async void Application_Green_Quake\&.ViewModels\&.TravelPointsUpdate\&.WalkPoints ()"
This function updates the points in the Travel category by ten points\&. It also increments the number of logs logged in the Travel category by one and increments the number of times this particular action was logged by one and sends this data to Firebase\&. 
.PP
Definition at line 435 of file TravelPointsUpdate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
