.TH "Application_Green_Quake.Views.LeaderboardPage.TopTabLeaderBoard" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application_Green_Quake.Views.LeaderboardPage.TopTabLeaderBoard
.SH SYNOPSIS
.br
.PP
.PP
Inherits global\&.XamarinForms\&.ContentPage, global\&.XamarinForms\&.ContentPage, and ContentPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTopTabLeaderBoard\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async void \fBOnAppearing\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file TopTabLeaderBoard\&.xaml\&.g\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application_Green_Quake\&.Views\&.LeaderboardPage\&.TopTabLeaderBoard\&.TopTabLeaderBoard ()"

.PP
Definition at line 32 of file TopTabLeaderBoard\&.xaml\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override async void Application_Green_Quake\&.Views\&.LeaderboardPage\&.TopTabLeaderBoard\&.OnAppearing ()\fC [protected]\fP"
This function is called before the page is displayed\&. 
.PP
Definition at line 98 of file TopTabLeaderBoard\&.xaml\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
