.TH "Application Green Quake/obj Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.ti -1c
.RI "directory \fBRelease\fP"
.br
.in -1c
