.TH "Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions/Waste Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions/Waste Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBillsOnline\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompostWaste\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBSetUpRecyclingBin\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBUseBiogradableBinBags\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBUseRecyclingBin\&.xaml\&.g\&.cs\fP"
.br
.in -1c
