.TH "Application Green Quake/obj/Release/netstandard2.0/Views/ProfilePage Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Release/netstandard2.0/Views/ProfilePage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAchievements\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBBadgePopUp\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBBadges\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBTopTabProfile\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBTrophyCase\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBUploadImagePopUp\&.xaml\&.g\&.cs\fP"
.br
.in -1c
