.TH "Application Green Quake.Android/obj/Debug/100/android/src/crc64435a5ac349fa9fda Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/100/android/src/crc64435a5ac349fa9fda Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActivityLifecycleContextListener\&.java\fP"
.br
.in -1c
