.TH "Application Green Quake/Views/EcoActions/FoodAndDrink Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/FoodAndDrink Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuyOrganicFood\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBEatAllYouMake\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBFoodDelivered\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBNoMeat\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBOwnCoffee\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBReCoffeeMug\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSaveLeftOvers\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSteelStraw\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBWaterOverFizzy\&.xaml\&.cs\fP"
.br
.in -1c
