.TH "Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions/Travel Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Debug/netstandard2.0/Views/EcoActions/Travel Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCarpool\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBCycle\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBEcoFreindlyCar\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBPublicTransport\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBWalk\&.xaml\&.g\&.cs\fP"
.br
.in -1c
