.TH "Application Green Quake.Android/obj/Release/110/android/src/androidx/browser/customtabs Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/androidx/browser/customtabs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCustomTabsClient_CustomTabsCallbackImpl\&.java\fP"
.br
.in -1c
