.TH "Application Green Quake/Views/EcoActions/EcoActionsSubMenu Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/EcoActionsSubMenu Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAdvancedPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBCommunityPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBEnergyPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBFoodAndDrinkPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBHabitsPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBHomePage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBOutdoorsPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBShoppingPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBTravelPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBWastePage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBWaterPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBWorkPage\&.xaml\&.cs\fP"
.br
.in -1c
