.TH "Application Green Quake/Views/EcoActions/Energy Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/EcoActions/Energy Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDryerFull\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBEfficientThermostat\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBHangDry\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBInsulateWater\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBIsolateHome\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBLedLightbulb\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMachineFull\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMicrowaveNotOven\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBOffSocketSwitch\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBReBatteries\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBRefrigiratorDown\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSealDrafts\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSealDucts\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolarPanel\&.xaml\&.cs\fP"
.br
.in -1c
