.TH "Application Green Quake/obj/Debug/netstandard2.0/html/search Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Debug/netstandard2.0/html/search Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsearch\&.css\&.g\&.cs\fP"
.br
.in -1c
