.TH "Application Green Quake/obj/Release/netstandard2.0/Views/EcoActions/Water Directory Reference" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Release/netstandard2.0/Views/EcoActions/Water Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCisternDisplacement\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBRainBarrel\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBReusableWater\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBShowerBucket\&.xaml\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBWSShowerHead\&.xaml\&.g\&.cs\fP"
.br
.in -1c
