.TH "crc643f46942d9dd1fff9.ShellSearchViewAdapter_CustomFilter" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.ShellSearchViewAdapter_CustomFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.widget\&.Filter, mono\&.android\&.IGCUserPeer, android\&.widget\&.Filter, mono\&.android\&.IGCUserPeer, android\&.widget\&.Filter, mono\&.android\&.IGCUserPeer, android\&.widget\&.Filter, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP (android\&.widget\&.BaseAdapter p0)"
.br
.ti -1c
.RI "android\&.widget\&.Filter\&.FilterResults \fBperformFiltering\fP (java\&.lang\&.CharSequence p0)"
.br
.ti -1c
.RI "void \fBpublishResults\fP (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP (android\&.widget\&.BaseAdapter p0)"
.br
.ti -1c
.RI "android\&.widget\&.Filter\&.FilterResults \fBperformFiltering\fP (java\&.lang\&.CharSequence p0)"
.br
.ti -1c
.RI "void \fBpublishResults\fP (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP (android\&.widget\&.BaseAdapter p0)"
.br
.ti -1c
.RI "android\&.widget\&.Filter\&.FilterResults \fBperformFiltering\fP (java\&.lang\&.CharSequence p0)"
.br
.ti -1c
.RI "void \fBpublishResults\fP (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP ()"
.br
.ti -1c
.RI "\fBShellSearchViewAdapter_CustomFilter\fP (android\&.widget\&.BaseAdapter p0)"
.br
.ti -1c
.RI "android\&.widget\&.Filter\&.FilterResults \fBperformFiltering\fP (java\&.lang\&.CharSequence p0)"
.br
.ti -1c
.RI "void \fBpublishResults\fP (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter ()"

.PP
Definition at line 20 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter (android\&.widget\&.BaseAdapter p0)"

.PP
Definition at line 27 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter ()"

.PP
Definition at line 20 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter (android\&.widget\&.BaseAdapter p0)"

.PP
Definition at line 27 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter ()"

.PP
Definition at line 20 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter (android\&.widget\&.BaseAdapter p0)"

.PP
Definition at line 27 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter ()"

.PP
Definition at line 20 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.ShellSearchViewAdapter_CustomFilter (android\&.widget\&.BaseAdapter p0)"

.PP
Definition at line 27 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "android\&.widget\&.Filter\&.FilterResults crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.performFiltering (java\&.lang\&.CharSequence p0)"

.PP
Definition at line 35 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "android\&.widget\&.Filter\&.FilterResults crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.performFiltering (java\&.lang\&.CharSequence p0)"

.PP
Definition at line 35 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "android\&.widget\&.Filter\&.FilterResults crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.performFiltering (java\&.lang\&.CharSequence p0)"

.PP
Definition at line 35 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "android\&.widget\&.Filter\&.FilterResults crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.performFiltering (java\&.lang\&.CharSequence p0)"

.PP
Definition at line 35 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.publishResults (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"

.PP
Definition at line 43 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.publishResults (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"

.PP
Definition at line 43 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.publishResults (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"

.PP
Definition at line 43 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.publishResults (java\&.lang\&.CharSequence p0, android\&.widget\&.Filter\&.FilterResults p1)"

.PP
Definition at line 43 of file ShellSearchViewAdapter_CustomFilter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.ShellSearchViewAdapter_CustomFilter\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file ShellSearchViewAdapter_CustomFilter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
