.TH "crc64692a67b1ffd85ce9.ActivityLifecycleCallbacks" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64692a67b1ffd85ce9.ActivityLifecycleCallbacks
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.app\&.Application\&.ActivityLifecycleCallbacks, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.app\&.Application\&.ActivityLifecycleCallbacks, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.app\&.Application\&.ActivityLifecycleCallbacks, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and android\&.app\&.Application\&.ActivityLifecycleCallbacks\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivityLifecycleCallbacks\fP ()"
.br
.ti -1c
.RI "void \fBonActivityCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivitySaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBActivityLifecycleCallbacks\fP ()"
.br
.ti -1c
.RI "void \fBonActivityCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivitySaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPostDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostPaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostSaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPostStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPreDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPrePaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreSaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPreStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBActivityLifecycleCallbacks\fP ()"
.br
.ti -1c
.RI "void \fBonActivityCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivitySaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBActivityLifecycleCallbacks\fP ()"
.br
.ti -1c
.RI "void \fBonActivityCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivitySaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPostDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostPaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostSaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPostStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPostStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreCreated\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPreDestroyed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPrePaused\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreResumed\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreSaveInstanceState\fP (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"
.br
.ti -1c
.RI "void \fBonActivityPreStarted\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBonActivityPreStopped\fP (android\&.app\&.Activity p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ActivityLifecycleCallbacks\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.ActivityLifecycleCallbacks ()"

.PP
Definition at line 26 of file ActivityLifecycleCallbacks\&.java\&.
.SS "crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.ActivityLifecycleCallbacks ()"

.PP
Definition at line 40 of file ActivityLifecycleCallbacks\&.java\&.
.SS "crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.ActivityLifecycleCallbacks ()"

.PP
Definition at line 26 of file ActivityLifecycleCallbacks\&.java\&.
.SS "crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.ActivityLifecycleCallbacks ()"

.PP
Definition at line 40 of file ActivityLifecycleCallbacks\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 90 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 216 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 90 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 216 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidClearReferences ()"

.PP
Definition at line 97 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidClearReferences ()"

.PP
Definition at line 223 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidClearReferences ()"

.PP
Definition at line 97 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.monodroidClearReferences ()"

.PP
Definition at line 223 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 34 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 48 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 34 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 48 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 42 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 56 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 42 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 56 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPaused (android\&.app\&.Activity p0)"

.PP
Definition at line 50 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPaused (android\&.app\&.Activity p0)"

.PP
Definition at line 64 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPaused (android\&.app\&.Activity p0)"

.PP
Definition at line 50 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPaused (android\&.app\&.Activity p0)"

.PP
Definition at line 64 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 104 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 104 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 112 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 112 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostPaused (android\&.app\&.Activity p0)"

.PP
Definition at line 120 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostPaused (android\&.app\&.Activity p0)"

.PP
Definition at line 120 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 128 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 128 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostSaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 136 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostSaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 136 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 144 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 144 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 152 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPostStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 152 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 160 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreCreated (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 160 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 168 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreDestroyed (android\&.app\&.Activity p0)"

.PP
Definition at line 168 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPrePaused (android\&.app\&.Activity p0)"

.PP
Definition at line 176 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPrePaused (android\&.app\&.Activity p0)"

.PP
Definition at line 176 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 184 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 184 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreSaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 192 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreSaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 192 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 200 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 200 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 208 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityPreStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 208 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 58 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 72 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 58 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityResumed (android\&.app\&.Activity p0)"

.PP
Definition at line 72 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivitySaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 66 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivitySaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 80 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivitySaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 66 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivitySaveInstanceState (android\&.app\&.Activity p0, android\&.os\&.Bundle p1)"

.PP
Definition at line 80 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 74 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 88 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 74 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStarted (android\&.app\&.Activity p0)"

.PP
Definition at line 88 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 82 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 96 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 82 of file ActivityLifecycleCallbacks\&.java\&.
.SS "void crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.onActivityStopped (android\&.app\&.Activity p0)"

.PP
Definition at line 96 of file ActivityLifecycleCallbacks\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64692a67b1ffd85ce9\&.ActivityLifecycleCallbacks\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file ActivityLifecycleCallbacks\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
