.TH "crc64a0e0a82d0db9a07d.MagnetometerListener" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a0e0a82d0db9a07d.MagnetometerListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.hardware\&.SensorEventListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.hardware\&.SensorEventListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, android\&.hardware\&.SensorEventListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and android\&.hardware\&.SensorEventListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMagnetometerListener\fP ()"
.br
.ti -1c
.RI "void \fBonAccuracyChanged\fP (android\&.hardware\&.Sensor p0, int p1)"
.br
.ti -1c
.RI "void \fBonSensorChanged\fP (android\&.hardware\&.SensorEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBMagnetometerListener\fP ()"
.br
.ti -1c
.RI "void \fBonAccuracyChanged\fP (android\&.hardware\&.Sensor p0, int p1)"
.br
.ti -1c
.RI "void \fBonSensorChanged\fP (android\&.hardware\&.SensorEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBMagnetometerListener\fP ()"
.br
.ti -1c
.RI "void \fBonAccuracyChanged\fP (android\&.hardware\&.Sensor p0, int p1)"
.br
.ti -1c
.RI "void \fBonSensorChanged\fP (android\&.hardware\&.SensorEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBMagnetometerListener\fP ()"
.br
.ti -1c
.RI "void \fBonAccuracyChanged\fP (android\&.hardware\&.Sensor p0, int p1)"
.br
.ti -1c
.RI "void \fBonSensorChanged\fP (android\&.hardware\&.SensorEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file MagnetometerListener\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.MagnetometerListener ()"

.PP
Definition at line 21 of file MagnetometerListener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.MagnetometerListener ()"

.PP
Definition at line 21 of file MagnetometerListener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.MagnetometerListener ()"

.PP
Definition at line 21 of file MagnetometerListener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.MagnetometerListener ()"

.PP
Definition at line 21 of file MagnetometerListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onAccuracyChanged (android\&.hardware\&.Sensor p0, int p1)"

.PP
Definition at line 29 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onAccuracyChanged (android\&.hardware\&.Sensor p0, int p1)"

.PP
Definition at line 29 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onAccuracyChanged (android\&.hardware\&.Sensor p0, int p1)"

.PP
Definition at line 29 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onAccuracyChanged (android\&.hardware\&.Sensor p0, int p1)"

.PP
Definition at line 29 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onSensorChanged (android\&.hardware\&.SensorEvent p0)"

.PP
Definition at line 37 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onSensorChanged (android\&.hardware\&.SensorEvent p0)"

.PP
Definition at line 37 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onSensorChanged (android\&.hardware\&.SensorEvent p0)"

.PP
Definition at line 37 of file MagnetometerListener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.onSensorChanged (android\&.hardware\&.SensorEvent p0)"

.PP
Definition at line 37 of file MagnetometerListener\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64a0e0a82d0db9a07d\&.MagnetometerListener\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file MagnetometerListener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
