.TH "crc643f46942d9dd1fff9.TemplatedItemViewHolder" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.TemplatedItemViewHolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTemplatedItemViewHolder\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBTemplatedItemViewHolder\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBTemplatedItemViewHolder\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBTemplatedItemViewHolder\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TemplatedItemViewHolder\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.TemplatedItemViewHolder (android\&.view\&.View p0)"

.PP
Definition at line 18 of file TemplatedItemViewHolder\&.java\&.
.SS "crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.TemplatedItemViewHolder (android\&.view\&.View p0)"

.PP
Definition at line 18 of file TemplatedItemViewHolder\&.java\&.
.SS "crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.TemplatedItemViewHolder (android\&.view\&.View p0)"

.PP
Definition at line 18 of file TemplatedItemViewHolder\&.java\&.
.SS "crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.TemplatedItemViewHolder (android\&.view\&.View p0)"

.PP
Definition at line 18 of file TemplatedItemViewHolder\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 26 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 26 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 26 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 26 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 33 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 33 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 33 of file TemplatedItemViewHolder\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.SelectableViewHolder\fP\&.
.PP
Definition at line 33 of file TemplatedItemViewHolder\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.TemplatedItemViewHolder\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file TemplatedItemViewHolder\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
