.TH "crc64a0e0a82d0db9a07d.Listener" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a0e0a82d0db9a07d.Listener
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.view\&.OrientationEventListener, mono\&.android\&.IGCUserPeer, android\&.view\&.OrientationEventListener, mono\&.android\&.IGCUserPeer, android\&.view\&.OrientationEventListener, mono\&.android\&.IGCUserPeer, android\&.view\&.OrientationEventListener, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0, int p1)"
.br
.ti -1c
.RI "void \fBonOrientationChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0, int p1)"
.br
.ti -1c
.RI "void \fBonOrientationChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0, int p1)"
.br
.ti -1c
.RI "void \fBonOrientationChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBListener\fP (android\&.content\&.Context p0, int p1)"
.br
.ti -1c
.RI "void \fBonOrientationChanged\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Listener\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0, int p1)"

.PP
Definition at line 27 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0, int p1)"

.PP
Definition at line 27 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0, int p1)"

.PP
Definition at line 27 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file Listener\&.java\&.
.SS "crc64a0e0a82d0db9a07d\&.Listener\&.Listener (android\&.content\&.Context p0, int p1)"

.PP
Definition at line 27 of file Listener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.onOrientationChanged (int p0)"

.PP
Definition at line 35 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.onOrientationChanged (int p0)"

.PP
Definition at line 35 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.onOrientationChanged (int p0)"

.PP
Definition at line 35 of file Listener\&.java\&.
.SS "void crc64a0e0a82d0db9a07d\&.Listener\&.onOrientationChanged (int p0)"

.PP
Definition at line 35 of file Listener\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64a0e0a82d0db9a07d\&.Listener\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file Listener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
