.TH "crc643f46942d9dd1fff9.GradientStrokeDrawable" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.GradientStrokeDrawable
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.graphics\&.drawable\&.PaintDrawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.PaintDrawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.PaintDrawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.PaintDrawable, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGradientStrokeDrawable\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP ()"
.br
.ti -1c
.RI "\fBGradientStrokeDrawable\fP (int p0)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file GradientStrokeDrawable\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable ()"

.PP
Definition at line 19 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable (int p0)"

.PP
Definition at line 27 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable ()"

.PP
Definition at line 19 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable (int p0)"

.PP
Definition at line 27 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable ()"

.PP
Definition at line 19 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable (int p0)"

.PP
Definition at line 27 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable ()"

.PP
Definition at line 19 of file GradientStrokeDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.GradientStrokeDrawable (int p0)"

.PP
Definition at line 27 of file GradientStrokeDrawable\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 43 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 50 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.onDraw (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"

.PP
Definition at line 35 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.onDraw (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"

.PP
Definition at line 35 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.onDraw (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"

.PP
Definition at line 35 of file GradientStrokeDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.onDraw (android\&.graphics\&.drawable\&.shapes\&.Shape p0, android\&.graphics\&.Canvas p1, android\&.graphics\&.Paint p2)"

.PP
Definition at line 35 of file GradientStrokeDrawable\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.GradientStrokeDrawable\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file GradientStrokeDrawable\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
