.TH "crc643f46942d9dd1fff9.BorderDrawable" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.BorderDrawable
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.graphics\&.drawable\&.Drawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.Drawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.Drawable, mono\&.android\&.IGCUserPeer, android\&.graphics\&.drawable\&.Drawable, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBorderDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisStateful\fP ()"
.br
.ti -1c
.RI "int \fBgetOpacity\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (int p0)"
.br
.ti -1c
.RI "void \fBsetColorFilter\fP (android\&.graphics\&.ColorFilter p0)"
.br
.ti -1c
.RI "boolean \fBonStateChange\fP (int[] p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBBorderDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisStateful\fP ()"
.br
.ti -1c
.RI "int \fBgetOpacity\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (int p0)"
.br
.ti -1c
.RI "void \fBsetColorFilter\fP (android\&.graphics\&.ColorFilter p0)"
.br
.ti -1c
.RI "boolean \fBonStateChange\fP (int[] p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBBorderDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisStateful\fP ()"
.br
.ti -1c
.RI "int \fBgetOpacity\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (int p0)"
.br
.ti -1c
.RI "void \fBsetColorFilter\fP (android\&.graphics\&.ColorFilter p0)"
.br
.ti -1c
.RI "boolean \fBonStateChange\fP (int[] p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBBorderDrawable\fP ()"
.br
.ti -1c
.RI "boolean \fBisStateful\fP ()"
.br
.ti -1c
.RI "int \fBgetOpacity\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (int p0)"
.br
.ti -1c
.RI "void \fBsetColorFilter\fP (android\&.graphics\&.ColorFilter p0)"
.br
.ti -1c
.RI "boolean \fBonStateChange\fP (int[] p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file BorderDrawable\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.BorderDrawable\&.BorderDrawable ()"

.PP
Definition at line 24 of file BorderDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.BorderDrawable\&.BorderDrawable ()"

.PP
Definition at line 24 of file BorderDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.BorderDrawable\&.BorderDrawable ()"

.PP
Definition at line 24 of file BorderDrawable\&.java\&.
.SS "crc643f46942d9dd1fff9\&.BorderDrawable\&.BorderDrawable ()"

.PP
Definition at line 24 of file BorderDrawable\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.draw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 48 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.draw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 48 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.draw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 48 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.draw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 48 of file BorderDrawable\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.BorderDrawable\&.getOpacity ()"

.PP
Definition at line 40 of file BorderDrawable\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.BorderDrawable\&.getOpacity ()"

.PP
Definition at line 40 of file BorderDrawable\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.BorderDrawable\&.getOpacity ()"

.PP
Definition at line 40 of file BorderDrawable\&.java\&.
.SS "int crc643f46942d9dd1fff9\&.BorderDrawable\&.getOpacity ()"

.PP
Definition at line 40 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.isStateful ()"

.PP
Definition at line 32 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.isStateful ()"

.PP
Definition at line 32 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.isStateful ()"

.PP
Definition at line 32 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.isStateful ()"

.PP
Definition at line 32 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 80 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 80 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 80 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 80 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 87 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 87 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 87 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.monodroidClearReferences ()"

.PP
Definition at line 87 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.onStateChange (int[] p0)"

.PP
Definition at line 72 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.onStateChange (int[] p0)"

.PP
Definition at line 72 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.onStateChange (int[] p0)"

.PP
Definition at line 72 of file BorderDrawable\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.BorderDrawable\&.onStateChange (int[] p0)"

.PP
Definition at line 72 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setAlpha (int p0)"

.PP
Definition at line 56 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setAlpha (int p0)"

.PP
Definition at line 56 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setAlpha (int p0)"

.PP
Definition at line 56 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setAlpha (int p0)"

.PP
Definition at line 56 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setColorFilter (android\&.graphics\&.ColorFilter p0)"

.PP
Definition at line 64 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setColorFilter (android\&.graphics\&.ColorFilter p0)"

.PP
Definition at line 64 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setColorFilter (android\&.graphics\&.ColorFilter p0)"

.PP
Definition at line 64 of file BorderDrawable\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.BorderDrawable\&.setColorFilter (android\&.graphics\&.ColorFilter p0)"

.PP
Definition at line 64 of file BorderDrawable\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.BorderDrawable\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file BorderDrawable\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
