.TH "crc643f46942d9dd1fff9.ScrollLayoutManager" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.ScrollLayoutManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.recyclerview\&.widget\&.LinearLayoutManager, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.LinearLayoutManager, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.LinearLayoutManager, mono\&.android\&.IGCUserPeer, androidx\&.recyclerview\&.widget\&.LinearLayoutManager, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, int p1, boolean p2)"
.br
.ti -1c
.RI "boolean \fBcanScrollVertically\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, int p1, boolean p2)"
.br
.ti -1c
.RI "boolean \fBcanScrollVertically\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, int p1, boolean p2)"
.br
.ti -1c
.RI "boolean \fBcanScrollVertically\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "\fBScrollLayoutManager\fP (android\&.content\&.Context p0, int p1, boolean p2)"
.br
.ti -1c
.RI "boolean \fBcanScrollVertically\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ScrollLayoutManager\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 27 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, int p1, boolean p2)"

.PP
Definition at line 35 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 27 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, int p1, boolean p2)"

.PP
Definition at line 35 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 27 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, int p1, boolean p2)"

.PP
Definition at line 35 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 27 of file ScrollLayoutManager\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.ScrollLayoutManager (android\&.content\&.Context p0, int p1, boolean p2)"

.PP
Definition at line 35 of file ScrollLayoutManager\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.canScrollVertically ()"

.PP
Definition at line 43 of file ScrollLayoutManager\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.canScrollVertically ()"

.PP
Definition at line 43 of file ScrollLayoutManager\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.canScrollVertically ()"

.PP
Definition at line 43 of file ScrollLayoutManager\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.canScrollVertically ()"

.PP
Definition at line 43 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ScrollLayoutManager\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ScrollLayoutManager\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.ScrollLayoutManager\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file ScrollLayoutManager\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
