.TH "crc64d32ffa835eadac0e" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64d32ffa835eadac0e
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDelegateCancelableCallback\fP"
.br
.ti -1c
.RI "class \fBDelegateSnapshotReadyCallback\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
