.TH "crc643f46942d9dd1fff9.FormsApplicationActivity" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.FormsApplicationActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, android\&.app\&.Activity, mono\&.android\&.IGCUserPeer, android\&.app\&.Activity, and mono\&.android\&.IGCUserPeer\&.
.PP
Inherited by \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormsApplicationActivity\fP ()"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "boolean \fBonPrepareOptionsMenu\fP (android\&.view\&.Menu p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsApplicationActivity\fP ()"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "boolean \fBonPrepareOptionsMenu\fP (android\&.view\&.Menu p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsApplicationActivity\fP ()"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "boolean \fBonPrepareOptionsMenu\fP (android\&.view\&.Menu p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsApplicationActivity\fP ()"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "boolean \fBonPrepareOptionsMenu\fP (android\&.view\&.Menu p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file FormsApplicationActivity\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.FormsApplicationActivity ()"

.PP
Definition at line 30 of file FormsApplicationActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.FormsApplicationActivity ()"

.PP
Definition at line 30 of file FormsApplicationActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.FormsApplicationActivity ()"

.PP
Definition at line 30 of file FormsApplicationActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.FormsApplicationActivity ()"

.PP
Definition at line 30 of file FormsApplicationActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 134 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 134 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 134 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 134 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 141 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 141 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 141 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP, and \fBcrc643f46942d9dd1fff9\&.AndroidActivity\fP\&.
.PP
Definition at line 141 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onBackPressed ()"

.PP
Definition at line 38 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onBackPressed ()"

.PP
Definition at line 38 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onBackPressed ()"

.PP
Definition at line 38 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onBackPressed ()"

.PP
Definition at line 38 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 46 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 46 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 46 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 46 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 78 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 78 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 78 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Definition at line 78 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 54 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 54 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 54 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 54 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPause ()"

.PP
Definition at line 94 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPause ()"

.PP
Definition at line 94 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPause ()"

.PP
Definition at line 94 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPause ()"

.PP
Definition at line 94 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPrepareOptionsMenu (android\&.view\&.Menu p0)"

.PP
Definition at line 62 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPrepareOptionsMenu (android\&.view\&.Menu p0)"

.PP
Definition at line 62 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPrepareOptionsMenu (android\&.view\&.Menu p0)"

.PP
Definition at line 62 of file FormsApplicationActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onPrepareOptionsMenu (android\&.view\&.Menu p0)"

.PP
Definition at line 62 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onRestart ()"

.PP
Definition at line 102 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onRestart ()"

.PP
Definition at line 102 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onRestart ()"

.PP
Definition at line 102 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onRestart ()"

.PP
Definition at line 102 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onResume ()"

.PP
Definition at line 110 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onResume ()"

.PP
Definition at line 110 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onResume ()"

.PP
Definition at line 110 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onResume ()"

.PP
Definition at line 110 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStart ()"

.PP
Definition at line 118 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStart ()"

.PP
Definition at line 118 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStart ()"

.PP
Definition at line 118 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStart ()"

.PP
Definition at line 118 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStop ()"

.PP
Definition at line 126 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStop ()"

.PP
Definition at line 126 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStop ()"

.PP
Definition at line 126 of file FormsApplicationActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.onStop ()"

.PP
Definition at line 126 of file FormsApplicationActivity\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.FormsApplicationActivity\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file FormsApplicationActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
