.TH "crc643f46942d9dd1fff9.ShellPageContainer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.ShellPageContainer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.PageContainer\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.PageContainer\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.PageContainer\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.PageContainer\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBShellPageContainer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ShellPageContainer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellPageContainer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellPageContainer\&.ShellPageContainer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 43 of file ShellPageContainer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 59 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 59 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 59 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 59 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 66 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 66 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 66 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 66 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 51 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 51 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 51 of file ShellPageContainer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellPageContainer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageContainer\fP\&.
.PP
Definition at line 51 of file ShellPageContainer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.ShellPageContainer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file ShellPageContainer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
