.TH "crc646e4e3ae19170bac3.DroidSyncTileLayer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc646e4e3ae19170bac3.DroidSyncTileLayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.model\&.TileProvider, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.model\&.TileProvider, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.model\&.TileProvider, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.google\&.android\&.gms\&.maps\&.model\&.TileProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDroidSyncTileLayer\fP ()"
.br
.ti -1c
.RI "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile \fBgetTile\fP (int p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDroidSyncTileLayer\fP ()"
.br
.ti -1c
.RI "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile \fBgetTile\fP (int p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDroidSyncTileLayer\fP ()"
.br
.ti -1c
.RI "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile \fBgetTile\fP (int p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDroidSyncTileLayer\fP ()"
.br
.ti -1c
.RI "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile \fBgetTile\fP (int p0, int p1, int p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file DroidSyncTileLayer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.DroidSyncTileLayer ()"

.PP
Definition at line 20 of file DroidSyncTileLayer\&.java\&.
.SS "crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.DroidSyncTileLayer ()"

.PP
Definition at line 20 of file DroidSyncTileLayer\&.java\&.
.SS "crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.DroidSyncTileLayer ()"

.PP
Definition at line 20 of file DroidSyncTileLayer\&.java\&.
.SS "crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.DroidSyncTileLayer ()"

.PP
Definition at line 20 of file DroidSyncTileLayer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.getTile (int p0, int p1, int p2)"

.PP
Definition at line 28 of file DroidSyncTileLayer\&.java\&.
.SS "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.getTile (int p0, int p1, int p2)"

.PP
Definition at line 28 of file DroidSyncTileLayer\&.java\&.
.SS "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.getTile (int p0, int p1, int p2)"

.PP
Definition at line 28 of file DroidSyncTileLayer\&.java\&.
.SS "com\&.google\&.android\&.gms\&.maps\&.model\&.Tile crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.getTile (int p0, int p1, int p2)"

.PP
Definition at line 28 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DroidSyncTileLayer\&.java\&.
.SS "void crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DroidSyncTileLayer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc646e4e3ae19170bac3\&.DroidSyncTileLayer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file DroidSyncTileLayer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
