.TH "crc640879981a986d658b.SfGradientViewRenderer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc640879981a986d658b.SfGradientViewRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.ViewRenderer\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSfGradientViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSfGradientViewRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSfGradientViewRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file SfGradientViewRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc640879981a986d658b\&.SfGradientViewRenderer\&.SfGradientViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 19 of file SfGradientViewRenderer\&.java\&.
.SS "crc640879981a986d658b\&.SfGradientViewRenderer\&.SfGradientViewRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file SfGradientViewRenderer\&.java\&.
.SS "crc640879981a986d658b\&.SfGradientViewRenderer\&.SfGradientViewRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 35 of file SfGradientViewRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc640879981a986d658b\&.SfGradientViewRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer\fP\&.
.PP
Definition at line 51 of file SfGradientViewRenderer\&.java\&.
.SS "void crc640879981a986d658b\&.SfGradientViewRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer\fP\&.
.PP
Definition at line 58 of file SfGradientViewRenderer\&.java\&.
.SS "void crc640879981a986d658b\&.SfGradientViewRenderer\&.onDraw (android\&.graphics\&.Canvas p0)"

.PP
Definition at line 43 of file SfGradientViewRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String crc640879981a986d658b\&.SfGradientViewRenderer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file SfGradientViewRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
