.TH "crc64396a3fe5f8138e3f.KeepAliveService" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64396a3fe5f8138e3f.KeepAliveService
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.app\&.Service, mono\&.android\&.IGCUserPeer, android\&.app\&.Service, mono\&.android\&.IGCUserPeer, android\&.app\&.Service, mono\&.android\&.IGCUserPeer, android\&.app\&.Service, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeepAliveService\fP ()"
.br
.ti -1c
.RI "android\&.os\&.IBinder \fBonBind\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBKeepAliveService\fP ()"
.br
.ti -1c
.RI "android\&.os\&.IBinder \fBonBind\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBKeepAliveService\fP ()"
.br
.ti -1c
.RI "android\&.os\&.IBinder \fBonBind\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBKeepAliveService\fP ()"
.br
.ti -1c
.RI "android\&.os\&.IBinder \fBonBind\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file KeepAliveService\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64396a3fe5f8138e3f\&.KeepAliveService\&.KeepAliveService ()"

.PP
Definition at line 19 of file KeepAliveService\&.java\&.
.SS "crc64396a3fe5f8138e3f\&.KeepAliveService\&.KeepAliveService ()"

.PP
Definition at line 19 of file KeepAliveService\&.java\&.
.SS "crc64396a3fe5f8138e3f\&.KeepAliveService\&.KeepAliveService ()"

.PP
Definition at line 19 of file KeepAliveService\&.java\&.
.SS "crc64396a3fe5f8138e3f\&.KeepAliveService\&.KeepAliveService ()"

.PP
Definition at line 19 of file KeepAliveService\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 35 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 35 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 35 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 35 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidClearReferences ()"

.PP
Definition at line 42 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidClearReferences ()"

.PP
Definition at line 42 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidClearReferences ()"

.PP
Definition at line 42 of file KeepAliveService\&.java\&.
.SS "void crc64396a3fe5f8138e3f\&.KeepAliveService\&.monodroidClearReferences ()"

.PP
Definition at line 42 of file KeepAliveService\&.java\&.
.SS "android\&.os\&.IBinder crc64396a3fe5f8138e3f\&.KeepAliveService\&.onBind (android\&.content\&.Intent p0)"

.PP
Definition at line 27 of file KeepAliveService\&.java\&.
.SS "android\&.os\&.IBinder crc64396a3fe5f8138e3f\&.KeepAliveService\&.onBind (android\&.content\&.Intent p0)"

.PP
Definition at line 27 of file KeepAliveService\&.java\&.
.SS "android\&.os\&.IBinder crc64396a3fe5f8138e3f\&.KeepAliveService\&.onBind (android\&.content\&.Intent p0)"

.PP
Definition at line 27 of file KeepAliveService\&.java\&.
.SS "android\&.os\&.IBinder crc64396a3fe5f8138e3f\&.KeepAliveService\&.onBind (android\&.content\&.Intent p0)"

.PP
Definition at line 27 of file KeepAliveService\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64396a3fe5f8138e3f\&.KeepAliveService\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file KeepAliveService\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
