.TH "crc643f46942d9dd1fff9.ShellFlyoutLayout" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.ShellFlyoutLayout
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.coordinatorlayout\&.widget\&.CoordinatorLayout, mono\&.android\&.IGCUserPeer, androidx\&.coordinatorlayout\&.widget\&.CoordinatorLayout, mono\&.android\&.IGCUserPeer, androidx\&.coordinatorlayout\&.widget\&.CoordinatorLayout, mono\&.android\&.IGCUserPeer, androidx\&.coordinatorlayout\&.widget\&.CoordinatorLayout, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBShellFlyoutLayout\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ShellFlyoutLayout\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0)"

.PP
Definition at line 19 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file ShellFlyoutLayout\&.java\&.
.SS "crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.ShellFlyoutLayout (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 35 of file ShellFlyoutLayout\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 51 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.monodroidClearReferences ()"

.PP
Definition at line 58 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Definition at line 43 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Definition at line 43 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Definition at line 43 of file ShellFlyoutLayout\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Definition at line 43 of file ShellFlyoutLayout\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.ShellFlyoutLayout\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file ShellFlyoutLayout\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
