.TH "crc64cad742debd39f951.SfPickerRenderer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64cad742debd39f951.SfPickerRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP, and mono\&.android\&.IGCUserPeer\&.
.PP
Inherited by \fBcrc64cad742debd39f951\&.MaterialSfPickerRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSfPickerRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSfPickerRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSfPickerRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonSizeChanged\fP (int p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file SfPickerRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64cad742debd39f951\&.SfPickerRenderer\&.SfPickerRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 19 of file SfPickerRenderer\&.java\&.
.SS "crc64cad742debd39f951\&.SfPickerRenderer\&.SfPickerRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 27 of file SfPickerRenderer\&.java\&.
.SS "crc64cad742debd39f951\&.SfPickerRenderer\&.SfPickerRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 35 of file SfPickerRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64cad742debd39f951\&.SfPickerRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Reimplemented in \fBcrc64cad742debd39f951\&.MaterialSfPickerRenderer\fP\&.
.PP
Definition at line 51 of file SfPickerRenderer\&.java\&.
.SS "void crc64cad742debd39f951\&.SfPickerRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Reimplemented in \fBcrc64cad742debd39f951\&.MaterialSfPickerRenderer\fP\&.
.PP
Definition at line 58 of file SfPickerRenderer\&.java\&.
.SS "void crc64cad742debd39f951\&.SfPickerRenderer\&.onSizeChanged (int p0, int p1, int p2, int p3)"

.PP
Definition at line 43 of file SfPickerRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String crc64cad742debd39f951\&.SfPickerRenderer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file SfPickerRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
