.TH "crc6434af9c19aa01b597.GoogleApiClientConnectionCallbacksImpl" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc6434af9c19aa01b597.GoogleApiClientConnectionCallbacksImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.GoogleApiClient\&.ConnectionCallbacks, com\&.google\&.android\&.gms\&.common\&.api\&.internal\&.ConnectionCallbacks, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.GoogleApiClient\&.ConnectionCallbacks, com\&.google\&.android\&.gms\&.common\&.api\&.internal\&.ConnectionCallbacks, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.GoogleApiClient\&.ConnectionCallbacks, com\&.google\&.android\&.gms\&.common\&.api\&.internal\&.ConnectionCallbacks, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.GoogleApiClient\&.ConnectionCallbacks, and com\&.google\&.android\&.gms\&.common\&.api\&.internal\&.ConnectionCallbacks\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGoogleApiClientConnectionCallbacksImpl\fP ()"
.br
.ti -1c
.RI "void \fBonConnected\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonConnectionSuspended\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBGoogleApiClientConnectionCallbacksImpl\fP ()"
.br
.ti -1c
.RI "void \fBonConnected\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonConnectionSuspended\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBGoogleApiClientConnectionCallbacksImpl\fP ()"
.br
.ti -1c
.RI "void \fBonConnected\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonConnectionSuspended\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBGoogleApiClientConnectionCallbacksImpl\fP ()"
.br
.ti -1c
.RI "void \fBonConnected\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonConnectionSuspended\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.GoogleApiClientConnectionCallbacksImpl ()"

.PP
Definition at line 22 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.GoogleApiClientConnectionCallbacksImpl ()"

.PP
Definition at line 22 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.GoogleApiClientConnectionCallbacksImpl ()"

.PP
Definition at line 22 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.GoogleApiClientConnectionCallbacksImpl ()"

.PP
Definition at line 22 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 46 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.monodroidClearReferences ()"

.PP
Definition at line 53 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnected (android\&.os\&.Bundle p0)"

.PP
Definition at line 30 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnected (android\&.os\&.Bundle p0)"

.PP
Definition at line 30 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnected (android\&.os\&.Bundle p0)"

.PP
Definition at line 30 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnected (android\&.os\&.Bundle p0)"

.PP
Definition at line 30 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnectionSuspended (int p0)"

.PP
Definition at line 38 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnectionSuspended (int p0)"

.PP
Definition at line 38 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnectionSuspended (int p0)"

.PP
Definition at line 38 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SS "void crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.onConnectionSuspended (int p0)"

.PP
Definition at line 38 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc6434af9c19aa01b597\&.GoogleApiClientConnectionCallbacksImpl\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 12 of file GoogleApiClientConnectionCallbacksImpl\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
