.TH "crc64d32ffa835eadac0e.DelegateCancelableCallback" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64d32ffa835eadac0e.DelegateCancelableCallback
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.CancelableCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.CancelableCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.CancelableCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.google\&.android\&.gms\&.maps\&.GoogleMap\&.CancelableCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegateCancelableCallback\fP ()"
.br
.ti -1c
.RI "void \fBonCancel\fP ()"
.br
.ti -1c
.RI "void \fBonFinish\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDelegateCancelableCallback\fP ()"
.br
.ti -1c
.RI "void \fBonCancel\fP ()"
.br
.ti -1c
.RI "void \fBonFinish\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDelegateCancelableCallback\fP ()"
.br
.ti -1c
.RI "void \fBonCancel\fP ()"
.br
.ti -1c
.RI "void \fBonFinish\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDelegateCancelableCallback\fP ()"
.br
.ti -1c
.RI "void \fBonCancel\fP ()"
.br
.ti -1c
.RI "void \fBonFinish\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file DelegateCancelableCallback\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.DelegateCancelableCallback ()"

.PP
Definition at line 21 of file DelegateCancelableCallback\&.java\&.
.SS "crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.DelegateCancelableCallback ()"

.PP
Definition at line 21 of file DelegateCancelableCallback\&.java\&.
.SS "crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.DelegateCancelableCallback ()"

.PP
Definition at line 21 of file DelegateCancelableCallback\&.java\&.
.SS "crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.DelegateCancelableCallback ()"

.PP
Definition at line 21 of file DelegateCancelableCallback\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 45 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.monodroidClearReferences ()"

.PP
Definition at line 52 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onCancel ()"

.PP
Definition at line 29 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onCancel ()"

.PP
Definition at line 29 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onCancel ()"

.PP
Definition at line 29 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onCancel ()"

.PP
Definition at line 29 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onFinish ()"

.PP
Definition at line 37 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onFinish ()"

.PP
Definition at line 37 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onFinish ()"

.PP
Definition at line 37 of file DelegateCancelableCallback\&.java\&.
.SS "void crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.onFinish ()"

.PP
Definition at line 37 of file DelegateCancelableCallback\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64d32ffa835eadac0e\&.DelegateCancelableCallback\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file DelegateCancelableCallback\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
