.TH "crc643f46942d9dd1fff9.FormsAppCompatActivity" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.FormsAppCompatActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.appcompat\&.app\&.AppCompatActivity, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.app\&.AppCompatActivity, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.app\&.AppCompatActivity, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.app\&.AppCompatActivity, and mono\&.android\&.IGCUserPeer\&.
.PP
Inherited by \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormsAppCompatActivity\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP (int p0)"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonNewIntent\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP (int p0)"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonNewIntent\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP (int p0)"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonNewIntent\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP ()"
.br
.ti -1c
.RI "\fBFormsAppCompatActivity\fP (int p0)"
.br
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonConfigurationChanged\fP (android\&.content\&.res\&.Configuration p0)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (android\&.view\&.MenuItem p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonNewIntent\fP (android\&.content\&.Intent p0)"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonRestart\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file FormsAppCompatActivity\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity ()"

.PP
Definition at line 30 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity (int p0)"

.PP
Definition at line 38 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity ()"

.PP
Definition at line 30 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity (int p0)"

.PP
Definition at line 38 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity ()"

.PP
Definition at line 30 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity (int p0)"

.PP
Definition at line 38 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity ()"

.PP
Definition at line 30 of file FormsAppCompatActivity\&.java\&.
.SS "crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.FormsAppCompatActivity (int p0)"

.PP
Definition at line 38 of file FormsAppCompatActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 142 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 142 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 142 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 142 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 149 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 149 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 149 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.monodroidClearReferences ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 149 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onActivityResult (int p0, int p1, android\&.content\&.Intent p2)"

.PP
Definition at line 70 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onBackPressed ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 46 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onBackPressed ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 46 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onBackPressed ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 46 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onBackPressed ()"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 46 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 54 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 54 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 54 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onConfigurationChanged (android\&.content\&.res\&.Configuration p0)"

.PP
Definition at line 54 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 78 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 78 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 78 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onCreate (android\&.os\&.Bundle p0)"

.PP
Reimplemented in \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, \fBcrc6473473cbc676e88c0\&.MainActivity\fP, and \fBcrc6473473cbc676e88c0\&.MainActivity\fP\&.
.PP
Definition at line 78 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onDestroy ()"

.PP
Definition at line 86 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onNewIntent (android\&.content\&.Intent p0)"

.PP
Definition at line 94 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onNewIntent (android\&.content\&.Intent p0)"

.PP
Definition at line 94 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onNewIntent (android\&.content\&.Intent p0)"

.PP
Definition at line 94 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onNewIntent (android\&.content\&.Intent p0)"

.PP
Definition at line 94 of file FormsAppCompatActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 62 of file FormsAppCompatActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 62 of file FormsAppCompatActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 62 of file FormsAppCompatActivity\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onOptionsItemSelected (android\&.view\&.MenuItem p0)"

.PP
Definition at line 62 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onPause ()"

.PP
Definition at line 102 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onPause ()"

.PP
Definition at line 102 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onPause ()"

.PP
Definition at line 102 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onPause ()"

.PP
Definition at line 102 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onRestart ()"

.PP
Definition at line 110 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onRestart ()"

.PP
Definition at line 110 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onRestart ()"

.PP
Definition at line 110 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onRestart ()"

.PP
Definition at line 110 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onResume ()"

.PP
Definition at line 118 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onResume ()"

.PP
Definition at line 118 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onResume ()"

.PP
Definition at line 118 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onResume ()"

.PP
Definition at line 118 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStart ()"

.PP
Definition at line 126 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStart ()"

.PP
Definition at line 126 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStart ()"

.PP
Definition at line 126 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStart ()"

.PP
Definition at line 126 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStop ()"

.PP
Definition at line 134 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStop ()"

.PP
Definition at line 134 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStop ()"

.PP
Definition at line 134 of file FormsAppCompatActivity\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.onStop ()"

.PP
Definition at line 134 of file FormsAppCompatActivity\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.FormsAppCompatActivity\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file FormsAppCompatActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
