.TH "crc64720bb2db43a66fe9.FormsFragmentPagerAdapter_1" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64720bb2db43a66fe9.FormsFragmentPagerAdapter_1
.SH SYNOPSIS
.br
.PP
.PP
Inherits androidx\&.fragment\&.app\&.FragmentPagerAdapter, mono\&.android\&.IGCUserPeer, androidx\&.fragment\&.app\&.FragmentPagerAdapter, mono\&.android\&.IGCUserPeer, androidx\&.fragment\&.app\&.FragmentPagerAdapter, mono\&.android\&.IGCUserPeer, androidx\&.fragment\&.app\&.FragmentPagerAdapter, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0)"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "androidx\&.fragment\&.app\&.Fragment \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.CharSequence \fBgetPageTitle\fP (int p0)"
.br
.ti -1c
.RI "void \fBrestoreState\fP (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0)"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "androidx\&.fragment\&.app\&.Fragment \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.CharSequence \fBgetPageTitle\fP (int p0)"
.br
.ti -1c
.RI "void \fBrestoreState\fP (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0)"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "androidx\&.fragment\&.app\&.Fragment \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.CharSequence \fBgetPageTitle\fP (int p0)"
.br
.ti -1c
.RI "void \fBrestoreState\fP (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0)"
.br
.ti -1c
.RI "\fBFormsFragmentPagerAdapter_1\fP (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "androidx\&.fragment\&.app\&.Fragment \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "int \fBgetItemPosition\fP (java\&.lang\&.Object p0)"
.br
.ti -1c
.RI "java\&.lang\&.CharSequence \fBgetPageTitle\fP (int p0)"
.br
.ti -1c
.RI "void \fBrestoreState\fP (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file FormsFragmentPagerAdapter_1\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0)"

.PP
Definition at line 24 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"

.PP
Definition at line 32 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0)"

.PP
Definition at line 24 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"

.PP
Definition at line 32 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0)"

.PP
Definition at line 24 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"

.PP
Definition at line 32 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0)"

.PP
Definition at line 24 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.FormsFragmentPagerAdapter_1 (androidx\&.fragment\&.app\&.FragmentManager p0, int p1)"

.PP
Definition at line 32 of file FormsFragmentPagerAdapter_1\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getCount ()"

.PP
Definition at line 40 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getCount ()"

.PP
Definition at line 40 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getCount ()"

.PP
Definition at line 40 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getCount ()"

.PP
Definition at line 40 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "androidx\&.fragment\&.app\&.Fragment crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItem (int p0)"

.PP
Definition at line 48 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "androidx\&.fragment\&.app\&.Fragment crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItem (int p0)"

.PP
Definition at line 48 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "androidx\&.fragment\&.app\&.Fragment crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItem (int p0)"

.PP
Definition at line 48 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "androidx\&.fragment\&.app\&.Fragment crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItem (int p0)"

.PP
Definition at line 48 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "long crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemId (int p0)"

.PP
Definition at line 56 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "long crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemId (int p0)"

.PP
Definition at line 56 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "long crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemId (int p0)"

.PP
Definition at line 56 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "long crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemId (int p0)"

.PP
Definition at line 56 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 64 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 64 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 64 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "int crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getItemPosition (java\&.lang\&.Object p0)"

.PP
Definition at line 64 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "java\&.lang\&.CharSequence crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getPageTitle (int p0)"

.PP
Definition at line 72 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "java\&.lang\&.CharSequence crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getPageTitle (int p0)"

.PP
Definition at line 72 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "java\&.lang\&.CharSequence crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getPageTitle (int p0)"

.PP
Definition at line 72 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "java\&.lang\&.CharSequence crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.getPageTitle (int p0)"

.PP
Definition at line 72 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 88 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 88 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 88 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 88 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidClearReferences ()"

.PP
Definition at line 95 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidClearReferences ()"

.PP
Definition at line 95 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidClearReferences ()"

.PP
Definition at line 95 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.monodroidClearReferences ()"

.PP
Definition at line 95 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.restoreState (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"

.PP
Definition at line 80 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.restoreState (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"

.PP
Definition at line 80 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.restoreState (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"

.PP
Definition at line 80 of file FormsFragmentPagerAdapter_1\&.java\&.
.SS "void crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.restoreState (android\&.os\&.Parcelable p0, java\&.lang\&.ClassLoader p1)"

.PP
Definition at line 80 of file FormsFragmentPagerAdapter_1\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64720bb2db43a66fe9\&.FormsFragmentPagerAdapter_1\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file FormsFragmentPagerAdapter_1\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
