.TH "crc643f46942d9dd1fff9.SwitchRenderer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.SwitchRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP, mono\&.android\&.IGCUserPeer, android\&.widget\&.CompoundButton\&.OnCheckedChangeListener, \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP, mono\&.android\&.IGCUserPeer, android\&.widget\&.CompoundButton\&.OnCheckedChangeListener, \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP, mono\&.android\&.IGCUserPeer, android\&.widget\&.CompoundButton\&.OnCheckedChangeListener, \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP, mono\&.android\&.IGCUserPeer, and android\&.widget\&.CompoundButton\&.OnCheckedChangeListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonCheckedChanged\fP (android\&.widget\&.CompoundButton p0, boolean p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonCheckedChanged\fP (android\&.widget\&.CompoundButton p0, boolean p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonCheckedChanged\fP (android\&.widget\&.CompoundButton p0, boolean p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBSwitchRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonCheckedChanged\fP (android\&.widget\&.CompoundButton p0, boolean p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file SwitchRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 20 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 28 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 36 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 20 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 28 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 36 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 20 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 28 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 36 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 20 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 28 of file SwitchRenderer\&.java\&.
.SS "crc643f46942d9dd1fff9\&.SwitchRenderer\&.SwitchRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 36 of file SwitchRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 52 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 52 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 52 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 52 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 59 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 59 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 59 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ViewRenderer_2\fP\&.
.PP
Definition at line 59 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.onCheckedChanged (android\&.widget\&.CompoundButton p0, boolean p1)"

.PP
Definition at line 44 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.onCheckedChanged (android\&.widget\&.CompoundButton p0, boolean p1)"

.PP
Definition at line 44 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.onCheckedChanged (android\&.widget\&.CompoundButton p0, boolean p1)"

.PP
Definition at line 44 of file SwitchRenderer\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.SwitchRenderer\&.onCheckedChanged (android\&.widget\&.CompoundButton p0, boolean p1)"

.PP
Definition at line 44 of file SwitchRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.SwitchRenderer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file SwitchRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
