.TH "crc643f46942d9dd1fff9.PolylineView" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.PolylineView
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.ShapeView\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.ShapeView\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.ShapeView\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.ShapeView\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPolylineView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file PolylineView\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 42 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 42 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 42 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0)"

.PP
Definition at line 18 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 26 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 34 of file PolylineView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.PolylineView\&.PolylineView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 42 of file PolylineView\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 50 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 50 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 50 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 50 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 57 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 57 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 57 of file PolylineView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.PolylineView\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.ShapeView\fP\&.
.PP
Definition at line 57 of file PolylineView\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.PolylineView\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file PolylineView\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
