.TH "crc643dd37f507f3d9710.PopupPageRenderer" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643dd37f507f3d9710.PopupPageRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP, and mono\&.android\&.IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBonAttachedToWindow\fP ()"
.br
.ti -1c
.RI "void \fBonDetachedFromWindow\fP ()"
.br
.ti -1c
.RI "void \fBonWindowVisibilityChanged\fP (int p0)"
.br
.ti -1c
.RI "boolean \fBdispatchTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBonAttachedToWindow\fP ()"
.br
.ti -1c
.RI "void \fBonDetachedFromWindow\fP ()"
.br
.ti -1c
.RI "void \fBonWindowVisibilityChanged\fP (int p0)"
.br
.ti -1c
.RI "boolean \fBdispatchTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBonAttachedToWindow\fP ()"
.br
.ti -1c
.RI "void \fBonDetachedFromWindow\fP ()"
.br
.ti -1c
.RI "void \fBonWindowVisibilityChanged\fP (int p0)"
.br
.ti -1c
.RI "boolean \fBdispatchTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBPopupPageRenderer\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBonAttachedToWindow\fP ()"
.br
.ti -1c
.RI "void \fBonDetachedFromWindow\fP ()"
.br
.ti -1c
.RI "void \fBonWindowVisibilityChanged\fP (int p0)"
.br
.ti -1c
.RI "boolean \fBdispatchTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "boolean \fBonTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file PopupPageRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 24 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 32 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 40 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 24 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 32 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 40 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 24 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 32 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 40 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 24 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 32 of file PopupPageRenderer\&.java\&.
.SS "crc643dd37f507f3d9710\&.PopupPageRenderer\&.PopupPageRenderer (android\&.content\&.Context p0)"

.PP
Definition at line 40 of file PopupPageRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.dispatchTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.VisualElementRenderer_1\fP\&.
.PP
Definition at line 80 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.dispatchTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.VisualElementRenderer_1\fP\&.
.PP
Definition at line 80 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.dispatchTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.VisualElementRenderer_1\fP\&.
.PP
Definition at line 80 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.dispatchTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.VisualElementRenderer_1\fP\&.
.PP
Definition at line 80 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 96 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 96 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 96 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 96 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 103 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 103 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 103 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 103 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onAttachedToWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 56 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onAttachedToWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 56 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onAttachedToWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 56 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onAttachedToWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 56 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onDetachedFromWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 64 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onDetachedFromWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 64 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onDetachedFromWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 64 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onDetachedFromWindow ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 64 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 48 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 48 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 48 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onLayout (boolean p0, int p1, int p2, int p3, int p4)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 48 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.onTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 88 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.onTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 88 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.onTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 88 of file PopupPageRenderer\&.java\&.
.SS "boolean crc643dd37f507f3d9710\&.PopupPageRenderer\&.onTouchEvent (android\&.view\&.MotionEvent p0)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.PageRenderer\fP\&.
.PP
Definition at line 88 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onWindowVisibilityChanged (int p0)"

.PP
Definition at line 72 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onWindowVisibilityChanged (int p0)"

.PP
Definition at line 72 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onWindowVisibilityChanged (int p0)"

.PP
Definition at line 72 of file PopupPageRenderer\&.java\&.
.SS "void crc643dd37f507f3d9710\&.PopupPageRenderer\&.onWindowVisibilityChanged (int p0)"

.PP
Definition at line 72 of file PopupPageRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643dd37f507f3d9710\&.PopupPageRenderer\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file PopupPageRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
