.TH "crc643f46942d9dd1fff9.EdgeSnapHelper" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.EdgeSnapHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP, mono\&.android\&.IGCUserPeer, \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP, and mono\&.android\&.IGCUserPeer\&.
.PP
Inherited by \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdgeSnapHelper\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEdgeSnapHelper\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEdgeSnapHelper\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEdgeSnapHelper\fP ()"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file EdgeSnapHelper\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.EdgeSnapHelper ()"

.PP
Definition at line 18 of file EdgeSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.EdgeSnapHelper ()"

.PP
Definition at line 18 of file EdgeSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.EdgeSnapHelper ()"

.PP
Definition at line 18 of file EdgeSnapHelper\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.EdgeSnapHelper ()"

.PP
Definition at line 18 of file EdgeSnapHelper\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 26 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 26 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 26 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 26 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 33 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 33 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 33 of file EdgeSnapHelper\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.monodroidClearReferences ()"

.PP
Reimplemented from \fBcrc643f46942d9dd1fff9\&.NongreedySnapHelper\fP\&.
.PP
Reimplemented in \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP, \fBcrc643f46942d9dd1fff9\&.StartSnapHelper\fP, and \fBcrc643f46942d9dd1fff9\&.EndSnapHelper\fP\&.
.PP
Definition at line 33 of file EdgeSnapHelper\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.EdgeSnapHelper\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 10 of file EdgeSnapHelper\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
