.TH "crc6450e07d0e82e86181.AwaitableResultCallback_1" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc6450e07d0e82e86181.AwaitableResultCallback_1
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.ResultCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.ResultCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.google\&.android\&.gms\&.common\&.api\&.ResultCallback, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.google\&.android\&.gms\&.common\&.api\&.ResultCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAwaitableResultCallback_1\fP ()"
.br
.ti -1c
.RI "void \fBonResult\fP (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBAwaitableResultCallback_1\fP ()"
.br
.ti -1c
.RI "void \fBonResult\fP (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBAwaitableResultCallback_1\fP ()"
.br
.ti -1c
.RI "void \fBonResult\fP (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBAwaitableResultCallback_1\fP ()"
.br
.ti -1c
.RI "void \fBonResult\fP (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file AwaitableResultCallback_1\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.AwaitableResultCallback_1 ()"

.PP
Definition at line 20 of file AwaitableResultCallback_1\&.java\&.
.SS "crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.AwaitableResultCallback_1 ()"

.PP
Definition at line 20 of file AwaitableResultCallback_1\&.java\&.
.SS "crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.AwaitableResultCallback_1 ()"

.PP
Definition at line 20 of file AwaitableResultCallback_1\&.java\&.
.SS "crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.AwaitableResultCallback_1 ()"

.PP
Definition at line 20 of file AwaitableResultCallback_1\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.onResult (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"

.PP
Definition at line 28 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.onResult (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"

.PP
Definition at line 28 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.onResult (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"

.PP
Definition at line 28 of file AwaitableResultCallback_1\&.java\&.
.SS "void crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.onResult (com\&.google\&.android\&.gms\&.common\&.api\&.Result p0)"

.PP
Definition at line 28 of file AwaitableResultCallback_1\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc6450e07d0e82e86181\&.AwaitableResultCallback_1\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file AwaitableResultCallback_1\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
