.TH "crc64a4555f9f70c213ae.Crashes_AndroidCrashListener" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc64a4555f9f70c213ae.Crashes_AndroidCrashListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.microsoft\&.appcenter\&.crashes\&.CrashesListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.microsoft\&.appcenter\&.crashes\&.CrashesListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrashes_AndroidCrashListener\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Iterable \fBgetErrorAttachments\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "void \fBonBeforeSending\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "void \fBonSendingFailed\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0, java\&.lang\&.Exception p1)"
.br
.ti -1c
.RI "void \fBonSendingSucceeded\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "boolean \fBshouldAwaitUserConfirmation\fP ()"
.br
.ti -1c
.RI "boolean \fBshouldProcess\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBCrashes_AndroidCrashListener\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Iterable \fBgetErrorAttachments\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "void \fBonBeforeSending\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "void \fBonSendingFailed\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0, java\&.lang\&.Exception p1)"
.br
.ti -1c
.RI "void \fBonSendingSucceeded\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "boolean \fBshouldAwaitUserConfirmation\fP ()"
.br
.ti -1c
.RI "boolean \fBshouldProcess\fP (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Crashes_AndroidCrashListener\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.Crashes_AndroidCrashListener ()"

.PP
Definition at line 25 of file Crashes_AndroidCrashListener\&.java\&.
.SS "crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.Crashes_AndroidCrashListener ()"

.PP
Definition at line 25 of file Crashes_AndroidCrashListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "java\&.lang\&.Iterable crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.getErrorAttachments (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 33 of file Crashes_AndroidCrashListener\&.java\&.
.SS "java\&.lang\&.Iterable crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.getErrorAttachments (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 33 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 81 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 81 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.monodroidClearReferences ()"

.PP
Definition at line 88 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.monodroidClearReferences ()"

.PP
Definition at line 88 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.onBeforeSending (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 41 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.onBeforeSending (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 41 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.onSendingFailed (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0, java\&.lang\&.Exception p1)"

.PP
Definition at line 49 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.onSendingFailed (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0, java\&.lang\&.Exception p1)"

.PP
Definition at line 49 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.onSendingSucceeded (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 57 of file Crashes_AndroidCrashListener\&.java\&.
.SS "void crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.onSendingSucceeded (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 57 of file Crashes_AndroidCrashListener\&.java\&.
.SS "boolean crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.shouldAwaitUserConfirmation ()"

.PP
Definition at line 65 of file Crashes_AndroidCrashListener\&.java\&.
.SS "boolean crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.shouldAwaitUserConfirmation ()"

.PP
Definition at line 65 of file Crashes_AndroidCrashListener\&.java\&.
.SS "boolean crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.shouldProcess (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 73 of file Crashes_AndroidCrashListener\&.java\&.
.SS "boolean crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.shouldProcess (com\&.microsoft\&.appcenter\&.crashes\&.model\&.ErrorReport p0)"

.PP
Definition at line 73 of file Crashes_AndroidCrashListener\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc64a4555f9f70c213ae\&.Crashes_AndroidCrashListener\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file Crashes_AndroidCrashListener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
