.TH "crc643f46942d9dd1fff9.EntryCellView" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc643f46942d9dd1fff9.EntryCellView
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.text\&.TextWatcher, android\&.text\&.NoCopySpan, android\&.view\&.View\&.OnFocusChangeListener, android\&.widget\&.TextView\&.OnEditorActionListener, android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.text\&.TextWatcher, android\&.text\&.NoCopySpan, android\&.view\&.View\&.OnFocusChangeListener, android\&.widget\&.TextView\&.OnEditorActionListener, android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.text\&.TextWatcher, android\&.text\&.NoCopySpan, android\&.view\&.View\&.OnFocusChangeListener, android\&.widget\&.TextView\&.OnEditorActionListener, android\&.widget\&.LinearLayout, mono\&.android\&.IGCUserPeer, android\&.text\&.TextWatcher, android\&.text\&.NoCopySpan, android\&.view\&.View\&.OnFocusChangeListener, and android\&.widget\&.TextView\&.OnEditorActionListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBafterTextChanged\fP (android\&.text\&.Editable p0)"
.br
.ti -1c
.RI "void \fBbeforeTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonFocusChange\fP (android\&.view\&.View p0, boolean p1)"
.br
.ti -1c
.RI "boolean \fBonEditorAction\fP (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBafterTextChanged\fP (android\&.text\&.Editable p0)"
.br
.ti -1c
.RI "void \fBbeforeTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonFocusChange\fP (android\&.view\&.View p0, boolean p1)"
.br
.ti -1c
.RI "boolean \fBonEditorAction\fP (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBafterTextChanged\fP (android\&.text\&.Editable p0)"
.br
.ti -1c
.RI "void \fBbeforeTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonFocusChange\fP (android\&.view\&.View p0, boolean p1)"
.br
.ti -1c
.RI "boolean \fBonEditorAction\fP (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"
.br
.ti -1c
.RI "\fBEntryCellView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBafterTextChanged\fP (android\&.text\&.Editable p0)"
.br
.ti -1c
.RI "void \fBbeforeTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonTextChanged\fP (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"
.br
.ti -1c
.RI "void \fBonFocusChange\fP (android\&.view\&.View p0, boolean p1)"
.br
.ti -1c
.RI "boolean \fBonEditorAction\fP (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file EntryCellView\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0)"

.PP
Definition at line 27 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 35 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 43 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 51 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0)"

.PP
Definition at line 27 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 35 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 43 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 51 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0)"

.PP
Definition at line 27 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 35 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 43 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 51 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0)"

.PP
Definition at line 27 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)"

.PP
Definition at line 35 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)"

.PP
Definition at line 43 of file EntryCellView\&.java\&.
.SS "crc643f46942d9dd1fff9\&.EntryCellView\&.EntryCellView (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2, int p3)"

.PP
Definition at line 51 of file EntryCellView\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.afterTextChanged (android\&.text\&.Editable p0)"

.PP
Definition at line 59 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.afterTextChanged (android\&.text\&.Editable p0)"

.PP
Definition at line 59 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.afterTextChanged (android\&.text\&.Editable p0)"

.PP
Definition at line 59 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.afterTextChanged (android\&.text\&.Editable p0)"

.PP
Definition at line 59 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.beforeTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 67 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.beforeTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 67 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.beforeTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 67 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.beforeTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 67 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 99 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.monodroidClearReferences ()"

.PP
Definition at line 106 of file EntryCellView\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.EntryCellView\&.onEditorAction (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"

.PP
Definition at line 91 of file EntryCellView\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.EntryCellView\&.onEditorAction (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"

.PP
Definition at line 91 of file EntryCellView\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.EntryCellView\&.onEditorAction (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"

.PP
Definition at line 91 of file EntryCellView\&.java\&.
.SS "boolean crc643f46942d9dd1fff9\&.EntryCellView\&.onEditorAction (android\&.widget\&.TextView p0, int p1, android\&.view\&.KeyEvent p2)"

.PP
Definition at line 91 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onFocusChange (android\&.view\&.View p0, boolean p1)"

.PP
Definition at line 83 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onFocusChange (android\&.view\&.View p0, boolean p1)"

.PP
Definition at line 83 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onFocusChange (android\&.view\&.View p0, boolean p1)"

.PP
Definition at line 83 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onFocusChange (android\&.view\&.View p0, boolean p1)"

.PP
Definition at line 83 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 75 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 75 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 75 of file EntryCellView\&.java\&.
.SS "void crc643f46942d9dd1fff9\&.EntryCellView\&.onTextChanged (java\&.lang\&.CharSequence p0, int p1, int p2, int p3)"

.PP
Definition at line 75 of file EntryCellView\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String crc643f46942d9dd1fff9\&.EntryCellView\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 14 of file EntryCellView\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
