.TH "Application Green Quake/obj/Release/netstandard2.0/Views/EcoActions/Shopping/EcoFriendlyProduct.xaml.g.cs" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/obj/Release/netstandard2.0/Views/EcoActions/Shopping/EcoFriendlyProduct.xaml.g.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Views\&.EcoActions\&.Shopping\&.EcoFriendlyProduct\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBApplication_Green_Quake\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Views\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Views\&.EcoActions\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Views\&.EcoActions\&.Shopping\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
