.TH "MainApplication" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainApplication
.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainApplication\fP (IntPtr handle, JniHandleOwnership transer)"
.br
.ti -1c
.RI "override void \fBOnCreate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file MainApplication\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainApplication\&.MainApplication (IntPtr handle, JniHandleOwnership transer)"

.PP
Definition at line 30 of file MainApplication\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void MainApplication\&.OnCreate ()"

.PP
Definition at line 35 of file MainApplication\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
