.TH "Application Green Quake/Views/MainMenu.xaml.cs" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/MainMenu.xaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Views\&.MainMenu\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBApplication_Green_Quake\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Views\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBApplication\fP = Xamarin\&.Forms\&.Application"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBApplication\fP =  Xamarin\&.Forms\&.Application"

.PP
Definition at line 17 of file MainMenu\&.xaml\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
