.TH "mono.androidx.core.view.ViewPropertyAnimatorUpdateListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.core.view.ViewPropertyAnimatorUpdateListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewPropertyAnimatorUpdateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationUpdate\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBViewPropertyAnimatorUpdateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationUpdate\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBViewPropertyAnimatorUpdateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationUpdate\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBViewPropertyAnimatorUpdateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationUpdate\fP (android\&.view\&.View p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.ViewPropertyAnimatorUpdateListenerImplementor ()"

.PP
Definition at line 20 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.ViewPropertyAnimatorUpdateListenerImplementor ()"

.PP
Definition at line 20 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.ViewPropertyAnimatorUpdateListenerImplementor ()"

.PP
Definition at line 20 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.ViewPropertyAnimatorUpdateListenerImplementor ()"

.PP
Definition at line 20 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.onAnimationUpdate (android\&.view\&.View p0)"

.PP
Definition at line 28 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.onAnimationUpdate (android\&.view\&.View p0)"

.PP
Definition at line 28 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.onAnimationUpdate (android\&.view\&.View p0)"

.PP
Definition at line 28 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.onAnimationUpdate (android\&.view\&.View p0)"

.PP
Definition at line 28 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.androidx\&.core\&.view\&.ViewPropertyAnimatorUpdateListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file ViewPropertyAnimatorUpdateListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
