.TH "mono.androidx.appcompat.widget.ViewStubCompat_OnInflateListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.appcompat.widget.ViewStubCompat_OnInflateListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.widget\&.ViewStubCompat\&.OnInflateListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.widget\&.ViewStubCompat\&.OnInflateListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.widget\&.ViewStubCompat\&.OnInflateListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and androidx\&.appcompat\&.widget\&.ViewStubCompat\&.OnInflateListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewStubCompat_OnInflateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonInflate\fP (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBViewStubCompat_OnInflateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonInflate\fP (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBViewStubCompat_OnInflateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonInflate\fP (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBViewStubCompat_OnInflateListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonInflate\fP (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.ViewStubCompat_OnInflateListenerImplementor ()"

.PP
Definition at line 20 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.ViewStubCompat_OnInflateListenerImplementor ()"

.PP
Definition at line 20 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.ViewStubCompat_OnInflateListenerImplementor ()"

.PP
Definition at line 20 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.ViewStubCompat_OnInflateListenerImplementor ()"

.PP
Definition at line 20 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.onInflate (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.onInflate (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.onInflate (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.onInflate (androidx\&.appcompat\&.widget\&.ViewStubCompat p0, android\&.view\&.View p1)"

.PP
Definition at line 28 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.androidx\&.appcompat\&.widget\&.ViewStubCompat_OnInflateListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file ViewStubCompat_OnInflateListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
