.TH "mono.androidx.appcompat.widget" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.appcompat.widget
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionMenuView_OnMenuItemClickListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBContentFrameLayout_OnAttachListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBFitWindowsViewGroup_OnFitSystemWindowsListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBMenuItemHoverListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBPopupMenu_OnDismissListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBPopupMenu_OnMenuItemClickListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBSearchView_OnCloseListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBSearchView_OnQueryTextListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBSearchView_OnSuggestionListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBShareActionProvider_OnShareTargetSelectedListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBToolbar_OnMenuItemClickListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBViewStubCompat_OnInflateListenerImplementor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
