.TH "mono.com.microsoft.appcenter.channel.Channel_ListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.com.microsoft.appcenter.channel.Channel_ListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.microsoft\&.appcenter\&.channel\&.Channel\&.Listener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.microsoft\&.appcenter\&.channel\&.Channel\&.Listener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannel_ListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonClear\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonGloballyEnabled\fP (boolean p0)"
.br
.ti -1c
.RI "void \fBonGroupAdded\fP (java\&.lang\&.String p0, com\&.microsoft\&.appcenter\&.channel\&.Channel\&.GroupListener p1, long p2)"
.br
.ti -1c
.RI "void \fBonGroupRemoved\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonPaused\fP (java\&.lang\&.String p0, java\&.lang\&.String p1)"
.br
.ti -1c
.RI "void \fBonPreparedLog\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1, int p2)"
.br
.ti -1c
.RI "void \fBonPreparingLog\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1)"
.br
.ti -1c
.RI "void \fBonResumed\fP (java\&.lang\&.String p0, java\&.lang\&.String p1)"
.br
.ti -1c
.RI "boolean \fBshouldFilter\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBChannel_ListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonClear\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonGloballyEnabled\fP (boolean p0)"
.br
.ti -1c
.RI "void \fBonGroupAdded\fP (java\&.lang\&.String p0, com\&.microsoft\&.appcenter\&.channel\&.Channel\&.GroupListener p1, long p2)"
.br
.ti -1c
.RI "void \fBonGroupRemoved\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonPaused\fP (java\&.lang\&.String p0, java\&.lang\&.String p1)"
.br
.ti -1c
.RI "void \fBonPreparedLog\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1, int p2)"
.br
.ti -1c
.RI "void \fBonPreparingLog\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1)"
.br
.ti -1c
.RI "void \fBonResumed\fP (java\&.lang\&.String p0, java\&.lang\&.String p1)"
.br
.ti -1c
.RI "boolean \fBshouldFilter\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Channel_ListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.Channel_ListenerImplementor ()"

.PP
Definition at line 28 of file Channel_ListenerImplementor\&.java\&.
.SS "mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.Channel_ListenerImplementor ()"

.PP
Definition at line 28 of file Channel_ListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 108 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 108 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 115 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 115 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onClear (java\&.lang\&.String p0)"

.PP
Definition at line 36 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onClear (java\&.lang\&.String p0)"

.PP
Definition at line 36 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onGloballyEnabled (boolean p0)"

.PP
Definition at line 44 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onGloballyEnabled (boolean p0)"

.PP
Definition at line 44 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onGroupAdded (java\&.lang\&.String p0, com\&.microsoft\&.appcenter\&.channel\&.Channel\&.GroupListener p1, long p2)"

.PP
Definition at line 52 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onGroupAdded (java\&.lang\&.String p0, com\&.microsoft\&.appcenter\&.channel\&.Channel\&.GroupListener p1, long p2)"

.PP
Definition at line 52 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onGroupRemoved (java\&.lang\&.String p0)"

.PP
Definition at line 60 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onGroupRemoved (java\&.lang\&.String p0)"

.PP
Definition at line 60 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onPaused (java\&.lang\&.String p0, java\&.lang\&.String p1)"

.PP
Definition at line 68 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onPaused (java\&.lang\&.String p0, java\&.lang\&.String p1)"

.PP
Definition at line 68 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onPreparedLog (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1, int p2)"

.PP
Definition at line 76 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onPreparedLog (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1, int p2)"

.PP
Definition at line 76 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onPreparingLog (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1)"

.PP
Definition at line 84 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onPreparingLog (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.String p1)"

.PP
Definition at line 84 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onResumed (java\&.lang\&.String p0, java\&.lang\&.String p1)"

.PP
Definition at line 92 of file Channel_ListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.onResumed (java\&.lang\&.String p0, java\&.lang\&.String p1)"

.PP
Definition at line 92 of file Channel_ListenerImplementor\&.java\&.
.SS "boolean mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.shouldFilter (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"

.PP
Definition at line 100 of file Channel_ListenerImplementor\&.java\&.
.SS "boolean mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.shouldFilter (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"

.PP
Definition at line 100 of file Channel_ListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.com\&.microsoft\&.appcenter\&.channel\&.Channel_ListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file Channel_ListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
