.TH "mono.com.microsoft.appcenter.analytics.channel.AnalyticsListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.com.microsoft.appcenter.analytics.channel.AnalyticsListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnalyticsListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonBeforeSending\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"
.br
.ti -1c
.RI "void \fBonSendingFailed\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.Exception p1)"
.br
.ti -1c
.RI "void \fBonSendingSucceeded\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBAnalyticsListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonBeforeSending\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"
.br
.ti -1c
.RI "void \fBonSendingFailed\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.Exception p1)"
.br
.ti -1c
.RI "void \fBonSendingSucceeded\fP (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file AnalyticsListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.AnalyticsListenerImplementor ()"

.PP
Definition at line 22 of file AnalyticsListenerImplementor\&.java\&.
.SS "mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.AnalyticsListenerImplementor ()"

.PP
Definition at line 22 of file AnalyticsListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 54 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 54 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 61 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 61 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.onBeforeSending (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"

.PP
Definition at line 30 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.onBeforeSending (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"

.PP
Definition at line 30 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.onSendingFailed (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.Exception p1)"

.PP
Definition at line 38 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.onSendingFailed (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0, java\&.lang\&.Exception p1)"

.PP
Definition at line 38 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.onSendingSucceeded (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"

.PP
Definition at line 46 of file AnalyticsListenerImplementor\&.java\&.
.SS "void mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.onSendingSucceeded (com\&.microsoft\&.appcenter\&.ingestion\&.models\&.Log p0)"

.PP
Definition at line 46 of file AnalyticsListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.com\&.microsoft\&.appcenter\&.analytics\&.channel\&.AnalyticsListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file AnalyticsListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
