.TH "mono.MonoRuntimeProvider" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.MonoRuntimeProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits android\&.content\&.ContentProvider, android\&.content\&.ContentProvider, android\&.content\&.ContentProvider, and android\&.content\&.ContentProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMonoRuntimeProvider\fP ()"
.br
.ti -1c
.RI "boolean \fBonCreate\fP ()"
.br
.ti -1c
.RI "void \fBattachInfo\fP (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"
.br
.ti -1c
.RI "android\&.database\&.Cursor \fBquery\fP (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"
.br
.ti -1c
.RI "String \fBgetType\fP (android\&.net\&.Uri uri)"
.br
.ti -1c
.RI "android\&.net\&.Uri \fBinsert\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"
.br
.ti -1c
.RI "int \fBdelete\fP (android\&.net\&.Uri uri, String where, String[] whereArgs)"
.br
.ti -1c
.RI "int \fBupdate\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"
.br
.ti -1c
.RI "\fBMonoRuntimeProvider\fP ()"
.br
.ti -1c
.RI "boolean \fBonCreate\fP ()"
.br
.ti -1c
.RI "void \fBattachInfo\fP (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"
.br
.ti -1c
.RI "android\&.database\&.Cursor \fBquery\fP (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"
.br
.ti -1c
.RI "String \fBgetType\fP (android\&.net\&.Uri uri)"
.br
.ti -1c
.RI "android\&.net\&.Uri \fBinsert\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"
.br
.ti -1c
.RI "int \fBdelete\fP (android\&.net\&.Uri uri, String where, String[] whereArgs)"
.br
.ti -1c
.RI "int \fBupdate\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"
.br
.ti -1c
.RI "\fBMonoRuntimeProvider\fP ()"
.br
.ti -1c
.RI "boolean \fBonCreate\fP ()"
.br
.ti -1c
.RI "void \fBattachInfo\fP (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"
.br
.ti -1c
.RI "android\&.database\&.Cursor \fBquery\fP (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"
.br
.ti -1c
.RI "String \fBgetType\fP (android\&.net\&.Uri uri)"
.br
.ti -1c
.RI "android\&.net\&.Uri \fBinsert\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"
.br
.ti -1c
.RI "int \fBdelete\fP (android\&.net\&.Uri uri, String where, String[] whereArgs)"
.br
.ti -1c
.RI "int \fBupdate\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"
.br
.ti -1c
.RI "\fBMonoRuntimeProvider\fP ()"
.br
.ti -1c
.RI "boolean \fBonCreate\fP ()"
.br
.ti -1c
.RI "void \fBattachInfo\fP (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"
.br
.ti -1c
.RI "android\&.database\&.Cursor \fBquery\fP (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"
.br
.ti -1c
.RI "String \fBgetType\fP (android\&.net\&.Uri uri)"
.br
.ti -1c
.RI "android\&.net\&.Uri \fBinsert\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"
.br
.ti -1c
.RI "int \fBdelete\fP (android\&.net\&.Uri uri, String where, String[] whereArgs)"
.br
.ti -1c
.RI "int \fBupdate\fP (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file MonoRuntimeProvider\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.MonoRuntimeProvider\&.MonoRuntimeProvider ()"

.PP
Definition at line 8 of file MonoRuntimeProvider\&.java\&.
.SS "mono\&.MonoRuntimeProvider\&.MonoRuntimeProvider ()"

.PP
Definition at line 8 of file MonoRuntimeProvider\&.java\&.
.SS "mono\&.MonoRuntimeProvider\&.MonoRuntimeProvider ()"

.PP
Definition at line 8 of file MonoRuntimeProvider\&.java\&.
.SS "mono\&.MonoRuntimeProvider\&.MonoRuntimeProvider ()"

.PP
Definition at line 8 of file MonoRuntimeProvider\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.MonoRuntimeProvider\&.attachInfo (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"

.PP
Definition at line 19 of file MonoRuntimeProvider\&.java\&.
.SS "void mono\&.MonoRuntimeProvider\&.attachInfo (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"

.PP
Definition at line 19 of file MonoRuntimeProvider\&.java\&.
.SS "void mono\&.MonoRuntimeProvider\&.attachInfo (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"

.PP
Definition at line 19 of file MonoRuntimeProvider\&.java\&.
.SS "void mono\&.MonoRuntimeProvider\&.attachInfo (android\&.content\&.Context context, android\&.content\&.pm\&.ProviderInfo info)"

.PP
Definition at line 19 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.delete (android\&.net\&.Uri uri, String where, String[] whereArgs)"

.PP
Definition at line 59 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.delete (android\&.net\&.Uri uri, String where, String[] whereArgs)"

.PP
Definition at line 59 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.delete (android\&.net\&.Uri uri, String where, String[] whereArgs)"

.PP
Definition at line 59 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.delete (android\&.net\&.Uri uri, String where, String[] whereArgs)"

.PP
Definition at line 59 of file MonoRuntimeProvider\&.java\&.
.SS "String mono\&.MonoRuntimeProvider\&.getType (android\&.net\&.Uri uri)"

.PP
Definition at line 47 of file MonoRuntimeProvider\&.java\&.
.SS "String mono\&.MonoRuntimeProvider\&.getType (android\&.net\&.Uri uri)"

.PP
Definition at line 47 of file MonoRuntimeProvider\&.java\&.
.SS "String mono\&.MonoRuntimeProvider\&.getType (android\&.net\&.Uri uri)"

.PP
Definition at line 47 of file MonoRuntimeProvider\&.java\&.
.SS "String mono\&.MonoRuntimeProvider\&.getType (android\&.net\&.Uri uri)"

.PP
Definition at line 47 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.net\&.Uri mono\&.MonoRuntimeProvider\&.insert (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"

.PP
Definition at line 53 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.net\&.Uri mono\&.MonoRuntimeProvider\&.insert (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"

.PP
Definition at line 53 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.net\&.Uri mono\&.MonoRuntimeProvider\&.insert (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"

.PP
Definition at line 53 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.net\&.Uri mono\&.MonoRuntimeProvider\&.insert (android\&.net\&.Uri uri, android\&.content\&.ContentValues initialValues)"

.PP
Definition at line 53 of file MonoRuntimeProvider\&.java\&.
.SS "boolean mono\&.MonoRuntimeProvider\&.onCreate ()"

.PP
Definition at line 13 of file MonoRuntimeProvider\&.java\&.
.SS "boolean mono\&.MonoRuntimeProvider\&.onCreate ()"

.PP
Definition at line 13 of file MonoRuntimeProvider\&.java\&.
.SS "boolean mono\&.MonoRuntimeProvider\&.onCreate ()"

.PP
Definition at line 13 of file MonoRuntimeProvider\&.java\&.
.SS "boolean mono\&.MonoRuntimeProvider\&.onCreate ()"

.PP
Definition at line 13 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.database\&.Cursor mono\&.MonoRuntimeProvider\&.query (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"

.PP
Definition at line 41 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.database\&.Cursor mono\&.MonoRuntimeProvider\&.query (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"

.PP
Definition at line 41 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.database\&.Cursor mono\&.MonoRuntimeProvider\&.query (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"

.PP
Definition at line 41 of file MonoRuntimeProvider\&.java\&.
.SS "android\&.database\&.Cursor mono\&.MonoRuntimeProvider\&.query (android\&.net\&.Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder)"

.PP
Definition at line 41 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.update (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"

.PP
Definition at line 65 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.update (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"

.PP
Definition at line 65 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.update (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"

.PP
Definition at line 65 of file MonoRuntimeProvider\&.java\&.
.SS "int mono\&.MonoRuntimeProvider\&.update (android\&.net\&.Uri uri, android\&.content\&.ContentValues values, String where, String[] whereArgs)"

.PP
Definition at line 65 of file MonoRuntimeProvider\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
