.TH "mono.androidx.appcompat.app.ActionBar_OnMenuVisibilityListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.appcompat.app.ActionBar_OnMenuVisibilityListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.app\&.ActionBar\&.OnMenuVisibilityListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.app\&.ActionBar\&.OnMenuVisibilityListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.appcompat\&.app\&.ActionBar\&.OnMenuVisibilityListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and androidx\&.appcompat\&.app\&.ActionBar\&.OnMenuVisibilityListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActionBar_OnMenuVisibilityListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonMenuVisibilityChanged\fP (boolean p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBActionBar_OnMenuVisibilityListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonMenuVisibilityChanged\fP (boolean p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBActionBar_OnMenuVisibilityListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonMenuVisibilityChanged\fP (boolean p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBActionBar_OnMenuVisibilityListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonMenuVisibilityChanged\fP (boolean p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.ActionBar_OnMenuVisibilityListenerImplementor ()"

.PP
Definition at line 20 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.ActionBar_OnMenuVisibilityListenerImplementor ()"

.PP
Definition at line 20 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.ActionBar_OnMenuVisibilityListenerImplementor ()"

.PP
Definition at line 20 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.ActionBar_OnMenuVisibilityListenerImplementor ()"

.PP
Definition at line 20 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.onMenuVisibilityChanged (boolean p0)"

.PP
Definition at line 28 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.onMenuVisibilityChanged (boolean p0)"

.PP
Definition at line 28 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.onMenuVisibilityChanged (boolean p0)"

.PP
Definition at line 28 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.onMenuVisibilityChanged (boolean p0)"

.PP
Definition at line 28 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.androidx\&.appcompat\&.app\&.ActionBar_OnMenuVisibilityListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file ActionBar_OnMenuVisibilityListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
