.TH "mono.androidx.dynamicanimation.animation.DynamicAnimation_OnAnimationEndListenerImplementor" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.androidx.dynamicanimation.animation.DynamicAnimation_OnAnimationEndListenerImplementor
.SH SYNOPSIS
.br
.PP
.PP
Inherits java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.dynamicanimation\&.animation\&.DynamicAnimation\&.OnAnimationEndListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.dynamicanimation\&.animation\&.DynamicAnimation\&.OnAnimationEndListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, androidx\&.dynamicanimation\&.animation\&.DynamicAnimation\&.OnAnimationEndListener, java\&.lang\&.Object, mono\&.android\&.IGCUserPeer, and androidx\&.dynamicanimation\&.animation\&.DynamicAnimation\&.OnAnimationEndListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamicAnimation_OnAnimationEndListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationEnd\fP (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDynamicAnimation_OnAnimationEndListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationEnd\fP (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDynamicAnimation_OnAnimationEndListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationEnd\fP (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.ti -1c
.RI "\fBDynamicAnimation_OnAnimationEndListenerImplementor\fP ()"
.br
.ti -1c
.RI "void \fBonAnimationEnd\fP (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fB__md_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.DynamicAnimation_OnAnimationEndListenerImplementor ()"

.PP
Definition at line 20 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.DynamicAnimation_OnAnimationEndListenerImplementor ()"

.PP
Definition at line 20 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.DynamicAnimation_OnAnimationEndListenerImplementor ()"

.PP
Definition at line 20 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.DynamicAnimation_OnAnimationEndListenerImplementor ()"

.PP
Definition at line 20 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidAddReference (java\&.lang\&.Object obj)"

.PP
Definition at line 36 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.monodroidClearReferences ()"

.PP
Definition at line 43 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.onAnimationEnd (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"

.PP
Definition at line 28 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.onAnimationEnd (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"

.PP
Definition at line 28 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.onAnimationEnd (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"

.PP
Definition at line 28 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SS "void mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.onAnimationEnd (androidx\&.dynamicanimation\&.animation\&.DynamicAnimation p0, boolean p1, float p2, float p3)"

.PP
Definition at line 28 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "static final String mono\&.androidx\&.dynamicanimation\&.animation\&.DynamicAnimation_OnAnimationEndListenerImplementor\&.__md_methods\fC [static]\fP"
@hide 
.PP
Definition at line 11 of file DynamicAnimation_OnAnimationEndListenerImplementor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
