.TH "mono.com.google.android.material.button" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.com.google.android.material.button
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaterialButton_OnCheckedChangeListenerImplementor\fP"
.br
.ti -1c
.RI "class \fBMaterialButtonToggleGroup_OnButtonCheckedListenerImplementor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
