.TH "Application Green Quake.Android/obj/Release/110/android/src/crc643dd37f507f3d9710/PopupPageRenderer.java" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/crc643dd37f507f3d9710/PopupPageRenderer.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcrc643dd37f507f3d9710\&.PopupPageRenderer\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcrc643dd37f507f3d9710\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
