.TH "Application Green Quake.Android/Resources/Resource.designer.cs" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/Resources/Resource.designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Animation\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Animator\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Attribute\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Boolean\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Color\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Dimension\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Drawable\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Id\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Integer\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Interpolator\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Layout\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Mipmap\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Plurals\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.String\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Style\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Styleable\fP"
.br
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Droid\&.Resource\&.Xml\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBApplication_Green_Quake\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Droid\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
