.TH "Application Green Quake.Android/obj/Release/110/android/src/mono/androidx/appcompat/widget/ShareActionProvider_OnShareTargetSelectedListenerImplementor.java" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Release/110/android/src/mono/androidx/appcompat/widget/ShareActionProvider_OnShareTargetSelectedListenerImplementor.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmono\&.androidx\&.appcompat\&.widget\&.ShareActionProvider_OnShareTargetSelectedListenerImplementor\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBmono\&.androidx\&.appcompat\&.widget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
