.TH "Application Green Quake.Android/obj/Debug/110/android/src/crc64f606ab658bf2774f/ShimmerViewRenderer.java" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake.Android/obj/Debug/110/android/src/crc64f606ab658bf2774f/ShimmerViewRenderer.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcrc64f606ab658bf2774f\&.ShimmerViewRenderer\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcrc64f606ab658bf2774f\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
