.TH "The" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the IAuth Interface\&. It is the interface between the cross platform code and the native code\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the AdvancedPoints Model Class
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the AppConstants Model Class in contains the constants that are used throughout this application\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the CommunityPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EnergyPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the FoodAndDrinkPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HabitsPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HomePoints Model Class\&.
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ImageResourceExtension Class\&. It is used for loading image files\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the LeaderBoard Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OutdoorsPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Points Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SecurityChecks Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ShoppingPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Station Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TravelPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Usernames Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Users Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WastePoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WaterPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WorkPoints Model Class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the AdvancedPointsUpdate ViewModel Class\&. It updates the data for the Advanced Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the CommunityPointsUpdate ViewModel Class\&. It updates the data for the Community Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EnergyPointsUpdate ViewModel Class\&. It updates the data for the Energy Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the FoodAndDrinkPointsUpdate ViewModel Class\&. It updates the data for the Food And Drink Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the GetAchievementsData ViewModel Class\&. It gets data that is needed for Achievements from firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the GetBadgeData ViewModel Class\&. It gets data that is needed for badges from firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the GetData ViewModel Class\&. It gets data that is needed for the applications back end and front end\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HabitsPointsUpdate ViewModel Class\&. It updates the data for the Habits Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HomePointsUpdate ViewModel Class\&. It updates the data for the Home Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OutdoorsPointsUpdate ViewModel Class\&. It updates the data for the Outdoors Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PointsUpdate ViewModel Class\&. It updates the data for the Overall Points of user for the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SecurityMethods ViewModel Class\&. It performs security checks for the application whenever a log is made in the application\&. It prevents the user from logging more than 15 actions per day and more than 1 action per 60 seconds\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ShoppingPointsUpdate ViewModel Class\&. It updates the data for the Shopping Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TravelPointsUpdate ViewModel Class\&. It updates the data for the Travel Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WastePointsUpdate ViewModel Class\&. It updates the data for the Waste Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WaterPointsUpdate ViewModel Class\&. It updates the data for the Water Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WorkPointsUpdate ViewModel Class\&. It updates the data for the Work Category of the application\&. \fBThe\fP functions in this class work by reading in all the chosen data and updating the selected fields and then sending this data to back firebase\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the FixInsteadOfThrowAway View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the CreateEnvironmentalGroup View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the DoCommunity View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the DonateItems View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EnvironmentalGroups View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ShareThisApp View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SpreadAwareness View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ActionsCategories View Class\&. This page displays and allows the navigation to each of the 12 main categories\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the AdvancedPage View Class\&. This page displays and allows the navigation to each of the actions in the Advanced category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the CommunityPage View Class\&. This page displays and allows the navigation to each of the actions in the Community category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EnergyPage View Class\&. This page displays and allows the navigation to each of the actions in the Energy category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the FoodAndDrinkPage View Class\&. This page displays and allows the navigation to each of the actions in the FoodAndDrink category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HabitsPage View Class\&. This page displays and allows the navigation to each of the actions in the Habits category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HomePage View Class\&. This page displays and allows the navigation to each of the actions in the Home category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OutdoorsPage View Class\&. This page displays and allows the navigation to each of the actions in the Outdoors category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ShoppingPage View Class\&. This page displays and allows the navigation to each of the actions in the Shopping category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TravelPage View Class\&. This page displays and allows the navigation to each of the actions in the Travel category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WastePage View Class\&. This page displays and allows the navigation to each of the actions in the Waste category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WaterPage View Class\&. This page displays and allows the navigation to each of the actions in the Water category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WorkPage View Class\&. This page displays and allows the navigation to each of the actions in the Work category\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the DryerFull View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EfficientThermostat View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the HangDry View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the InsulateWater View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the IsolateHome View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the LedLightBulb View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the MachineFull View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the MicrowaveNotOven View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OffSocketSwitch View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ReBatteries View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the RefrigiratorDown View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SealDrafts View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SealDucts View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SolarPanel View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the BuyOrganicFood View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EatAllYouMake View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the FoodDelivered View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the NoMeat View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OwnCoffee View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ReCoffeeMug View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SaveLeftOvers View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SteelStraw View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WaterOverFizzy View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the BrushingTeeth View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the DishwasherFull View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ShowerInstead View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TimedShower View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TurnOffLights View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the UseMatches View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the AirOutHome View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the NonHarmfulProducts View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OutsideOnce View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PlantIntoHome View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ToiletFlushes View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the GoCamping View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Picnic View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PlantABush View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PlantAFlower View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PlantATree View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Scoop View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SetUpFruitGarden View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SetUpHerbGarden View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SetUpVegetableGarden View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the UpBirdfeeder View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ClothNapkins View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ClothTowels View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EcoFreidnlyApplicance View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EcoFriendlyProduct View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EcoFriendlyToothbrush View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EthicalClothes View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the FoodInBulk View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the LocalProduct View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the LooseLeafTea View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the OrganicFood View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PurchaseReusableWater View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ReusableBag View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Carpool View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Cycle View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the EcoFreindlyCar View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the PublicTransport View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Walk View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the BillsOnline View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the CompostWaste View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SetUpRecyclingBin View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the UseBiogradableBinBags View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the UseRecyclingBin View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the CisternDisplacement View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the RainBarrel View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ReusableWater View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ShowerBucket View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the WSShowerHead View Class\&. This class is the eco action that the user can log\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the ForgotPasswordPage View Class\&. This page allows a user to request a password reset email after successful validation\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the LeaderBoardPopUp View Class\&. This class is the popup that appears when a entry in the LeaderBoard is tapped\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TopTabLeaderBoard View Class\&. This is the class for the leaderboard screen\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the LoginSplashPage View Class\&. This class provides the splash screen when a user logs into the applciation\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the MainMenu View Class\&. This page is the main menu of the application and provides navigation to all the apps screens\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the MainPage View Class\&. This is the class that allows a user to login to the application\&. It contains validation checks\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Achievements View Class\&. This class is the class that displays all the Achievements on the Achievements page\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the BadgePopUp View Class\&. This class is the popup that appears when a badge is tapped\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the Badges View Class\&. This class is the class that displays all the Badges on the Badges page\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TopTabProfile View Class\&. \fBThe\fP progile page class\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the TrophyCase View Class\&. This class is the class that displays all the trophies on the trophy page\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the UploadImagePopUp View Class\&. This class is the popup that appears to upload a new profile picture\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the RefillStation View Class\&. This page contains the map and loads data from firebase and then uses this data to display the pins\&.
.PP
Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the SignUpPage View Class\&. This is the class that allows a user to sign up for the application\&. It contains validation checks\&.
.PP
Android Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the AuthDroid Native Android Class\&. This is implements native functions to check if a user is signed in, o try and log in, to try and sign up to get their uid and to get a password rest email\&.
.PP
Android Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the MainActivity Native Android Class\&. It had to be modified to make certain Nuget Packages and APIs work
.PP
Android Class 
.PP
\fBAuthor\fP
.RS 4
Peter Lucan, 4th Year Software Development student at IT Carlow, C00228946, c00228956@itcarlow.ie 
.RE
.PP
\fBDate\fP
.RS 4
28/04/2021 
.RE
.PP
.SH "Description"
.PP
Description: This is the \fBMainApplication\fP Native Android Class\&. It had to be modified to make the APKs work 

.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
