.TH "Application Green Quake/Views/LeaderboardPage/TopTabLeaderBoard.xaml.cs" 3 "Thu Apr 29 2021" "Version 1.0" "Green Quake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application Green Quake/Views/LeaderboardPage/TopTabLeaderBoard.xaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication_Green_Quake\&.Views\&.LeaderboardPage\&.TopTabLeaderBoard\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBApplication_Green_Quake\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Views\fP"
.br
.ti -1c
.RI "namespace \fBApplication_Green_Quake\&.Views\&.LeaderboardPage\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBSelectionChangedEventArgs\fP = Syncfusion\&.SfPicker\&.XForms\&.SelectionChangedEventArgs"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBSelectionChangedEventArgs\fP =  Syncfusion\&.SfPicker\&.XForms\&.SelectionChangedEventArgs"

.PP
Definition at line 21 of file TopTabLeaderBoard\&.xaml\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Green Quake from the source code\&.
